---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


## NOTICE on items in this file:
##   * If you use anything in the *._git_install_branch field that is not a TAG
##     make sure to leave an in-line comment as to "why".

## For the sake of anyone else editing this file:
##   * If you add services to this file please do so in alphabetical order.
##   * Every entry should be name spaced with the name of the client followed by an "_"
##   * All items with this file should be separated by `name_` note that the name of the
##     package should be one long name with no additional `_` separating it.


### Before this is shipped all of these services should have a tag set as the branch,
### or have a comment / reason attached to them as to why a tag can not work.


## Global Requirements
requirements_git_repo: https://git.openstack.org/openstack/requirements
requirements_git_install_branch: 8c514ba0db5518889f6a2fb79af5e710aacb724c # HEAD of "stable/ocata" as of 23.09.2018
requirements_git_dest: "/opt/requirements_{{ requirements_git_install_branch | replace('/', '_') }}"
requirements_git_track_branch: stable/ocata


## Aodh service
aodh_git_repo: https://git.openstack.org/openstack/aodh
aodh_git_install_branch: a6d28c2e146ee73a4faade1c14b1cf10e4306fb4 # HEAD of "stable/ocata" as of 23.09.2018
aodh_git_dest: "/opt/aodh_{{ aodh_git_install_branch | replace('/', '_') }}"
aodh_git_project_group: aodh_all
aodh_git_track_branch: stable/ocata


## Barbican service
barbican_git_repo: https://git.openstack.org/openstack/barbican
barbican_git_install_branch: dce65cfed11100df4e92aa429d1eed35d737a847 # HEAD of "stable/ocata" as of 23.09.2018
barbican_git_dest: "/opt/barbican_{{ barbican_git_install_branch | replace('/', '_') }}"
barbican_git_project_group: barbican_all
barbican_git_track_branch: stable/ocata


## Ceilometer service
ceilometer_git_repo: https://git.openstack.org/openstack/ceilometer
ceilometer_git_install_branch: 1ab279745bb112582f2ed8b6f670cb6adf96824f # HEAD of "stable/ocata" as of 23.09.2018
ceilometer_git_dest: "/opt/ceilometer_{{ceilometer_git_install_branch | replace('/', '_') }}"
ceilometer_git_project_group: ceilometer_all
ceilometer_git_track_branch: stable/ocata


## Cinder service
cinder_git_repo: https://git.openstack.org/openstack/cinder
cinder_git_install_branch: 2dc52153215bb6a37532a959c5c98239be21bb56 # HEAD of "stable/ocata" as of 23.09.2018
cinder_git_dest: "/opt/cinder_{{ cinder_git_install_branch | replace('/', '_') }}"
cinder_git_project_group: cinder_all
cinder_git_track_branch: stable/ocata


## Designate service
designate_git_repo: https://git.openstack.org/openstack/designate
designate_git_install_branch: fff74696bc3f47e8d0ea6194d120a9615d2bb8b8 # HEAD of "stable/ocata" as of 23.09.2018
designate_git_dest: "/opt/designate_{{ designate_git_install_branch | replace('/', '_') }}"
designate_git_project_group: designate_all
designate_git_track_branch: stable/ocata


## Horizon Designate dashboard plugin
designate_dashboard_git_repo: https://git.openstack.org/openstack/designate-dashboard
designate_dashboard_git_install_branch: 77a32db03e808efe72f30c7a5078d989179e43db # HEAD of "stable/ocata" as of 23.09.2018
designate_dashboard_git_dest: "/opt/designate_dashboard_{{ designate_dashboard_git_install_branch | replace('/', '_') }}"
designate_dashboard_git_project_group: horizon_all
designate_dashboard_git_track_branch: stable/ocata


## Dragonflow service
dragonflow_git_repo: https://git.openstack.org/openstack/dragonflow
dragonflow_git_install_branch: 2af283306930965a775b46dbfdb00339ed770b29 # HEAD of "stable/ocata" as of 23.09.2018
dragonflow_git_dest: "/opt/dragonflow_{{ dragonflow_git_install_branch | replace('/', '_') }}"
dragonflow_git_project_group: neutron_all
dragonflow_git_track_branch: stable/ocata


## Glance service
glance_git_repo: https://git.openstack.org/openstack/glance
glance_git_install_branch: 58a9bd4eb1c43b2312042f4da86ec8f9dad7aac1 # HEAD of "stable/ocata" as of 23.09.2018
glance_git_dest: "/opt/glance_{{ glance_git_install_branch | replace('/', '_') }}"
glance_git_project_group: glance_all
glance_git_track_branch: stable/ocata


## Heat service
heat_git_repo: https://git.openstack.org/openstack/heat
heat_git_install_branch: cb8bd3aa67c7aa90c5e6569a1a6274970bcf902d # HEAD of "stable/ocata" as of 23.09.2018
heat_git_dest: "/opt/heat_{{ heat_git_install_branch | replace('/', '_') }}"
heat_git_project_group: heat_all
heat_git_track_branch: stable/ocata


## Horizon service
horizon_git_repo: https://git.openstack.org/openstack/horizon
horizon_git_install_branch: 60c150df0440a9604ce09e945e14abc10ede22d6 # HEAD of "stable/ocata" as of 23.09.2018
horizon_git_dest: "/opt/horizon_{{ horizon_git_install_branch | replace('/', '_') }}"
horizon_git_project_group: horizon_all
horizon_git_track_branch: stable/ocata

## Horizon Ironic dashboard plugin
ironic_dashboard_git_repo: https://git.openstack.org/openstack/ironic-ui
ironic_dashboard_git_install_branch: 6c70c8ef6b104e121db0311aa035affc3680a00f # HEAD of "stable/ocata" as of 23.09.2018
ironic_dashboard_git_dest: "/opt/ironic_dashboard_{{ ironic_dashboard_git_install_branch | replace('/', '_') }}"
ironic_dashboard_git_project_group: horizon_all
ironic_dashboard_git_track_branch: stable/ocata

## Horizon Magnum dashboard plugin
magnum_dashboard_git_repo: https://git.openstack.org/openstack/magnum-ui
magnum_dashboard_git_install_branch: 078780d6824117505f355ef5ce5391ddf60caeab # HEAD of "stable/ocata" as of 23.09.2018
magnum_dashboard_git_dest: "/opt/magnum_dashboard_{{ magnum_dashboard_git_install_branch | replace('/', '_') }}"
magnum_dashboard_git_project_group: horizon_all
magnum_dashboard_git_track_branch: stable/ocata

## Horizon LBaaS dashboard plugin
neutron_lbaas_dashboard_git_repo: https://git.openstack.org/openstack/neutron-lbaas-dashboard
neutron_lbaas_dashboard_git_install_branch: be052c5212c8da384f2a15c25e153d9cf638815a # HEAD of "stable/ocata" as of 23.09.2018
neutron_lbaas_dashboard_git_dest: "/opt/neutron_lbaas_dashboard_{{ neutron_lbaas_dashboard_git_install_branch | replace('/', '_') }}"
neutron_lbaas_dashboard_git_project_group: horizon_all
neutron_lbaas_dashboard_git_track_branch: stable/ocata

## Horizon Sahara dashboard plugin
sahara_dashboard_git_repo: https://git.openstack.org/openstack/sahara-dashboard
sahara_dashboard_git_install_branch: 08db9cb5bbdba3d7b8d49416f4eefcf27c70845e # HEAD of "stable/ocata" as of 23.09.2018
sahara_dashboard_git_dest: "/opt/sahara_dashboard_{{ sahara_dashboard_git_install_branch | replace('/', '_') }}"
sahara_dashboard_git_project_group: horizon_all
sahara_dashboard_git_track_branch: stable/ocata

## Keystone service
keystone_git_repo: https://git.openstack.org/openstack/keystone
keystone_git_install_branch: e1f7752199cca4b5f871c02282bf72336efcfbeb # HEAD of "stable/ocata" as of 23.09.2018
keystone_git_dest: "/opt/keystone_{{ keystone_git_install_branch | replace('/', '_') }}"
keystone_git_project_group: keystone_all
keystone_git_track_branch: stable/ocata


## Neutron service
neutron_git_repo: https://git.openstack.org/openstack/neutron
neutron_git_install_branch: b9a2864cc9b950eac9e76090c57cd39e6580bf05 # HEAD of "stable/ocata" as of 23.09.2018
neutron_git_dest: "/opt/neutron_{{ neutron_git_install_branch | replace('/', '_') }}"
neutron_git_project_group: neutron_all
neutron_git_track_branch: stable/ocata

neutron_lbaas_git_repo: https://git.openstack.org/openstack/neutron-lbaas
neutron_lbaas_git_install_branch: adeb3be01aed1e0775174a860599b24b35e4bf6e # HEAD of "stable/ocata" as of 23.09.2018
neutron_lbaas_git_dest: "/opt/neutron_lbaas_{{ neutron_lbaas_git_install_branch | replace('/', '_') }}"
neutron_lbaas_git_project_group: neutron_all
neutron_lbaas_git_track_branch: stable/ocata

neutron_vpnaas_git_repo: https://git.openstack.org/openstack/neutron-vpnaas
neutron_vpnaas_git_install_branch: dc90ddaae55b06bebca11ea17364391ae3762596 # HEAD of "stable/ocata" as of 23.09.2018
neutron_vpnaas_git_dest: "/opt/neutron_vpnaas_{{ neutron_vpnaas_git_install_branch | replace('/', '_') }}"
neutron_vpnaas_git_project_group: neutron_all
neutron_vpnaas_git_track_branch: stable/ocata

neutron_fwaas_git_repo: https://git.openstack.org/openstack/neutron-fwaas
neutron_fwaas_git_install_branch: 9d6ba1724932dc215a27b44e8e8a74378984a3ca # HEAD of "stable/ocata" as of 23.09.2018
neutron_fwaas_git_dest: "/opt/neutron_fwaas_{{ neutron_fwaas_git_install_branch | replace('/', '_') }}"
neutron_fwaas_git_project_group: neutron_all
neutron_fwaas_git_track_branch: stable/ocata

neutron_dynamic_routing_git_repo: https://git.openstack.org/openstack/neutron-dynamic-routing
neutron_dynamic_routing_git_install_branch: 099f0f81d98b4f77b0591a7a0e9a0e8b596b9546 # HEAD of "stable/ocata" as of 23.09.2018
neutron_dynamic_routing_git_dest: "/opt/neutron_dynamic_routing_{{ neutron_dynamic_routing_git_install_branch | replace('/', '_') }}"
neutron_dynamic_routing_git_project_group: neutron_all
neutron_dynamic_routing_git_track_branch: stable/ocata

networking_calico_git_repo: https://git.openstack.org/openstack/networking-calico
networking_calico_git_install_branch: 501fc98c428b8dd6b9dd7bf6908dbcd7b94ead5c # HEAD of "master" as of 23.09.2018
networking_calico_git_project_group: neutron_all
networking_calico_git_track_branch: master

## Nova service
nova_git_repo: https://git.openstack.org/openstack/nova
nova_git_install_branch: 72ab303ef493b29b70654b681749269eb4bbe2c4 # HEAD of "stable/ocata" as of 23.09.2018
nova_git_dest: "/opt/nova_{{ nova_git_install_branch | replace('/', '_') }}"
nova_git_project_group: nova_all
nova_git_track_branch: stable/ocata


## PowerVM Virt Driver
nova_powervm_git_repo: https://git.openstack.org/openstack/nova-powervm
nova_powervm_git_install_branch: 43c094759bcb6d0f1fd6c3b90d2cc3c99cab7035 # HEAD of "stable/ocata" as of 23.09.2018
nova_powervm_git_dest: "/opt/nova_powervm_{{ nova_powervm_git_install_branch | replace('/', '_') }}"
nova_powervm_git_project_group: nova_all
nova_powervm_git_track_branch: stable/ocata


## LXD Virt Driver
nova_lxd_git_repo: https://git.openstack.org/openstack/nova-lxd
nova_lxd_git_install_branch: cc7585651f4f81f809d8864661553af4fec7ecea # HEAD of "stable/ocata" as of 23.09.2018
nova_lxd_git_dest: "/opt/nova_lxd_{{ nova_lxd_git_install_branch | replace('/', '_') }}"
nova_lxd_git_project_group: nova_all
nova_lxd_git_track_branch: stable/ocata


## Sahara service
sahara_git_repo: https://git.openstack.org/openstack/sahara
sahara_git_install_branch: fc4afbf120b08082f160caa8b1b01ef5fa94aacd # HEAD of "stable/ocata" as of 23.09.2018
sahara_git_dest: "/opt/sahara_{{ sahara_git_install_branch | replace('/', '_') }}"
sahara_git_project_group: sahara_all
sahara_git_track_branch: stable/ocata


## Swift service
swift_git_repo: https://git.openstack.org/openstack/swift
swift_git_install_branch: 3aff40b0bf6fc63a9185ee349d5e195b1198959a # HEAD of "stable/ocata" as of 23.09.2018
swift_git_dest: "/opt/swift_{{ swift_git_install_branch | replace('/', '_') }}"
swift_git_project_group: swift_all
swift_git_track_branch: stable/ocata


## Swift3 middleware
swift_swift3_git_repo: https://git.openstack.org/openstack/swift3
swift_swift3_git_install_branch: 90db5d1510b2a770387961e7bf0fbeae8101ba45 # FROZEN HEAD of "master" as of 22.08.2018
swift_swift3_git_project_group: swift_all
swift_swift3_git_track_branch: None


## Ironic service
ironic_git_repo: https://git.openstack.org/openstack/ironic
ironic_git_install_branch: 94d03ef7a918208b7dd3012b20bb5dc45d137239 # HEAD of "stable/ocata" as of 23.09.2018
ironic_git_dest: "/opt/ironic_{{ ironic_git_install_branch | replace('/', '_') }}"
ironic_git_project_group: ironic_all
ironic_git_track_branch: stable/ocata

## Magnum service
magnum_git_repo: https://git.openstack.org/openstack/magnum
magnum_git_install_branch: 6019899a359e3a50ec5b66136057f15968d10974 # HEAD of "stable/ocata" as of 23.09.2018
magnum_git_dest: "/opt/magnum_{{ magnum_git_install_branch | replace('/', '_') }}"
magnum_git_project_group: magnum_all
magnum_git_track_branch: stable/ocata

## Trove service
trove_git_repo: https://git.openstack.org/openstack/trove
trove_git_install_branch: 0d2aa489caec1f6d1e3b24fea32b4d513e447448 # HEAD of "stable/ocata" as of 23.09.2018
trove_git_dest: "/opt/trove_{{ trove_git_install_branch | replace('/', '_') }}"
trove_git_project_group: trove_all
trove_git_track_branch: stable/ocata

## Horizon Trove dashboard plugin
trove_dashboard_git_repo: https://git.openstack.org/openstack/trove-dashboard
trove_dashboard_git_install_branch: e88344200a0b3e03f644a98723ff5fa1b670df7a # HEAD of "stable/ocata" as of 23.09.2018
trove_dashboard_git_dest: "/opt/trove_dashboard_{{ trove_dashboard_git_install_branch | replace('/', '_') }}"
trove_dashboard_git_project_group: horizon_all
trove_dashboard_git_track_branch: stable/ocata
