---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


## NOTICE on items in this file:
##   * If you use anything in the *._git_install_branch field that is not a TAG
##     make sure to leave an in-line comment as to "why".

## For the sake of anyone else editing this file:
##   * If you add services to this file please do so in alphabetical order.
##   * Every entry should be name spaced with the name of the client followed by an "_"
##   * All items with this file should be separated by `name_` note that the name of the
##     package should be one long name with no additional `_` separating it.


### Before this is shipped all of these services should have a tag set as the branch,
### or have a comment / reason attached to them as to why a tag can not work.


## Global Requirements
requirements_git_repo: https://opendev.org/openstack/requirements
requirements_git_install_branch: a0c31f4c7a6964baf8e4994b5daea70a5e76a571 # HEAD as of 03.11.2019
requirements_git_track_branch: stable/rocky


## Aodh service
aodh_git_repo: https://opendev.org/openstack/aodh
aodh_git_install_branch: 887a4953ac82667ee77efca98527fa6b3c151ed5  # HEAD as of 03.11.2019
aodh_git_project_group: aodh_all
aodh_git_track_branch: stable/rocky

## Barbican service
barbican_git_repo: https://opendev.org/openstack/barbican
barbican_git_install_branch: 27cf2f37f6003879f7427e206270b983fe28cdb0  # HEAD as of 03.11.2019
barbican_git_project_group: barbican_all
barbican_git_track_branch: stable/rocky


## Ceilometer service
ceilometer_git_repo: https://opendev.org/openstack/ceilometer
ceilometer_git_install_branch: 395747b739e7fbe793454c70f45dd325c5ab190b  # HEAD as of 03.11.2019
ceilometer_git_project_group: all
ceilometer_git_track_branch: stable/rocky


## Cinder service
cinder_git_repo: https://opendev.org/openstack/cinder
cinder_git_install_branch: e8b3232d2fcba240974c573bf33a021e60d6f6ac  # HEAD as of 03.11.2019
cinder_git_project_group: cinder_all
cinder_git_track_branch: stable/rocky


## Designate service
designate_git_repo: https://opendev.org/openstack/designate
designate_git_install_branch: 1e20d09272b4dbb082e72a663e931a61c81c6b37  # HEAD as of 03.11.2019
designate_git_project_group: designate_all
designate_git_track_branch: stable/rocky


## Horizon Designate dashboard plugin
designate_dashboard_git_repo: https://opendev.org/openstack/designate-dashboard
designate_dashboard_git_install_branch: d6dfda1b5b35d6425f825f0e5f55904225e8d48e  # HEAD as of 03.11.2019
designate_dashboard_git_project_group: horizon_all
designate_dashboard_git_track_branch: stable/rocky


## Dragonflow service
# please update the branch (sha and update the comment) when stable/rocky is branched on this repo.
dragonflow_git_repo: https://opendev.org/openstack/dragonflow
dragonflow_git_install_branch: 945b1e368c651ffa3655f42df724d9f13a7b6b96 # FROZEN HEAD of "master" as of 17.08.2018
dragonflow_git_project_group: neutron_all
dragonflow_git_track_branch: None


## Glance service
glance_git_repo: https://opendev.org/openstack/glance
glance_git_install_branch: ad39c12c64c8ff017918a8790d69d5278ac379da  # HEAD as of 03.11.2019
glance_git_project_group: glance_all
glance_git_track_branch: stable/rocky


## Heat service
heat_git_repo: https://opendev.org/openstack/heat
heat_git_install_branch: 8ce74284c82d5229d66e9b06eb95b64dc9dd86e5  # HEAD as of 03.11.2019
heat_git_package_name: openstack-heat
heat_git_project_group: heat_all
heat_git_track_branch: stable/rocky

## Horizon Heat dashboard plugin
# please update the branch (sha and update the comment) when stable/rocky is branched on this repo.
heat_dashboard_git_repo: https://opendev.org/openstack/heat-dashboard
heat_dashboard_git_install_branch: bc7f5068bbb6f7974eaffa2d865a859ff0fd0069 # FROZEN HEAD of "master" as of 17.08.2018
heat_dashboard_git_project_group: horizon_all
heat_dashboard_git_track_branch: None

## Horizon service
horizon_git_repo: https://opendev.org/openstack/horizon
horizon_git_install_branch: 8af8bc48a58fc9a2e45a89a24069f7cae0af8235  # HEAD as of 03.11.2019
horizon_git_project_group: horizon_all
horizon_git_track_branch: stable/rocky

## Horizon Ironic dashboard plugin
ironic_dashboard_git_repo: https://opendev.org/openstack/ironic-ui
ironic_dashboard_git_install_branch: efc85175da292fd2744d9ef1fe0052cb4abf5df6  # HEAD as of 03.11.2019
ironic_dashboard_git_project_group: horizon_all
ironic_dashboard_git_track_branch: stable/rocky

## Horizon Magnum dashboard plugin
magnum_dashboard_git_repo: https://opendev.org/openstack/magnum-ui
magnum_dashboard_git_install_branch: ed5b700bd2d85b96d36554224e1e1209240cc818  # HEAD as of 03.11.2019
magnum_dashboard_git_project_group: horizon_all
magnum_dashboard_git_track_branch: stable/rocky

## Horizon LBaaS dashboard plugin
neutron_lbaas_dashboard_git_repo: https://opendev.org/openstack/neutron-lbaas-dashboard
neutron_lbaas_dashboard_git_install_branch: 66c98f7ad1a60d8afe1b0dcccd39b7db88ce2ca8  # HEAD as of 03.11.2019
neutron_lbaas_dashboard_git_project_group: horizon_all
neutron_lbaas_dashboard_git_track_branch: stable/rocky

## Horizon FWaaS dashboard plugin
neutron_fwaas_dashboard_git_repo: https://opendev.org/openstack/neutron-fwaas-dashboard
neutron_fwaas_dashboard_git_install_branch: 84434ea7ac09a2499a99d8b3f8f68d7666271512  # HEAD as of 03.11.2019
neutron_fwaas_dashboard_git_project_group: horizon_all
neutron_fwaas_dashboard_git_track_branch: stable/rocky

## Horizon Sahara dashboard plugin
sahara_dashboard_git_repo: https://opendev.org/openstack/sahara-dashboard
sahara_dashboard_git_install_branch: 51a46eab08704053c9feea430831313740c847ae # HEAD as of 03.11.2019
sahara_dashboard_git_project_group: horizon_all
sahara_dashboard_git_track_branch: stable/rocky


## Keystone service
keystone_git_repo: https://opendev.org/openstack/keystone
keystone_git_install_branch: 50b10f40663418c0c3c1dbfd4d13b30ed3e17c0e  # HEAD as of 03.11.2019
keystone_git_project_group: keystone_all
keystone_git_track_branch: stable/rocky


## Neutron service
neutron_git_repo: https://opendev.org/openstack/neutron
neutron_git_install_branch: 32ecad13892a2081058cf9effba623221e9fcbdf  # HEAD as of 03.11.2019
neutron_git_project_group: neutron_all
neutron_git_track_branch: stable/rocky

neutron_lbaas_git_repo: https://opendev.org/openstack/neutron-lbaas
neutron_lbaas_git_install_branch: e22276df0560f38d6527a56808764924d66b3f5d  # HEAD as of 03.11.2019
neutron_lbaas_git_project_group: neutron_all
neutron_lbaas_git_track_branch: stable/rocky

neutron_vpnaas_git_repo: https://opendev.org/openstack/neutron-vpnaas
neutron_vpnaas_git_install_branch: af71c17d5153f7cbaba4c4e1e48538728a7d481a  # HEAD as of 03.11.2019
neutron_vpnaas_git_project_group: neutron_all
neutron_vpnaas_git_track_branch: stable/rocky

neutron_fwaas_git_repo: https://opendev.org/openstack/neutron-fwaas
neutron_fwaas_git_install_branch: fc59b08ff78456c98fee0cc187f8888bc99c333e  # HEAD as of 03.11.2019
neutron_fwaas_git_project_group: neutron_all
neutron_fwaas_git_track_branch: stable/rocky

neutron_dynamic_routing_git_repo: https://opendev.org/openstack/neutron-dynamic-routing
neutron_dynamic_routing_git_install_branch: bad20ef36b35dce0b1a0e79ae0d9f6b63f17389f  # HEAD as of 03.11.2019
neutron_dynamic_routing_git_project_group: neutron_all
neutron_dynamic_routing_git_track_branch: stable/rocky

# Networking Calico is following master
networking_calico_git_repo: https://opendev.org/openstack/networking-calico
networking_calico_git_install_branch: fbd0c827ca5b814438c2096877195b290640d6c1  # HEAD as of 03.11.2019
networking_calico_git_project_group: neutron_all
networking_calico_git_track_branch: master

networking_odl_git_repo: https://opendev.org/openstack/networking-odl
networking_odl_git_install_branch: 9ef63ea47bf64150878920444fb059349af5fef0  # HEAD as of 03.11.2019
networking_odl_git_project_group: neutron_all
networking_odl_git_track_branch: stable/rocky

networking_ovn_git_repo: https://opendev.org/openstack/networking-ovn
networking_ovn_git_install_branch: ad239b2d7b72d0dbc854e835b85e0d0790668b64  # HEAD as of 03.11.2019
networking_ovn_git_project_group: neutron_all
networking_ovn_git_track_branch: stable/rocky

# BGPVPN is frozen until further notice due to
# https://github.com/openstack/networking-bgpvpn/commit/e9a0ea199b47f76f69545e04bdb4db44869c388b#diff-b4ef698db8ca845e5845c4618278f29a
networking_bgpvpn_git_repo: https://opendev.org/openstack/networking-bgpvpn
networking_bgpvpn_git_install_branch: 3b93ddacd390d92fb144e5660324d4da064ad9a4 # FROZEN HEAD of "stable/rocky" as of 31.03.2018
networking_bgpvpn_git_project_group: neutron_all
networking_bgpvpn_git_track_branch: None

networking_sfc_git_repo: https://opendev.org/openstack/networking-sfc
networking_sfc_git_install_branch: af98891e7d7c1acaf97c25d155fbe3085f6bdc78  # HEAD as of 03.11.2019
networking_sfc_git_project_group: neutron_all
networking_sfc_git_track_branch: stable/rocky


## Nova service
nova_git_repo: https://opendev.org/openstack/nova
nova_git_install_branch: a07c612ea6fb8553effecef7454caa179589e916  # HEAD as of 03.11.2019
nova_git_project_group: nova_all
nova_git_track_branch: stable/rocky


## PowerVM Virt Driver
nova_powervm_git_repo: https://opendev.org/openstack/nova-powervm
nova_powervm_git_install_branch: 8660f3da7fa8ae8f6c827ac1d17ae84f121a5e92  # HEAD as of 03.11.2019
nova_powervm_git_project_group: nova_all
nova_powervm_git_track_branch: stable/rocky


## LXD Virt Driver
# please update the branch (sha and update the comment) when stable/rocky is branched on this repo.
nova_lxd_git_repo: https://opendev.org/openstack/nova-lxd
nova_lxd_git_install_branch: bc8d540c95b3209321658000fd74b0e5065a7ee2 # FROZEN HEAD of "master" as of 17.08.2018
nova_lxd_git_project_group: nova_all
nova_lxd_git_track_branch: None


## Sahara service
sahara_git_repo: https://opendev.org/openstack/sahara
sahara_git_install_branch: bd98d6e8667bb10d7a5e87db4418702cecb8e48a # HEAD as of 03.11.2019
sahara_git_project_group: sahara_all
sahara_git_track_branch: stable/rocky


## Swift service
swift_git_repo: https://opendev.org/openstack/swift
swift_git_install_branch: da83e066aaeca60441b48ad01e7a52f66a364cbc # HEAD as of 03.11.2019
swift_git_project_group: swift_all
swift_git_track_branch: stable/rocky


## Swift3 middleware
# please remove this when swift role is configured without this middleware (and uses swift code only)
swift_swift3_git_repo: https://opendev.org/openstack/swift3
swift_swift3_git_install_branch: 90db5d1510b2a770387961e7bf0fbeae8101ba45 # FROZEN HEAD of "master" as of 17.08.2018
swift_swift3_git_project_group: swift_all
swift_swift3_git_track_branch: None


## Ironic service
ironic_git_repo: https://opendev.org/openstack/ironic
ironic_git_install_branch: 02b852d59cfd97f1ccc80d0b5b5562eaa22e4b36  # HEAD as of 03.11.2019
ironic_git_project_group: ironic_all
ironic_git_track_branch: stable/rocky


## Magnum service
magnum_git_repo: https://opendev.org/openstack/magnum
magnum_git_install_branch: 5554abb0a7e378d8232e817558a95924074f16bd  # HEAD as of 03.11.2019
magnum_git_project_group: magnum_all
magnum_git_track_branch: stable/rocky

## Mistral service
mistral_git_repo: https://opendev.org/openstack/mistral
mistral_git_install_branch: d1b8dd1635aa45d3d644b356f883484997f31ca7  # HEAD as of 03.11.2019
mistral_git_project_group: mistral_all
mistral_git_track_branch: stable/rocky

## Trove service
trove_git_repo: https://opendev.org/openstack/trove
trove_git_install_branch: 239f9c6e4fa7d7bb9bab396f79336725a149126c # HEAD as of 03.11.2019
trove_git_project_group: trove_all
trove_git_track_branch: stable/rocky

## Horizon Trove dashboard plugin
trove_dashboard_git_repo: https://opendev.org/openstack/trove-dashboard
trove_dashboard_git_install_branch: a52236eebe22b8571d85e50cfcb0f01f415b0091 # HEAD as of 03.11.2019
trove_dashboard_git_project_group: horizon_all
trove_dashboard_git_track_branch: stable/rocky


## Octavia service
octavia_git_repo: https://opendev.org/openstack/octavia
octavia_git_install_branch: 43d3e1bde3e1257b7e3622eb222d4ab6a47114cf  # HEAD as of 03.11.2019
octavia_git_project_group: octavia_all
octavia_git_track_branch: stable/rocky


## Tacker service
tacker_git_repo: https://opendev.org/openstack/tacker
tacker_git_install_branch: 24f6db6f5c90f0b6ef909e52b47f6d20eb5a7ec8 # HEAD as of 03.11.2019
tacker_git_project_group: tacker_all
tacker_git_track_branch: stable/rocky

## Congress service
congress_git_repo: https://opendev.org/openstack/congress
congress_git_install_branch: 3ee83ca4899361d650216cda25032063fc2300e4  # HEAD as of 03.11.2019
congress_git_project_group: congress_all
congress_git_track_branch: stable/rocky

## Horizon Octavia dashboard plugin
octavia_dashboard_git_repo: https://opendev.org/openstack/octavia-dashboard
octavia_dashboard_git_install_branch: 0e14846f712fedfdc8b56686bde2114d26b241fe  # HEAD as of 03.11.2019
octavia_dashboard_git_project_group: horizon_all
octavia_dashboard_git_track_branch: stable/rocky
