---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


## NOTICE on items in this file:
##   * If you use anything in the *._git_install_branch field that is not a TAG
##     make sure to leave an in-line comment as to "why".

## For the sake of anyone else editing this file:
##   * If you add services to this file please do so in alphabetical order.
##   * Every entry should be name spaced with the name of the client followed by an "_"
##   * All items with this file should be separated by `name_` note that the name of the
##     package should be one long name with no additional `_` separating it.


### Before this is shipped all of these services should have a tag set as the branch,
### or have a comment / reason attached to them as to why a tag can not work.


## Global Requirements
requirements_git_repo: https://opendev.org/openstack/requirements
requirements_git_install_branch: d2c8b9d472320a8e916f38df4580a7f7bbab2bda # HEAD as of 06.09.2020
requirements_git_track_branch: master


## Aodh service
aodh_git_repo: https://opendev.org/openstack/aodh
aodh_git_install_branch: 8635b67777e3aa0c90eccdbcb5753e33a1750aeb  # HEAD as of 06.09.2020
aodh_git_project_group: aodh_all
aodh_git_track_branch: master


## Barbican service
barbican_git_repo: https://opendev.org/openstack/barbican
barbican_git_install_branch: 06e67d0b25ddb6379b028f50b7ab728d4f27d9c7  # HEAD as of 06.09.2020
barbican_git_project_group: barbican_all
barbican_git_track_branch: master


## Ceilometer service
ceilometer_git_repo: https://opendev.org/openstack/ceilometer
ceilometer_git_install_branch: 91bc55b12d7ebaa4c903503dc85f11a8bf79102a  # HEAD as of 06.09.2020
ceilometer_git_project_group: all
ceilometer_git_track_branch: master


## Cinder service
cinder_git_repo: https://opendev.org/openstack/cinder
cinder_git_install_branch: 06bc733ffae14782b8fcbc509c07ee6822b74122  # HEAD as of 06.09.2020
cinder_git_project_group: cinder_all
cinder_git_track_branch: master


## Designate service
designate_git_repo: https://opendev.org/openstack/designate
designate_git_install_branch: 06f147f76ddf5fa198fb7851ef14144bfb0fb9ee  # HEAD as of 06.09.2020
designate_git_project_group: designate_all
designate_git_track_branch: master


## Horizon Designate dashboard plugin
designate_dashboard_git_repo: https://opendev.org/openstack/designate-dashboard
designate_dashboard_git_install_branch: 00c1142e944ea8d09ac8271b5ac6a052c4792bff  # HEAD as of 06.09.2020
designate_dashboard_git_project_group: horizon_all
designate_dashboard_git_track_branch: master


## Glance service
glance_git_repo: https://opendev.org/openstack/glance
glance_git_install_branch: 5126ca0242ad0469bcd59c977f14d7d2ccd457e0  # HEAD as of 06.09.2020
glance_git_project_group: glance_all
glance_git_track_branch: master


## Heat service
heat_git_repo: https://opendev.org/openstack/heat
heat_git_install_branch: c54518d6072d8b5b65c6a2ce6c50903efb31e3ee  # HEAD as of 06.09.2020
heat_git_package_name: openstack-heat
heat_git_project_group: heat_all
heat_git_track_branch: master

## Horizon Heat dashboard plugin
heat_dashboard_git_repo: https://opendev.org/openstack/heat-dashboard
heat_dashboard_git_install_branch: 7d4ef2057fff075771e5ba24f7bff25e411b9102  # HEAD as of 06.09.2020
heat_dashboard_git_project_group: horizon_all
heat_dashboard_git_track_branch: master

## Horizon service
horizon_git_repo: https://opendev.org/openstack/horizon
horizon_git_install_branch: 49df5cffd84b6d9da4e5926afd12e0a92737d740  # HEAD as of 06.09.2020
horizon_git_project_group: horizon_all
horizon_git_track_branch: master

## Horizon Ironic dashboard plugin
ironic_dashboard_git_repo: https://opendev.org/openstack/ironic-ui
ironic_dashboard_git_install_branch: 927b4c291e4dbd40eaa45a87318d8165e01de0ee  # HEAD as of 06.09.2020
ironic_dashboard_git_project_group: horizon_all
ironic_dashboard_git_track_branch: master

## Horizon Magnum dashboard plugin
magnum_dashboard_git_repo: https://opendev.org/openstack/magnum-ui
magnum_dashboard_git_install_branch: d144650bd91f0a078b2483343e1e6d3edb1e8544  # HEAD as of 06.09.2020
magnum_dashboard_git_project_group: horizon_all
magnum_dashboard_git_track_branch: master

## Horizon Masakari dashboard plugin
masakari_dashboard_git_repo: https://opendev.org/openstack/masakari-dashboard
masakari_dashboard_git_install_branch: f832d82016c9c0afc84fc2595b82fff30ea725d3  # HEAD as of 06.09.2020
masakari_dashboard_git_project_group: horizon_all
masakari_dashboard_git_track_branch: master

## Horizon FWaaS dashboard plugin
neutron_fwaas_dashboard_git_repo: https://opendev.org/openstack/neutron-fwaas-dashboard
neutron_fwaas_dashboard_git_install_branch: 4a0f1a3ae54a69f37ab38a0209e3a9996f727693  # HEAD as of 06.09.2020
neutron_fwaas_dashboard_git_project_group: horizon_all
neutron_fwaas_dashboard_git_track_branch: master

## Horizon Sahara dashboard plugin
sahara_dashboard_git_repo: https://opendev.org/openstack/sahara-dashboard
sahara_dashboard_git_install_branch: 3fc494d1730b90a3e49855c2498958c92a2c1ee5 # HEAD as of 06.09.2020
sahara_dashboard_git_project_group: horizon_all
sahara_dashboard_git_track_branch: master


## Keystone service
keystone_git_repo: https://opendev.org/openstack/keystone
keystone_git_install_branch: 0b9d98b37b88d1be3a5e419ecc8395eb459f5a93  # HEAD as of 06.09.2020
keystone_git_project_group: keystone_all
keystone_git_track_branch: master


## Manila service
manila_git_repo: https://opendev.org/openstack/manila
manila_git_install_branch: 2fb8a153690321f30def22ea47f0f295d4f639d7  # HEAD as of 06.09.2020
manila_git_project_group: manila_all
manila_git_track_branch: master


## Neutron service
neutron_git_repo: https://opendev.org/openstack/neutron
neutron_git_install_branch: d3c939e88a0b285121e70599869089072fe5288b  # HEAD as of 06.09.2020
neutron_git_project_group: neutron_all
neutron_git_track_branch: master

neutron_vpnaas_git_repo: https://opendev.org/openstack/neutron-vpnaas
neutron_vpnaas_git_install_branch: 2b293a1bfae6cefe17efa820e41ef698663749f2  # HEAD as of 06.09.2020
neutron_vpnaas_git_project_group: neutron_all
neutron_vpnaas_git_track_branch: master

neutron_fwaas_git_repo: https://opendev.org/openstack/neutron-fwaas
neutron_fwaas_git_install_branch: caae7b6a6f5e8944dbe359b6472be2507bbf5e12  # HEAD as of 06.09.2020
neutron_fwaas_git_project_group: neutron_all
neutron_fwaas_git_track_branch: master

neutron_dynamic_routing_git_repo: https://opendev.org/openstack/neutron-dynamic-routing
neutron_dynamic_routing_git_install_branch: 818fe4935cf4d43ca0372fcbe05d4687b0ed9ac3  # HEAD as of 06.09.2020
neutron_dynamic_routing_git_project_group: neutron_all
neutron_dynamic_routing_git_track_branch: master

# Networking calico follows master
networking_calico_git_repo: https://github.com/projectcalico/networking-calico
networking_calico_git_install_branch: v3.14.0  # HEAD as of 19.05.2020
networking_calico_git_project_group: neutron_all
networking_calico_git_track_branch: None

networking_odl_git_repo: https://opendev.org/openstack/networking-odl
networking_odl_git_install_branch: 7d07b01cfa2ef9d2b888306586e22c7eb3fedbff  # HEAD as of 06.09.2020
networking_odl_git_project_group: neutron_all
networking_odl_git_track_branch: master

networking_bgpvpn_git_repo: https://opendev.org/openstack/networking-bgpvpn
networking_bgpvpn_git_install_branch: 1751d309b38f342956f4a3ae2af4941be95c0b71  # HEAD as of 06.09.2020
networking_bgpvpn_git_project_group: neutron_all
networking_bgpvpn_git_track_branch: master

networking_sfc_git_repo: https://opendev.org/openstack/networking-sfc
networking_sfc_git_install_branch: 79f95d9c3c6ab4feb9eccc739f58cb5ff2621fe2  # HEAD as of 06.09.2020
networking_sfc_git_project_group: neutron_all
networking_sfc_git_track_branch: master


## Nova service
nova_git_repo: https://opendev.org/openstack/nova
nova_git_install_branch: 85b35078cfad9aad7cc5d5df3aeb034e5452be59  # HEAD as of 06.09.2020
nova_git_project_group: nova_all
nova_git_track_branch: master


## Sahara service
sahara_git_repo: https://opendev.org/openstack/sahara
sahara_git_install_branch: 7cdda56b2cf9f64e78f01bd9156bf0c96c76e243 # HEAD as of 06.09.2020
sahara_git_project_group: sahara_all
sahara_git_track_branch: master


## Swift service
swift_git_repo: https://opendev.org/openstack/swift
swift_git_install_branch: cca5e8b1de162dfd65d73bf1971333af14a0dd17 # HEAD as of 06.09.2020
swift_git_project_group: swift_all
swift_git_track_branch: master


## Ironic service
ironic_git_repo: https://opendev.org/openstack/ironic
ironic_git_install_branch: 3709cce11f696f324f501090d050273a1fcb4a70  # HEAD as of 06.09.2020
ironic_git_project_group: ironic_all
ironic_git_track_branch: master


## Ironic inspector service
ironic_inspector_git_repo: https://opendev.org/openstack/ironic-inspector
ironic_inspector_git_install_branch: 2bc8f00707a9fac89c77f9bda593698a6566b165  # HEAD as of 06.09.2020
ironic_inspector_git_project_group: ironic_inspector
ironic_inspector_git_track_branch: master


## Magnum service
magnum_git_repo: https://opendev.org/openstack/magnum
magnum_git_install_branch: cbf0a3924c955d45400f1b5ce8550112e0345139  # HEAD as of 06.09.2020
magnum_git_project_group: magnum_all
magnum_git_track_branch: master

## Masakari service
masakari_git_repo: https://opendev.org/openstack/masakari
masakari_git_install_branch: 112610abce26e90abb393b1374d4ebc295275a7d  # HEAD as of 06.09.2020
masakari_git_project_group: masakari_api
masakari_git_track_branch: master

## Masakari monitors services
masakari_monitors_git_repo: https://opendev.org/openstack/masakari-monitors
masakari_monitors_git_install_branch: a830855ee65dbe1d5e0104d57e6b668e52f808ec  # HEAD as of 06.09.2020
masakari_monitors_git_project_group: masakari_monitor
masakari_monitors_git_track_branch: master

## Mistral service
mistral_git_repo: https://opendev.org/openstack/mistral
mistral_git_install_branch: 63225d41e41dbedc341f2ef0724901f62dcd5d8b  # HEAD as of 06.09.2020
mistral_git_project_group: mistral_all
mistral_git_track_branch: master

## Murano service
murano_git_repo: https://opendev.org/openstack/murano
murano_git_install_branch: 7c153733b92840662a358c888c6121fa1a9fe362  # HEAD as of 06.09.2020
murano_git_project_group: murano_all
murano_git_track_branch: master

## Trove service
trove_git_repo: https://opendev.org/openstack/trove
trove_git_install_branch: 768ec34dfef660f133f87218a6246a9ce111bcb5 # HEAD as of 06.09.2020
trove_git_project_group: trove_all
trove_git_track_branch: master

## Horizon Trove dashboard plugin
trove_dashboard_git_repo: https://opendev.org/openstack/trove-dashboard
trove_dashboard_git_install_branch: b1a2f6c77bcfa137e4e4a106101c68978c625e54 # HEAD as of 06.09.2020
trove_dashboard_git_project_group: horizon_all
trove_dashboard_git_track_branch: master


## Octavia service
octavia_git_repo: https://opendev.org/openstack/octavia
octavia_git_install_branch: 46de66b240697b1e6465c06a203fe6dac75b7da1  # HEAD as of 06.09.2020
octavia_git_project_group: octavia_all
octavia_git_track_branch: master


## Panko service
panko_git_repo: https://opendev.org/openstack/panko
panko_git_install_branch: 046c9460c60808ebbbee1ac988160e09ce88a27d  # HEAD as of 06.09.2020
panko_git_project_group: panko_all
panko_git_track_branch: master


## Placement service
placement_git_repo: https://opendev.org/openstack/placement
placement_git_install_branch: f89f1107613a0b49804e46b42dcb34e0294088f1  # HEAD as of 06.09.2020
placement_git_project_group: placement_all
placement_git_track_branch: master


## Tacker service
tacker_git_repo: https://opendev.org/openstack/tacker
tacker_git_install_branch: bc7e11f9570b6df4d8ef8ef2195ae2a25908fc43 # HEAD as of 06.09.2020
tacker_git_project_group: tacker_all
tacker_git_track_branch: master


## Congress service
congress_git_repo: https://opendev.org/openstack/congress
congress_git_install_branch: bba805af02f516b95650531afc02d1c60b1cd010  # HEAD as of 06.09.2020
congress_git_package_name: openstack-congress
congress_git_project_group: congress_all
congress_git_track_branch: master

## Horizon Octavia dashboard plugin
octavia_dashboard_git_repo: https://opendev.org/openstack/octavia-dashboard
octavia_dashboard_git_install_branch: d70f7b176af406aafbd6a5579eba4ee7b89bd22b  # HEAD as of 06.09.2020
octavia_dashboard_git_project_group: horizon_all
octavia_dashboard_git_track_branch: master


## Blazar service
blazar_git_repo: https://opendev.org/openstack/blazar
blazar_git_install_branch: a2f792629c2a6ef70ec6fa6efaa05b2357bff96a  # HEAD as of 06.09.2020
blazar_git_project_group: blazar_all
blazar_git_track_branch: master

## Blazar Nova Service
blazar_nova_git_repo: https://opendev.org/openstack/blazar-nova
blazar_nova_git_install_branch: 349e75a811c6fcc54eed128fed783f0bf2aeff78  # HEAD as of 06.09.2020
blazar_nova_git_project_group: blazar_all
blazar_nova_git_track_branch: master

## Zun service
zun_git_repo: https://opendev.org/openstack/zun
zun_git_install_branch: 1f7419b2ba49ecdf964f2ec524ec839543d412ea # HEAD as of 06.09.2020
zun_git_project_group: zun_all
zun_git_track_branch: master

## Zun kyrir service
zun_kuryr_git_repo: https://opendev.org/openstack/kuryr-libnetwork
zun_kuryr_git_install_branch: b096b19a5fcb2633160bbd9f03a3b69acf379057 # HEAD as of 06.09.2020
zun_kuryr_git_project_group: zun_all
zun_kuryr_git_track_branch: master
