---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


## NOTICE on items in this file:
##   * If you use anything in the *._git_install_branch field that is not a TAG
##     make sure to leave an in-line comment as to "why".

## For the sake of anyone else editing this file:
##   * If you add services to this file please do so in alphabetical order.
##   * Every entry should be name spaced with the name of the client followed by an "_"
##   * All items with this file should be separated by `name_` note that the name of the
##     package should be one long name with no additional `_` separating it.


### Before this is shipped all of these services should have a tag set as the branch,
### or have a comment / reason attached to them as to why a tag can not work.


## Global Requirements
requirements_git_repo: https://opendev.org/openstack/requirements
requirements_git_install_branch: 04152885d25001131e4bcf488da8c033468114c4 # HEAD as of 09.08.2020
requirements_git_track_branch: master


## Aodh service
aodh_git_repo: https://opendev.org/openstack/aodh
aodh_git_install_branch: 932b1e0e6102fada52c9a1a4f7f87d5925d71bca  # HEAD as of 09.08.2020
aodh_git_project_group: aodh_all
aodh_git_track_branch: master


## Barbican service
barbican_git_repo: https://opendev.org/openstack/barbican
barbican_git_install_branch: 36b2f65833c870801f900abe0a6cf679c1d3ac71  # HEAD as of 09.08.2020
barbican_git_project_group: barbican_all
barbican_git_track_branch: master


## Ceilometer service
ceilometer_git_repo: https://opendev.org/openstack/ceilometer
ceilometer_git_install_branch: 5af99caad73cf0af3966ea86a0664212a9982423  # HEAD as of 09.08.2020
ceilometer_git_project_group: all
ceilometer_git_track_branch: master


## Cinder service
cinder_git_repo: https://opendev.org/openstack/cinder
cinder_git_install_branch: 0ba9b86e6210c8a2b43bdf88e702476f0f04ab15  # HEAD as of 09.08.2020
cinder_git_project_group: cinder_all
cinder_git_track_branch: master


## Designate service
designate_git_repo: https://opendev.org/openstack/designate
designate_git_install_branch: 45cb4376a24d244fa677f3736299b4effa092657  # HEAD as of 09.08.2020
designate_git_project_group: designate_all
designate_git_track_branch: master


## Horizon Designate dashboard plugin
designate_dashboard_git_repo: https://opendev.org/openstack/designate-dashboard
designate_dashboard_git_install_branch: 00c1142e944ea8d09ac8271b5ac6a052c4792bff  # HEAD as of 09.08.2020
designate_dashboard_git_project_group: horizon_all
designate_dashboard_git_track_branch: master


## Glance service
glance_git_repo: https://opendev.org/openstack/glance
glance_git_install_branch: ed3296b23a452391bbe11116e060d4b49235523e  # HEAD as of 09.08.2020
glance_git_project_group: glance_all
glance_git_track_branch: master


## Heat service
heat_git_repo: https://opendev.org/openstack/heat
heat_git_install_branch: 65de8cb43694bb2063248dff920cc1f0e06c851f  # HEAD as of 09.08.2020
heat_git_package_name: openstack-heat
heat_git_project_group: heat_all
heat_git_track_branch: master

## Horizon Heat dashboard plugin
heat_dashboard_git_repo: https://opendev.org/openstack/heat-dashboard
heat_dashboard_git_install_branch: f8c9720499600baad488b956210e4bbe3b5da5bc  # HEAD as of 09.08.2020
heat_dashboard_git_project_group: horizon_all
heat_dashboard_git_track_branch: master

## Horizon service
horizon_git_repo: https://opendev.org/openstack/horizon
horizon_git_install_branch: a2a173d2c5fa9173793ae3deed194dde7c9a802f  # HEAD as of 09.08.2020
horizon_git_project_group: horizon_all
horizon_git_track_branch: master

## Horizon Ironic dashboard plugin
ironic_dashboard_git_repo: https://opendev.org/openstack/ironic-ui
ironic_dashboard_git_install_branch: 50134dc769a666b29ba55e377d7b1bfc4af94489  # HEAD as of 09.08.2020
ironic_dashboard_git_project_group: horizon_all
ironic_dashboard_git_track_branch: master

## Horizon Magnum dashboard plugin
magnum_dashboard_git_repo: https://opendev.org/openstack/magnum-ui
magnum_dashboard_git_install_branch: 6fa4868a7739087dabc8d773ffdee5e6f9503179  # HEAD as of 09.08.2020
magnum_dashboard_git_project_group: horizon_all
magnum_dashboard_git_track_branch: master

## Horizon Masakari dashboard plugin
masakari_dashboard_git_repo: https://opendev.org/openstack/masakari-dashboard
masakari_dashboard_git_install_branch: 567e3aed9b9eb8dcc347ce2a81822fe638cf735c  # HEAD as of 09.08.2020
masakari_dashboard_git_project_group: horizon_all
masakari_dashboard_git_track_branch: master

## Horizon FWaaS dashboard plugin
neutron_fwaas_dashboard_git_repo: https://opendev.org/openstack/neutron-fwaas-dashboard
neutron_fwaas_dashboard_git_install_branch: 4a0f1a3ae54a69f37ab38a0209e3a9996f727693  # HEAD as of 09.08.2020
neutron_fwaas_dashboard_git_project_group: horizon_all
neutron_fwaas_dashboard_git_track_branch: master

## Horizon Sahara dashboard plugin
sahara_dashboard_git_repo: https://opendev.org/openstack/sahara-dashboard
sahara_dashboard_git_install_branch: 0a891cf2328c014af8c6f2773af7cb0b7a167385 # HEAD as of 09.08.2020
sahara_dashboard_git_project_group: horizon_all
sahara_dashboard_git_track_branch: master


## Keystone service
keystone_git_repo: https://opendev.org/openstack/keystone
keystone_git_install_branch: 952959fb872b25d4ad525056012e1667efb4eb60  # HEAD as of 09.08.2020
keystone_git_project_group: keystone_all
keystone_git_track_branch: master


## Manila service
manila_git_repo: https://opendev.org/openstack/manila
manila_git_install_branch: f78e2fdee7d1ed05276dc2ebbc8cca7e88e15445  # HEAD as of 09.08.2020
manila_git_project_group: manila_all
manila_git_track_branch: master


## Neutron service
neutron_git_repo: https://opendev.org/openstack/neutron
neutron_git_install_branch: b425ca45dddae1bfc44ff1fda9e29d8d71fadb4b  # HEAD as of 09.08.2020
neutron_git_project_group: neutron_all
neutron_git_track_branch: master

neutron_vpnaas_git_repo: https://opendev.org/openstack/neutron-vpnaas
neutron_vpnaas_git_install_branch: 775adee6278ee887b79f30cc5f656815ab8989a7  # HEAD as of 09.08.2020
neutron_vpnaas_git_project_group: neutron_all
neutron_vpnaas_git_track_branch: master

neutron_fwaas_git_repo: https://opendev.org/openstack/neutron-fwaas
neutron_fwaas_git_install_branch: caae7b6a6f5e8944dbe359b6472be2507bbf5e12  # HEAD as of 09.08.2020
neutron_fwaas_git_project_group: neutron_all
neutron_fwaas_git_track_branch: master

neutron_dynamic_routing_git_repo: https://opendev.org/openstack/neutron-dynamic-routing
neutron_dynamic_routing_git_install_branch: e6274b2d162f9c7c95c5f8686b0e6c27d8dccba0  # HEAD as of 09.08.2020
neutron_dynamic_routing_git_project_group: neutron_all
neutron_dynamic_routing_git_track_branch: master

# Networking calico follows master
networking_calico_git_repo: https://github.com/projectcalico/networking-calico
networking_calico_git_install_branch: v3.14.0  # HEAD as of 19.05.2020
networking_calico_git_project_group: neutron_all
networking_calico_git_track_branch: None

networking_odl_git_repo: https://opendev.org/openstack/networking-odl
networking_odl_git_install_branch: 52a6f383f437400f9cee1c587850af961f761e69  # HEAD as of 09.08.2020
networking_odl_git_project_group: neutron_all
networking_odl_git_track_branch: master

networking_bgpvpn_git_repo: https://opendev.org/openstack/networking-bgpvpn
networking_bgpvpn_git_install_branch: 8c6564ffc4d2e00563ae22cfee6ebb4314304d9b  # HEAD as of 09.08.2020
networking_bgpvpn_git_project_group: neutron_all
networking_bgpvpn_git_track_branch: master

networking_sfc_git_repo: https://opendev.org/openstack/networking-sfc
networking_sfc_git_install_branch: 211e515630d2695c3a48a7ba6212a22f312bb3bc  # HEAD as of 09.08.2020
networking_sfc_git_project_group: neutron_all
networking_sfc_git_track_branch: master


## Nova service
nova_git_repo: https://opendev.org/openstack/nova
nova_git_install_branch: 64980bd78cba04e011ea78ed229b60e95204d60f  # HEAD as of 09.08.2020
nova_git_project_group: nova_all
nova_git_track_branch: master


## Sahara service
sahara_git_repo: https://opendev.org/openstack/sahara
sahara_git_install_branch: 7cdda56b2cf9f64e78f01bd9156bf0c96c76e243 # HEAD as of 09.08.2020
sahara_git_project_group: sahara_all
sahara_git_track_branch: master


## Swift service
swift_git_repo: https://opendev.org/openstack/swift
swift_git_install_branch: d50b50ba8d28eab544b7236cb1d786c16e20f080 # HEAD as of 09.08.2020
swift_git_project_group: swift_all
swift_git_track_branch: master


## Ironic service
ironic_git_repo: https://opendev.org/openstack/ironic
ironic_git_install_branch: 06094e16585357f0efde9344f40f14665f755c57  # HEAD as of 09.08.2020
ironic_git_project_group: ironic_all
ironic_git_track_branch: master


## Ironic inspector service
ironic_inspector_git_repo: https://opendev.org/openstack/ironic-inspector
ironic_inspector_git_install_branch: 2c38173fbf0ba2beebebc067704a30618b2eaf0d  # HEAD as of 19.08.2020
ironic_inspector_git_project_group: ironic_inspector
ironic_inspector_git_track_branch: master


## Magnum service
magnum_git_repo: https://opendev.org/openstack/magnum
magnum_git_install_branch: 37c216543c52dff124e844710d75ff2d2750cdaf  # HEAD as of 09.08.2020
magnum_git_project_group: magnum_all
magnum_git_track_branch: master

## Masakari service
masakari_git_repo: https://opendev.org/openstack/masakari
masakari_git_install_branch: 69a9a41802edf21c8e4784835654697e13db9ca2  # HEAD as of 09.08.2020
masakari_git_project_group: masakari_api
masakari_git_track_branch: master

## Masakari monitors services
masakari_monitors_git_repo: https://opendev.org/openstack/masakari-monitors
masakari_monitors_git_install_branch: be1173e853cb4548cdc33d5d5c5ef98c0cbbc28a  # HEAD as of 09.08.2020
masakari_monitors_git_project_group: masakari_monitor
masakari_monitors_git_track_branch: master

## Mistral service
mistral_git_repo: https://opendev.org/openstack/mistral
mistral_git_install_branch: 598d214de8e6d46bb3758ec834c02e2d3ab663ed  # HEAD as of 09.08.2020
mistral_git_project_group: mistral_all
mistral_git_track_branch: master

## Murano service
murano_git_repo: https://opendev.org/openstack/murano
murano_git_install_branch: fc12a87932291130067e6350fb0d0b5bd3a6c6d5  # HEAD as of 09.08.2020
murano_git_project_group: murano_all
murano_git_track_branch: master

## Trove service
trove_git_repo: https://opendev.org/openstack/trove
trove_git_install_branch: 6b1c31e2ed513785d72b5bf73bd928453b7f5a61 # HEAD as of 09.08.2020
trove_git_project_group: trove_all
trove_git_track_branch: master

## Horizon Trove dashboard plugin
trove_dashboard_git_repo: https://opendev.org/openstack/trove-dashboard
trove_dashboard_git_install_branch: fb011dbaa157b47db2ad805e94a2d26e79075aca # HEAD as of 09.08.2020
trove_dashboard_git_project_group: horizon_all
trove_dashboard_git_track_branch: master


## Octavia service
octavia_git_repo: https://opendev.org/openstack/octavia
octavia_git_install_branch: 1d32c9fc262670943aa7725a52cab5cba6ac5077  # HEAD as of 09.08.2020
octavia_git_project_group: octavia_all
octavia_git_track_branch: master


## Panko service
panko_git_repo: https://opendev.org/openstack/panko
panko_git_install_branch: 046c9460c60808ebbbee1ac988160e09ce88a27d  # HEAD as of 09.08.2020
panko_git_project_group: panko_all
panko_git_track_branch: master


## Placement service
placement_git_repo: https://opendev.org/openstack/placement
placement_git_install_branch: 4b95c078cc75987979a96bceafce152d6153adcf  # HEAD as of 09.08.2020
placement_git_project_group: placement_all
placement_git_track_branch: master


## Tacker service
tacker_git_repo: https://opendev.org/openstack/tacker
tacker_git_install_branch: 390b659a65b9afb8ccd1c76725e9db3ea8a60a63 # HEAD as of 09.08.2020
tacker_git_project_group: tacker_all
tacker_git_track_branch: master


## Congress service
congress_git_repo: https://opendev.org/openstack/congress
congress_git_install_branch: bba805af02f516b95650531afc02d1c60b1cd010  # HEAD as of 09.08.2020
congress_git_package_name: openstack-congress
congress_git_project_group: congress_all
congress_git_track_branch: master

## Horizon Octavia dashboard plugin
octavia_dashboard_git_repo: https://opendev.org/openstack/octavia-dashboard
octavia_dashboard_git_install_branch: 8bc9329b5f2b5983adfe0c7e336f3f2555aa2e62  # HEAD as of 09.08.2020
octavia_dashboard_git_project_group: horizon_all
octavia_dashboard_git_track_branch: master


## Blazar service
blazar_git_repo: https://opendev.org/openstack/blazar
blazar_git_install_branch: 532544efbf5fc3a2daf60af5d3c216b0b6a62c42  # HEAD as of 09.08.2020
blazar_git_project_group: blazar_all
blazar_git_track_branch: master

## Blazar Nova Service
blazar_nova_git_repo: https://opendev.org/openstack/blazar-nova
blazar_nova_git_install_branch: 349e75a811c6fcc54eed128fed783f0bf2aeff78  # HEAD as of 09.08.2020
blazar_nova_git_project_group: blazar_all
blazar_nova_git_track_branch: master

## Zun service
zun_git_repo: https://opendev.org/openstack/zun
zun_git_install_branch: 05d55ec9bdafb7ab06923c428906b0051a79c383 # HEAD as of 09.08.2020
zun_git_project_group: zun_all
zun_git_track_branch: master

## Zun kyrir service
zun_kuryr_git_repo: https://opendev.org/openstack/kuryr-libnetwork
zun_kuryr_git_install_branch: b096b19a5fcb2633160bbd9f03a3b69acf379057 # HEAD as of 09.08.2020
zun_kuryr_git_project_group: zun_all
zun_kuryr_git_track_branch: master
