---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


## NOTICE on items in this file:
##   * If you use anything in the *._git_install_branch field that is not a TAG
##     make sure to leave an in-line comment as to "why".

## For the sake of anyone else editing this file:
##   * If you add services to this file please do so in alphabetical order.
##   * Every entry should be name spaced with the name of the client followed by an "_"
##   * All items with this file should be separated by `name_` note that the name of the
##     package should be one long name with no additional `_` separating it.


### Before this is shipped all of these services should have a tag set as the branch,
### or have a comment / reason attached to them as to why a tag can not work.


## Global Requirements
requirements_git_repo: https://git.openstack.org/openstack/requirements
requirements_git_install_branch: ef16192e633b6e608e30e495529cbab8eaeece2b # HEAD of "stable/kilo" as of 17.09.2015
requirements_git_dest: "/opt/requirements_{{ requirements_git_install_branch | replace('/', '_') }}"


## Ceilometer service
ceilometer_git_repo: https://git.openstack.org/openstack/ceilometer
ceilometer_git_install_branch: c93ca9168e8f74e6b4f79d22ae4c1b34e36ef52c # HEAD of "stable/kilo" as of 17.09.2015
ceilometer_git_dest: "/opt/ceilometer_{{ceilometer_git_install_branch | replace('/', '_') }}"


## Cinder service
cinder_git_repo: https://git.openstack.org/openstack/cinder
cinder_git_install_branch: e8b25c6b8d929dd0836a7254a3b794c3480d6685 # HEAD of "stable/kilo" as of 17.09.2015
cinder_git_dest: "/opt/cinder_{{ cinder_git_install_branch | replace('/', '_') }}"


## Glance service
glance_git_repo: https://git.openstack.org/openstack/glance
glance_git_install_branch: 664404290e398d185665f8790bbdcb41f4746767 # HEAD of "stable/kilo" as of 17.09.2015
glance_git_dest: "/opt/glance_{{ glance_git_install_branch | replace('/', '_') }}"


## Heat service
heat_git_repo: https://git.openstack.org/openstack/heat
heat_git_install_branch: 721fe7babee64e54f9ab442e991b6d677471b194 # HEAD of "stable/kilo" as of 17.09.2015
heat_git_dest: "/opt/heat_{{ heat_git_install_branch | replace('/', '_') }}"
heat_repo_plugins:
  - { path: "contrib", package: "extraroute" }


## Horizon service
horizon_git_repo: https://git.openstack.org/openstack/horizon
horizon_git_install_branch: 8ed76248967ca741226dcebec1aa780e678fcf23 # HEAD of "stable/kilo" as of 17.09.2015
horizon_git_dest: "/opt/horizon_{{ horizon_git_install_branch | replace('/', '_') }}"


## Keystone service
keystone_git_repo: https://git.openstack.org/openstack/keystone
keystone_git_install_branch: b6c70ce410b3f8e3389a1308e2c0de33f982d3e5 # HEAD of "stable/kilo" as of 17.09.2015
keystone_git_dest: "/opt/keystone_{{ keystone_git_install_branch | replace('/', '_') }}"


## Neutron service
neutron_git_repo: https://git.openstack.org/openstack/neutron
neutron_git_install_branch: 4d15b6fe1259f2e9b17d76bc48050c7f54aad02e # HEAD of "stable/kilo" as of 17.09.2015
neutron_git_dest: "/opt/neutron_{{ neutron_git_install_branch | replace('/', '_') }}"

neutron_lbaas_git_repo: https://git.openstack.org/openstack/neutron-lbaas
neutron_lbaas_git_install_branch: 6343ed6e5ea10175cee8fdb620ef668a58dda0d9 # HEAD of "stable/kilo" as of 17.09.2015
neutron_lbaas_git_dest: "/opt/neutron_lbaas_{{ neutron_lbaas_git_install_branch | replace('/', '_') }}"

neutron_vpnaas_git_repo: https://git.openstack.org/openstack/neutron-vpnaas
neutron_vpnaas_git_install_branch: 5996aab16e776dd25c2d3fa3a48d7806f9c0f86f # HEAD of "stable/kilo" as of 17.09.2015
neutron_vpnaas_git_dest: "/opt/neutron_vpnaas_{{ neutron_vpnaas_git_install_branch | replace('/', '_') }}"

neutron_fwaas_git_repo: https://git.openstack.org/openstack/neutron-fwaas
neutron_fwaas_git_install_branch: aa8f3390e914593e11aac2734588397db8afa040 # HEAD of "stable/kilo" as of 17.09.2015
neutron_fwaas_git_dest: "/opt/neutron_fwaas_{{ neutron_fwaas_git_install_branch | replace('/', '_') }}"


## Nova service
nova_git_repo: https://git.openstack.org/openstack/nova
nova_git_install_branch: 328f38bad16423b4995644dbd3880cb8f132f566 # HEAD of "stable/kilo" as of 17.09.2015
nova_git_dest: "/opt/nova_{{ nova_git_install_branch | replace('/', '_') }}"


## Swift service
swift_git_repo: https://git.openstack.org/openstack/swift
swift_git_install_branch: da428c4f5613e31c6aeec8dda9738e896dd91324 # HEAD of "stable/kilo" as of 17.09.2015
swift_git_dest: "/opt/swift_{{ swift_git_install_branch | replace('/', '_') }}"
