---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


## NOTICE on items in this file:
##   * If you use anything in the *._git_install_branch field that is not a TAG
##     make sure to leave an in-line comment as to "why".

## For the sake of anyone else editing this file:
##   * If you add services to this file please do so in alphabetical order.
##   * Every entry should be name spaced with the name of the client followed by an "_"
##   * All items with this file should be separated by `name_` note that the name of the
##     package should be one long name with no additional `_` separating it.


### Before this is shipped all of these services should have a tag set as the branch,
### or have a comment / reason attached to them as to why a tag can not work.


## Global Requirements
requirements_git_repo: https://opendev.org/openstack/requirements
requirements_git_install_branch: 85ae62b804d28cebb4e4b40822d4464c73523b9b # HEAD as of 05.07.2021
requirements_git_track_branch: stable/ussuri


## Aodh service
aodh_git_repo: https://opendev.org/openstack/aodh
aodh_git_install_branch: d7b4f91c2f2e9d6a18a10ee4b668f8f78890cdb3  # HEAD as of 05.07.2021
aodh_git_project_group: aodh_all
aodh_git_track_branch: stable/ussuri


## Barbican service
barbican_git_repo: https://opendev.org/openstack/barbican
barbican_git_install_branch: 7cf483e205736483b4999abfe4baf6f626fff862  # HEAD as of 05.07.2021
barbican_git_project_group: barbican_all
barbican_git_track_branch: stable/ussuri


## Ceilometer service
ceilometer_git_repo: https://opendev.org/openstack/ceilometer
ceilometer_git_install_branch: f18675aed4e0c96e73ae58fc10e26020fd6ad824  # HEAD as of 05.07.2021
ceilometer_git_project_group: all
ceilometer_git_track_branch: stable/ussuri


## Cinder service
cinder_git_repo: https://opendev.org/openstack/cinder
cinder_git_install_branch: 62da2018555a0a59941e42eecf05a8ffbd66d7a9  # HEAD as of 05.07.2021
cinder_git_project_group: cinder_all
cinder_git_track_branch: stable/ussuri


## Designate service
designate_git_repo: https://opendev.org/openstack/designate
designate_git_install_branch: b967e9f706373f1aad6db882c2295fbbe1fadfc9  # HEAD as of 05.07.2021
designate_git_project_group: designate_all
designate_git_track_branch: stable/ussuri


## Horizon Designate dashboard plugin
designate_dashboard_git_repo: https://opendev.org/openstack/designate-dashboard
designate_dashboard_git_install_branch: 0859e4e16f622991382ce3cc86951c0458d555c1  # HEAD as of 05.07.2021
designate_dashboard_git_project_group: horizon_all
designate_dashboard_git_track_branch: stable/ussuri


## Glance service
glance_git_repo: https://opendev.org/openstack/glance
glance_git_install_branch: cc22468d74cc83a24c198cc45a827f0ed14b3227  # HEAD as of 05.07.2021
glance_git_project_group: glance_all
glance_git_track_branch: stable/ussuri


## Heat service
heat_git_repo: https://opendev.org/openstack/heat
heat_git_install_branch: b9a3395978bf60d3ce769b8fcedc60b7127f404f  # HEAD as of 05.07.2021
heat_git_package_name: openstack-heat
heat_git_project_group: heat_all
heat_git_track_branch: stable/ussuri

## Horizon Heat dashboard plugin
heat_dashboard_git_repo: https://opendev.org/openstack/heat-dashboard
heat_dashboard_git_install_branch: 5b4fe3ba50ca1cf23bde2e9c74d7cedbf3a8123f  # HEAD as of 05.07.2021
heat_dashboard_git_project_group: horizon_all
heat_dashboard_git_track_branch: stable/ussuri

## Horizon service
horizon_git_repo: https://opendev.org/openstack/horizon
horizon_git_install_branch: 7555c16cf6247c9ecf8f18dd565828f812338357  # HEAD as of 05.07.2021
horizon_git_project_group: horizon_all
horizon_git_track_branch: stable/ussuri

## Horizon Ironic dashboard plugin
ironic_dashboard_git_repo: https://opendev.org/openstack/ironic-ui
ironic_dashboard_git_install_branch: feb6e927384259b3d14d34cfa60d5ddf9a89d820  # HEAD as of 05.07.2021
ironic_dashboard_git_project_group: horizon_all
ironic_dashboard_git_track_branch: stable/ussuri

## Horizon Magnum dashboard plugin
magnum_dashboard_git_repo: https://opendev.org/openstack/magnum-ui
magnum_dashboard_git_install_branch: 4a561a93742d3c9cfa5c243601e89515cfd7d155  # HEAD as of 05.07.2021
magnum_dashboard_git_project_group: horizon_all
magnum_dashboard_git_track_branch: stable/ussuri

## Horizon Masakari dashboard plugin
masakari_dashboard_git_repo: https://opendev.org/openstack/masakari-dashboard
masakari_dashboard_git_install_branch: d5c42e7e1a262ccb782d218a71214b9bbf238c3c  # HEAD as of 05.07.2021
masakari_dashboard_git_project_group: horizon_all
masakari_dashboard_git_track_branch: stable/ussuri

## Horizon FWaaS dashboard plugin
neutron_fwaas_dashboard_git_repo: https://opendev.org/openstack/neutron-fwaas-dashboard
neutron_fwaas_dashboard_git_install_branch: ed079563319ee07eb9ea919ebd3fd7c3449a392a  # HEAD as of 05.07.2021
neutron_fwaas_dashboard_git_project_group: horizon_all
neutron_fwaas_dashboard_git_track_branch: stable/ussuri

## Horizon Sahara dashboard plugin
sahara_dashboard_git_repo: https://opendev.org/openstack/sahara-dashboard
sahara_dashboard_git_install_branch: 0fa9e96aa8588063edf95c7b5dd45e982f82bedc # HEAD as of 05.07.2021
sahara_dashboard_git_project_group: horizon_all
sahara_dashboard_git_track_branch: stable/ussuri


## Keystone service
keystone_git_repo: https://opendev.org/openstack/keystone
keystone_git_install_branch: 2cf2912fd4d23bd8515313eafc77c6df92c68b81  # HEAD as of 05.07.2021
keystone_git_project_group: keystone_all
keystone_git_track_branch: stable/ussuri


## Manila service
manila_git_repo: https://opendev.org/openstack/manila
manila_git_install_branch: 1dc105e37fe6456a285c97e9b68a81e63999e879  # HEAD as of 05.07.2021
manila_git_project_group: manila_all
manila_git_track_branch: stable/ussuri


## Neutron service
neutron_git_repo: https://opendev.org/openstack/neutron
neutron_git_install_branch: e0748a58efe6fdb2931047dffa267fa4e2d54615  # HEAD as of 05.07.2021
neutron_git_project_group: neutron_all
neutron_git_track_branch: stable/ussuri

neutron_vpnaas_git_repo: https://opendev.org/openstack/neutron-vpnaas
neutron_vpnaas_git_install_branch: 180fc9dcbc7debe4a3972a3d2877645a24f27a61  # HEAD as of 05.07.2021
neutron_vpnaas_git_project_group: neutron_all
neutron_vpnaas_git_track_branch: stable/ussuri

neutron_fwaas_git_repo: https://opendev.org/openstack/neutron-fwaas
neutron_fwaas_git_install_branch: 59bad17387d15f86ea7d08f8675208160a999ffe  # HEAD as of 05.07.2021
neutron_fwaas_git_project_group: neutron_all
neutron_fwaas_git_track_branch: stable/ussuri

neutron_dynamic_routing_git_repo: https://opendev.org/openstack/neutron-dynamic-routing
neutron_dynamic_routing_git_install_branch: 42000ee7a5383b4e3883c11e574cafe075ba245e  # HEAD as of 05.07.2021
neutron_dynamic_routing_git_project_group: neutron_all
neutron_dynamic_routing_git_track_branch: stable/ussuri

# Networking calico follows master
networking_calico_git_repo: https://github.com/projectcalico/networking-calico
networking_calico_git_install_branch: v3.14.0  # HEAD as of 19.05.2020
networking_calico_git_project_group: neutron_all
networking_calico_git_track_branch: None

networking_odl_git_repo: https://opendev.org/openstack/networking-odl
networking_odl_git_install_branch: 07d98314db6d6b513900fbb1b0536f221145244c  # HEAD as of 05.07.2021
networking_odl_git_project_group: neutron_all
networking_odl_git_track_branch: stable/ussuri

networking_bgpvpn_git_repo: https://opendev.org/openstack/networking-bgpvpn
networking_bgpvpn_git_install_branch: c38e8902fd15d36a857b251133cd6db453acd7b9  # HEAD as of 05.07.2021
networking_bgpvpn_git_project_group: neutron_all
networking_bgpvpn_git_track_branch: stable/ussuri

networking_sfc_git_repo: https://opendev.org/openstack/networking-sfc
networking_sfc_git_install_branch: ba57ca7d1f2d8f5986103cf114089f5ca159dd77  # HEAD as of 05.07.2021
networking_sfc_git_project_group: neutron_all
networking_sfc_git_track_branch: stable/ussuri


## Nova service
nova_git_repo: https://opendev.org/openstack/nova
nova_git_install_branch: 32f2d3940d66d85cb5d9c56329f3476f50933d76  # HEAD as of 05.07.2021
nova_git_project_group: nova_all
nova_git_track_branch: stable/ussuri


## Sahara service
sahara_git_repo: https://opendev.org/openstack/sahara
sahara_git_install_branch: 57fd4a113716d641017d025dd245e7a2c5d931d1 # HEAD as of 05.07.2021
sahara_git_project_group: sahara_all
sahara_git_track_branch: stable/ussuri


## Swift service
swift_git_repo: https://opendev.org/openstack/swift
swift_git_install_branch: 4b0d6a87e9b2d0a032fe3b3a85e6fef0e5e8839f # HEAD as of 05.07.2021
swift_git_project_group: swift_all
swift_git_track_branch: stable/ussuri


## Ironic service
ironic_git_repo: https://opendev.org/openstack/ironic
ironic_git_install_branch: 2f802e63abad90af6817a45a8e33a5529e31d038  # HEAD as of 05.07.2021
ironic_git_project_group: ironic_all
ironic_git_track_branch: stable/ussuri


## Ironic inspector service
ironic_inspector_git_repo: https://opendev.org/openstack/ironic-inspector
ironic_inspector_git_install_branch: 37827cf2ede6e91182a3a7bfa2f4cdc268eceeba  # HEAD as of 05.07.2021
ironic_inspector_git_project_group: ironic_inspector
ironic_inspector_git_track_branch: stable/ussuri


## Magnum service
magnum_git_repo: https://opendev.org/openstack/magnum
magnum_git_install_branch: 9c9a84f6690d11356212070b4c5221c8c3e7777d  # HEAD as of 05.07.2021
magnum_git_project_group: magnum_all
magnum_git_track_branch: stable/ussuri

## Masakari service
masakari_git_repo: https://opendev.org/openstack/masakari
masakari_git_install_branch: 35519c0ce02092aaef6b802817b74d017a84b08b  # HEAD as of 05.07.2021
masakari_git_project_group: masakari_api
masakari_git_track_branch: stable/ussuri

## Masakari monitors services
masakari_monitors_git_repo: https://opendev.org/openstack/masakari-monitors
masakari_monitors_git_install_branch: 61b72e86875984e49719d0fe568ac1073c68e301  # HEAD as of 05.07.2021
masakari_monitors_git_project_group: masakari_monitor
masakari_monitors_git_track_branch: stable/ussuri

## Mistral service
mistral_git_repo: https://opendev.org/openstack/mistral
mistral_git_install_branch: 2a1736f0709d7316ae9b7bf6fa9b488c7a342009  # HEAD as of 05.07.2021
mistral_git_project_group: mistral_all
mistral_git_track_branch: stable/ussuri

## Murano service
murano_git_repo: https://opendev.org/openstack/murano
murano_git_install_branch: 1daccfced80ae3dfac59f08fd20d31244ef9d94a  # HEAD as of 05.07.2021
murano_git_project_group: murano_all
murano_git_track_branch: stable/ussuri

## Trove service
trove_git_repo: https://opendev.org/openstack/trove
trove_git_install_branch: 48e39a07a60c9a7ce9b2fbfcc97a16bc2c56723f # HEAD as of 05.07.2021
trove_git_project_group: trove_all
trove_git_track_branch: stable/ussuri

## Horizon Trove dashboard plugin
trove_dashboard_git_repo: https://opendev.org/openstack/trove-dashboard
trove_dashboard_git_install_branch: db7a5abd655d871cc036a4b59eeb4225f028e2da # HEAD as of 05.07.2021
trove_dashboard_git_project_group: horizon_all
trove_dashboard_git_track_branch: stable/ussuri


## Octavia service
octavia_git_repo: https://opendev.org/openstack/octavia
octavia_git_install_branch: c0af684fd701706a9fcf80a64991f070132591b7  # HEAD as of 05.07.2021
octavia_git_project_group: octavia_all
octavia_git_track_branch: stable/ussuri


## Panko service
panko_git_repo: https://opendev.org/openstack/panko
panko_git_install_branch: 0a8d5b4fc0169108468404e88d12ee6fefed4e63  # HEAD as of 05.07.2021
panko_git_project_group: panko_all
panko_git_track_branch: stable/ussuri


## Placement service
placement_git_repo: https://opendev.org/openstack/placement
placement_git_install_branch: de030ef7a78b1b9ee2da75552d1edc829f830aa4  # HEAD as of 05.07.2021
placement_git_project_group: placement_all
placement_git_track_branch: stable/ussuri


## Tacker service
tacker_git_repo: https://opendev.org/openstack/tacker
tacker_git_install_branch: 5783b9fff46544e1d50f1d3eafc254095f9f9b99 # HEAD as of 05.07.2021
tacker_git_project_group: tacker_all
tacker_git_track_branch: stable/ussuri


## Congress service
congress_git_repo: https://github.com/openstack-archive/congress
congress_git_install_branch: 85243abf63dfc7c086e28e9bdb3fb0b7c9d2ad94  # HEAD as of 05.07.2021
congress_git_package_name: openstack-congress
congress_git_project_group: congress_all
congress_git_track_branch: refs/heads/stable/ussuri

## Horizon Octavia dashboard plugin
octavia_dashboard_git_repo: https://opendev.org/openstack/octavia-dashboard
octavia_dashboard_git_install_branch: eac97f1525d5f74ce4cd26506f77d2a36455c85c  # HEAD as of 05.07.2021
octavia_dashboard_git_project_group: horizon_all
octavia_dashboard_git_track_branch: stable/ussuri


## Blazar service
blazar_git_repo: https://opendev.org/openstack/blazar
blazar_git_install_branch: aea56f5269628bd2a1365bebe17776d8c3ba8300  # HEAD as of 05.07.2021
blazar_git_project_group: blazar_all
blazar_git_track_branch: stable/ussuri

## Blazar Nova Service
blazar_nova_git_repo: https://opendev.org/openstack/blazar-nova
blazar_nova_git_install_branch: 6d9f33cb99dcced4c74eca79385b7b58ac026b15  # HEAD as of 05.07.2021
blazar_nova_git_project_group: blazar_all
blazar_nova_git_track_branch: stable/ussuri

## Zun service
zun_git_repo: https://opendev.org/openstack/zun
zun_git_install_branch: 5d41a395f0b8a02c7c5970f4b54d77c22d548986 # HEAD as of 05.07.2021
zun_git_project_group: zun_all
zun_git_track_branch: stable/ussuri

## Zun kuryr service
zun_kuryr_git_repo: https://opendev.org/openstack/kuryr-libnetwork
zun_kuryr_git_install_branch: b2b1a36d0db096a5ccfe4084e291e2b5004f8bb7 # HEAD as of 05.07.2021
zun_kuryr_git_project_group: zun_all
zun_kuryr_git_track_branch: stable/ussuri

## Zun kuryr library
zun_kuryr_lib_git_repo: https://opendev.org/openstack/kuryr
zun_kuryr_lib_git_install_branch: dbcca8aa716677c273ec898bc6bc5dc08a17644f # HEAD as of 05.07.2021
zun_kuryr_lib_git_project_group: zun_all
zun_kuryr_lib_git_track_branch: stable/ussuri
