---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


## NOTICE on items in this file:
##   * If you use anything in the *._git_install_branch field that is not a TAG
##     make sure to leave an in-line comment as to "why".

## For the sake of anyone else editing this file:
##   * If you add services to this file please do so in alphabetical order.
##   * Every entry should be name spaced with the name of the client followed by an "_"
##   * All items with this file should be separated by `name_` note that the name of the
##     package should be one long name with no additional `_` separating it.


### Before this is shipped all of these services should have a tag set as the branch,
### or have a comment / reason attached to them as to why a tag can not work.


## Global Requirements
requirements_git_repo: https://opendev.org/openstack/requirements
requirements_git_install_branch: 210c8eac0df141191be4e5256543fc12c1893d94 # HEAD as of 25.10.2021
requirements_git_track_branch: stable/wallaby

## Adjutant service
adjutant_git_repo: https://opendev.org/openstack/adjutant
adjutant_git_install_branch: 14af21cb3bf91ac975a331f673b3c0c59c14b560 # HEAD as of 25.10.2021
adjutant_git_track_branch: stable/wallaby

## Adjutant dashboard plugin
adjutant_dashboard_git_repo: https://opendev.org/openstack/adjutant-ui
adjutant_dashboard_git_install_branch: 104c474479e9a89d22b96777378ff59983c03393 # HEAD as of 25.10.2021
adjutant_dashboard_git_track_branch: stable/wallaby

## Aodh service
aodh_git_repo: https://opendev.org/openstack/aodh
aodh_git_install_branch: 1fb8cde66b81c6e138749956824c7676ba6073a7 # HEAD as of 25.10.2021
aodh_git_track_branch: stable/wallaby


## Barbican service
barbican_git_repo: https://opendev.org/openstack/barbican
barbican_git_install_branch: 2792aca796400055c5d1dc3d3f32b7b29f3a605d # HEAD as of 25.10.2021
barbican_git_track_branch: stable/wallaby


## Barbican dashboard plugin
barbican_dashboard_git_repo: https://opendev.org/openstack/barbican-ui
barbican_dashboard_git_install_branch: 3a78a743426376250f43508d4281e86c75067271 # HEAD as of 25.10.2021
barbican_dashboard_git_track_branch: master


## Ceilometer service
ceilometer_git_repo: https://opendev.org/openstack/ceilometer
ceilometer_git_install_branch: 8fd515773bc98309dc9c9a5b1f1363f2f98a85f8 # HEAD as of 25.10.2021
ceilometer_git_track_branch: stable/wallaby


## Cinder service
cinder_git_repo: https://opendev.org/openstack/cinder
cinder_git_install_branch: 3cefcf776f35ee216b6252b8819f17b9aeb5b2f3 # HEAD as of 25.10.2021
cinder_git_track_branch: stable/wallaby


## Cloudkitty service
cloudkitty_git_repo: https://opendev.org/openstack/cloudkitty
cloudkitty_git_install_branch: 875cacdd46b4a7b70b3affb4e63effd01ac098cb # HEAD as of 25.10.2021
cloudkitty_git_track_branch: stable/wallaby


## Cloudkitty dashboard plugin
cloudkitty_dashboard_git_repo: https://opendev.org/openstack/cloudkitty-dashboard
cloudkitty_dashboard_git_install_branch: 31c6d8c3164a1386fd0ada8e1d24fb58180c3214 # HEAD as of 25.10.2021
cloudkitty_dashboard_git_track_branch: stable/wallaby


## Designate service
designate_git_repo: https://opendev.org/openstack/designate
designate_git_install_branch: d7cd95847a04a74ccce58bd7fd52fde5ecd52c21 # HEAD as of 25.10.2021
designate_git_track_branch: stable/wallaby


## Horizon Designate dashboard plugin
designate_dashboard_git_repo: https://opendev.org/openstack/designate-dashboard
designate_dashboard_git_install_branch: a65ea0165cd5b511ed23c36382b1a29d8d41df6d # HEAD as of 25.10.2021
designate_dashboard_git_track_branch: stable/wallaby


## Glance service
glance_git_repo: https://opendev.org/openstack/glance
glance_git_install_branch: 8499efd3205d84eff35ed4ed157685313d9e3fb7 # HEAD as of 25.10.2021
glance_git_track_branch: stable/wallaby


## Heat service
heat_git_repo: https://opendev.org/openstack/heat
heat_git_install_branch: ead4022533807b69ee913292f9ff9d84855cafa9 # HEAD as of 25.10.2021
heat_git_track_branch: stable/wallaby

## Horizon Heat dashboard plugin
heat_dashboard_git_repo: https://opendev.org/openstack/heat-dashboard
heat_dashboard_git_install_branch: cd889e6146ca11c70cd2a020a66547b270bf2660 # HEAD as of 25.10.2021
heat_dashboard_git_track_branch: stable/wallaby

## Horizon service
horizon_git_repo: https://opendev.org/openstack/horizon
horizon_git_install_branch: 4e402ada25f1ac9ca19777086d503810d7f218a2 # HEAD as of 25.10.2021
horizon_git_track_branch: stable/wallaby

## Horizon Ironic dashboard plugin
ironic_dashboard_git_repo: https://opendev.org/openstack/ironic-ui
ironic_dashboard_git_install_branch: 98f31e49e2c916bc56baaaffe717ca3ab7adce87 # HEAD as of 25.10.2021
ironic_dashboard_git_track_branch: stable/wallaby

## Horizon Magnum dashboard plugin
magnum_dashboard_git_repo: https://opendev.org/openstack/magnum-ui
magnum_dashboard_git_install_branch: e523a37bde515954478c14bb9e510f5c53cbe981 # HEAD as of 25.10.2021
magnum_dashboard_git_track_branch: stable/wallaby

## Horizon Masakari dashboard plugin
masakari_dashboard_git_repo: https://opendev.org/openstack/masakari-dashboard
masakari_dashboard_git_install_branch: a879b6bbfbd17d2a4dbee4c0dde200db7d944631 # HEAD as of 25.10.2021
masakari_dashboard_git_track_branch: stable/wallaby


## Horizon Sahara dashboard plugin
sahara_dashboard_git_repo: https://opendev.org/openstack/sahara-dashboard
sahara_dashboard_git_install_branch: 211f92dc453b37f8c2f9245b19e345e881cf4b95 # HEAD as of 25.10.2021
sahara_dashboard_git_track_branch: stable/wallaby


## Keystone service
keystone_git_repo: https://opendev.org/openstack/keystone
keystone_git_install_branch: 327312c3320165e1426c275eb5697fe39315229a # HEAD as of 25.10.2021
keystone_git_track_branch: stable/wallaby


## Manila service
manila_git_repo: https://opendev.org/openstack/manila
manila_git_install_branch: 7eca10bcb56574cd11fd6a929d87458b0aba20be # HEAD as of 25.10.2021
manila_git_track_branch: stable/wallaby


## Neutron service
neutron_git_repo: https://opendev.org/openstack/neutron
neutron_git_install_branch: fa9b3c7e520e7976cb30791030046ea8508a6801 # HEAD as of 25.10.2021
neutron_git_track_branch: stable/wallaby

neutron_vpnaas_git_repo: https://opendev.org/openstack/neutron-vpnaas
neutron_vpnaas_git_install_branch: 2cf3451517c09dc998bc7e3e194916601a728c03 # HEAD as of 25.10.2021
neutron_vpnaas_git_track_branch: stable/wallaby


neutron_dynamic_routing_git_repo: https://opendev.org/openstack/neutron-dynamic-routing
neutron_dynamic_routing_git_install_branch: 2f9dbc1df51cebb8bf26153a33060f0414d9dac8 # HEAD as of 25.10.2021
neutron_dynamic_routing_git_track_branch: stable/wallaby

# Networking calico follows master
networking_calico_git_repo: https://github.com/projectcalico/networking-calico
networking_calico_git_install_branch: ff42aafb57b1a249f59356c2ed61b52762319b18 # HEAD as of 25.10.2021
networking_calico_git_track_branch: release-v3.18

networking_odl_git_repo: https://opendev.org/openstack/networking-odl
networking_odl_git_install_branch: b377b3aa527a87f415f1a6a59362229f99855802 # HEAD as of 25.10.2021
networking_odl_git_track_branch: stable/wallaby

networking_bgpvpn_git_repo: https://opendev.org/openstack/networking-bgpvpn
networking_bgpvpn_git_install_branch: 188121ae61f16656b721485147e6feb98201bb99 # HEAD as of 25.10.2021
networking_bgpvpn_git_track_branch: stable/wallaby

networking_sfc_git_repo: https://opendev.org/openstack/networking-sfc
networking_sfc_git_install_branch: 71d44504dab4eac9c802db6962c10b956f52ffb1 # HEAD as of 25.10.2021
networking_sfc_git_track_branch: stable/wallaby

networking_generic_switch_git_repo: https://opendev.org/openstack/networking-generic-switch
networking_generic_switch_git_install_branch: 9dc003025bb8d2f1a73264acb1fcc7260a98d22c # HEAD as of 25.10.2021
networking_generic_switch_git_track_branch: stable/wallaby

networking_nsx_git_repo: https://opendev.org/x/vmware-nsx
networking_nsx_git_install_branch: 5b2151d9767b5d0ec7ebed65ae1afc02242dd792 # HEAD as of 25.10.2021
networking_nsx_git_track_branch: master

networking_nsxlib_git_repo: https://opendev.org/x/vmware-nsxlib
networking_nsxlib_git_install_branch: fedb0ba5d370465dbe8b134c83b7796fd483ed09 # HEAD as of 25.10.2021
networking_nsxlib_git_track_branch: master

## Nova service
nova_git_repo: https://opendev.org/openstack/nova
nova_git_install_branch: e39bbdc8afdbe1075265008f336336d3b76f0a27 # HEAD as of 25.10.2021
nova_git_track_branch: stable/wallaby


## Sahara service
sahara_git_repo: https://opendev.org/openstack/sahara
sahara_git_install_branch: 452affc54ba98031d0b75d61ed91329364e79c97 # HEAD as of 25.10.2021
sahara_git_track_branch: stable/wallaby


## Senlin service
senlin_git_repo: https://opendev.org/openstack/senlin
senlin_git_install_branch: c7842da4cf357faab343f0974e37dda448364ce4 # HEAD as of 25.10.2021
senlin_git_track_branch: stable/wallaby


## Swift service
swift_git_repo: https://opendev.org/openstack/swift
swift_git_install_branch: c966628978ac4ceb1d94ba92879df071b8ca265d # HEAD as of 25.10.2021
swift_git_track_branch: stable/wallaby


## Ironic service
ironic_git_repo: https://opendev.org/openstack/ironic
ironic_git_install_branch: d0c70aaf282de9b2ef4268c82054cadd0439af15 # HEAD as of 25.10.2021
ironic_git_track_branch: stable/wallaby


## Ironic inspector service
ironic_inspector_git_repo: https://opendev.org/openstack/ironic-inspector
ironic_inspector_git_install_branch: 06c65757c7eb43c4ac953548591349f8600c2ce3 # HEAD as of 25.10.2021
ironic_inspector_git_track_branch: stable/wallaby


## Magnum service
magnum_git_repo: https://opendev.org/openstack/magnum
magnum_git_install_branch: 5dfe6e0e760191b9a579985b5cfd5caf88e7b927 # HEAD as of 25.10.2021
magnum_git_track_branch: stable/wallaby

## Masakari service
masakari_git_repo: https://opendev.org/openstack/masakari
masakari_git_install_branch: 05124e1576e15885d2a7c3b409a3ea3a33a62a98 # HEAD as of 25.10.2021
masakari_git_track_branch: stable/wallaby

## Masakari monitors services
masakari_monitors_git_repo: https://opendev.org/openstack/masakari-monitors
masakari_monitors_git_install_branch: d090789f1247772cc37b0b7238d67f20ab644540 # HEAD as of 25.10.2021
masakari_monitors_git_track_branch: stable/wallaby

## Mistral service
mistral_git_repo: https://opendev.org/openstack/mistral
mistral_git_install_branch: c2a0205d56642ad920d94953079c98e17c7b3536 # HEAD as of 25.10.2021
mistral_git_track_branch: stable/wallaby

## Murano service
murano_git_repo: https://opendev.org/openstack/murano
murano_git_install_branch: 93dc1f7ce8100d065da5af60820444182f3b8886 # HEAD as of 25.10.2021
murano_git_track_branch: stable/wallaby

murano_dashboard_git_repo: https://opendev.org/openstack/murano-dashboard
murano_dashboard_git_install_branch: c01fbfcaeabd74f2a6b5edbe07c7d9d7515a9dea # HEAD as of 25.10.2021
murano_dashboard_git_track_branch: stable/wallaby

## Trove service
trove_git_repo: https://opendev.org/openstack/trove
trove_git_install_branch: 3b846ad235e459481b1bd566a7a697e4ce508a91 # HEAD as of 25.10.2021
trove_git_track_branch: stable/wallaby

## Horizon Trove dashboard plugin
trove_dashboard_git_repo: https://opendev.org/openstack/trove-dashboard
trove_dashboard_git_install_branch: 3a6e79c3c0cabaf3293046647481a792895efb05 # HEAD as of 25.10.2021
trove_dashboard_git_track_branch: stable/wallaby


## Octavia service
octavia_git_repo: https://opendev.org/openstack/octavia
octavia_git_install_branch: 5f502596a94c74dca2dc17c22544c79da0febac7 # HEAD as of 25.10.2021
octavia_git_track_branch: stable/wallaby


## Panko service
panko_git_repo: https://opendev.org/openstack/panko
panko_git_install_branch: 276d891675c692c146448180767f97362871b493 # HEAD as of 25.10.2021
panko_git_track_branch: stable/wallaby


## Placement service
placement_git_repo: https://opendev.org/openstack/placement
placement_git_install_branch: adf525a8f176fe37222d08478c9fe08db823db98 # HEAD as of 25.10.2021
placement_git_track_branch: stable/wallaby


## Tacker service
tacker_git_repo: https://opendev.org/openstack/tacker
tacker_git_install_branch: 74fd9813aed21589da79ce9e0fcea19345fca089 # HEAD as of 25.10.2021
tacker_git_track_branch: stable/wallaby


## Horizon Octavia dashboard plugin
octavia_dashboard_git_repo: https://opendev.org/openstack/octavia-dashboard
octavia_dashboard_git_install_branch: b4c76b96868dd22d5d1f306ac01129eb882e2d74 # HEAD as of 25.10.2021
octavia_dashboard_git_track_branch: stable/wallaby


## Blazar service
blazar_git_repo: https://opendev.org/openstack/blazar
blazar_git_install_branch: 43587aa53efdeb8a978a8c4408ec61ff7db6287f # HEAD as of 25.10.2021
blazar_git_track_branch: stable/wallaby

## Blazar Nova Service
blazar_nova_git_repo: https://opendev.org/openstack/blazar-nova
blazar_nova_git_install_branch: c71d01e3955a5904d1f557840285292422cbefe6 # HEAD as of 25.10.2021
blazar_nova_git_track_branch: stable/wallaby

## Zun service
zun_git_repo: https://opendev.org/openstack/zun
zun_git_install_branch: 12685be9b4947d856a405fd059f0fe15aa957512 # HEAD as of 25.10.2021
zun_git_track_branch: stable/wallaby

## Zun kuryr service
zun_kuryr_git_repo: https://opendev.org/openstack/kuryr-libnetwork
zun_kuryr_git_install_branch: 2d4cf6435e7878d11e5bcdb280c841dd8aabaf64 # HEAD as of 25.10.2021
zun_kuryr_git_track_branch: stable/wallaby

## Zun kuryr library
zun_kuryr_lib_git_repo: https://opendev.org/openstack/kuryr
zun_kuryr_lib_git_install_branch: 18590ef0a13d3bc9bb1f0759dfd1ce6a16079507 # HEAD as of 25.10.2021
zun_kuryr_lib_git_track_branch: stable/wallaby
