---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


## NOTICE on items in this file:
##   * If you use anything in the *._git_install_branch field that is not a TAG
##     make sure to leave an in-line comment as to "why".

## For the sake of anyone else editing this file:
##   * If you add services to this file please do so in alphabetical order.
##   * Every entry should be name spaced with the name of the client followed by an "_"
##   * All items with this file should be separated by `name_` note that the name of the
##     package should be one long name with no additional `_` separating it.


### Before this is shipped all of these services should have a tag set as the branch,
### or have a comment / reason attached to them as to why a tag can not work.


## Global Requirements
requirements_git_repo: https://opendev.org/openstack/requirements
requirements_git_install_branch: 4bb5643ad24d1ed49e5095ad1b8aefb168b12b12 # HEAD as of 20.12.2020
requirements_git_track_branch: master

## Adjutant service
adjutant_git_repo: https://opendev.org/openstack/adjutant
adjutant_git_install_branch: 43e0c625e39f826b578e3e5c25519606d9b72808 # HEAD as of 20.12.2020
adjutant_git_track_branch: master

## Aodh service
aodh_git_repo: https://opendev.org/openstack/aodh
aodh_git_install_branch: 0bac3700b39424eced6aeb5419734855eeaf4462 # HEAD as of 20.12.2020
aodh_git_track_branch: master


## Barbican service
barbican_git_repo: https://opendev.org/openstack/barbican
barbican_git_install_branch: 5734539d44672ab128c50e36def058b9f3e5729f # HEAD as of 20.12.2020
barbican_git_track_branch: master


## Ceilometer service
ceilometer_git_repo: https://opendev.org/openstack/ceilometer
ceilometer_git_install_branch: befe51814d27e1219d792fefd9c3afcca36972b0 # HEAD as of 20.12.2020
ceilometer_git_track_branch: master


## Cinder service
cinder_git_repo: https://opendev.org/openstack/cinder
cinder_git_install_branch: 482e6a3cc5cca697b54ee1d853a4eca6e6f3cfc7 # HEAD as of 20.12.2020
cinder_git_track_branch: master


## Designate service
designate_git_repo: https://opendev.org/openstack/designate
designate_git_install_branch: e8c901c32318a4f6bec7cb4f6d95fcc48c57ad73 # HEAD as of 20.12.2020
designate_git_track_branch: master


## Horizon Designate dashboard plugin
designate_dashboard_git_repo: https://opendev.org/openstack/designate-dashboard
designate_dashboard_git_install_branch: 0fb4e2e99e4dbf2859790d4a627c04f136a0bafc # HEAD as of 20.12.2020
designate_dashboard_git_track_branch: master


## Glance service
glance_git_repo: https://opendev.org/openstack/glance
glance_git_install_branch: 73742be99944d923031aa5f90e06051126b17007 # HEAD as of 20.12.2020
glance_git_track_branch: master


## Heat service
heat_git_repo: https://opendev.org/openstack/heat
heat_git_install_branch: 7e12f698455cfc76151c3067f99f81c25f1e083a # HEAD as of 20.12.2020
heat_git_track_branch: master

## Horizon Heat dashboard plugin
heat_dashboard_git_repo: https://opendev.org/openstack/heat-dashboard
heat_dashboard_git_install_branch: a36e451c1774a17cbdc62af3c90e64497b3f38c1 # HEAD as of 20.12.2020
heat_dashboard_git_track_branch: master

## Horizon service
horizon_git_repo: https://opendev.org/openstack/horizon
horizon_git_install_branch: 4d1ec9b3a472a753e6597fc13a8bd07c75b4ab2d # HEAD as of 20.12.2020
horizon_git_track_branch: master

## Horizon Ironic dashboard plugin
ironic_dashboard_git_repo: https://opendev.org/openstack/ironic-ui
ironic_dashboard_git_install_branch: a3d0f4e62672cba5dde6e211bb9a44964be164af # HEAD as of 20.12.2020
ironic_dashboard_git_track_branch: master

## Horizon Magnum dashboard plugin
magnum_dashboard_git_repo: https://opendev.org/openstack/magnum-ui
magnum_dashboard_git_install_branch: 086d1376e8848a669389bddff2e8aea484bb11ed # HEAD as of 20.12.2020
magnum_dashboard_git_track_branch: master

## Horizon Masakari dashboard plugin
masakari_dashboard_git_repo: https://opendev.org/openstack/masakari-dashboard
masakari_dashboard_git_install_branch: 27bdc6a6d8dba388c8e7bd08d908c66d7978c8ab # HEAD as of 20.12.2020
masakari_dashboard_git_track_branch: master


## Horizon Sahara dashboard plugin
sahara_dashboard_git_repo: https://opendev.org/openstack/sahara-dashboard
sahara_dashboard_git_install_branch: 1e67bcbe6a166b02c907da9f4ffc48908b8c7b4b # HEAD as of 20.12.2020
sahara_dashboard_git_track_branch: master


## Keystone service
keystone_git_repo: https://opendev.org/openstack/keystone
keystone_git_install_branch: b0b93c03986f3bb40c5a2ec31ee37c83014e197a # HEAD as of 20.12.2020
keystone_git_track_branch: master


## Manila service
manila_git_repo: https://opendev.org/openstack/manila
manila_git_install_branch: 99d21fa8e5b807114cff5bc667e9c6687be6a2cc # HEAD as of 20.12.2020
manila_git_track_branch: master


## Neutron service
neutron_git_repo: https://opendev.org/openstack/neutron
neutron_git_install_branch: 74e4cd31f1f68153bad62897fe3944054568ff3f # HEAD as of 20.12.2020
neutron_git_track_branch: master

neutron_vpnaas_git_repo: https://opendev.org/openstack/neutron-vpnaas
neutron_vpnaas_git_install_branch: fd4eb472ae89d711133e99f3910ed0b87245387e # HEAD as of 20.12.2020
neutron_vpnaas_git_track_branch: master


neutron_dynamic_routing_git_repo: https://opendev.org/openstack/neutron-dynamic-routing
neutron_dynamic_routing_git_install_branch: 6a6f49b609a50a55a71348d82a696d6976155a06 # HEAD as of 20.12.2020
neutron_dynamic_routing_git_track_branch: master

# Networking calico follows master
networking_calico_git_repo: https://github.com/projectcalico/networking-calico
networking_calico_git_install_branch: 1a588c56645333ab044cf98661498d4e601d1590 # HEAD as of 20.12.2020
networking_calico_git_track_branch: release-v3.16

networking_odl_git_repo: https://opendev.org/openstack/networking-odl
networking_odl_git_install_branch: 94edf39f3dfaa2a3dabde68904a0ddd94ab3374d # HEAD as of 20.12.2020
networking_odl_git_track_branch: master

networking_bgpvpn_git_repo: https://opendev.org/openstack/networking-bgpvpn
networking_bgpvpn_git_install_branch: 2722d5a0ad8e921064b875b00c5108afd2937676 # HEAD as of 20.12.2020
networking_bgpvpn_git_track_branch: master

networking_sfc_git_repo: https://opendev.org/openstack/networking-sfc
networking_sfc_git_install_branch: c1fd7280d4ddac10b2c436bdbde0bf7f88cee1db # HEAD as of 20.12.2020
networking_sfc_git_track_branch: master

networking_generic_switch_git_repo: https://opendev.org/openstack/networking-generic-switch
networking_generic_switch_git_install_branch: d01644f6b1a65a202160a5a65808f184d5ff8606 # HEAD as of 20.12.2020
networking_generic_switch_git_track_branch: master

networking_nsx_git_repo: https://opendev.org/x/vmware-nsx
networking_nsx_git_install_branch: 8bbeff9fb97dd638efb0a6038884c8d48adf47bd # HEAD as of 20.12.2020
networking_nsx_git_track_branch: master

networking_nsxlib_git_repo: https://opendev.org/x/vmware-nsxlib
networking_nsxlib_git_install_branch: f6f86385ae8c0dd0825fbca659ac7d0f04b5594d # HEAD as of 20.12.2020
networking_nsxlib_git_track_branch: master

## Nova service
nova_git_repo: https://opendev.org/openstack/nova
nova_git_install_branch: 0e5aa1b5e16b52d01ba017507542f8be9e5ecc3f # HEAD as of 20.12.2020
nova_git_track_branch: master


## Sahara service
sahara_git_repo: https://opendev.org/openstack/sahara
sahara_git_install_branch: b8ad624ee5e32ae244250ee9ad8cec452ca4781c # HEAD as of 20.12.2020
sahara_git_track_branch: master


## Senlin service
senlin_git_repo: https://opendev.org/openstack/senlin
senlin_git_install_branch: 5238a34c7d25c7b7a77f3c6a2f6d2c743e018978 # HEAD as of 20.12.2020
senlin_git_track_branch: master


## Swift service
swift_git_repo: https://opendev.org/openstack/swift
swift_git_install_branch: d277960161119face2eb9d617822b2645f19b2c1 # HEAD as of 20.12.2020
swift_git_track_branch: master


## Ironic service
ironic_git_repo: https://opendev.org/openstack/ironic
ironic_git_install_branch: 6c9e28dd505a19d405b5ab75500cde555b4aca8d # HEAD as of 20.12.2020
ironic_git_track_branch: master


## Ironic inspector service
ironic_inspector_git_repo: https://opendev.org/openstack/ironic-inspector
ironic_inspector_git_install_branch: c6fdf2511697305e2f00ec444081ab3353074b22 # HEAD as of 20.12.2020
ironic_inspector_git_track_branch: master


## Magnum service
magnum_git_repo: https://opendev.org/openstack/magnum
magnum_git_install_branch: dfc083d9f12df60dd64d273d1df2f7eb81d5ec07 # HEAD as of 20.12.2020
magnum_git_track_branch: master

## Masakari service
masakari_git_repo: https://opendev.org/openstack/masakari
masakari_git_install_branch: a18e3880ebb4aa42ae4d8e8f99e3ff81cece3712 # HEAD as of 20.12.2020
masakari_git_track_branch: master

## Masakari monitors services
masakari_monitors_git_repo: https://opendev.org/openstack/masakari-monitors
masakari_monitors_git_install_branch: bcf6129798a821975ab22cff56c791c81883f5da # HEAD as of 20.12.2020
masakari_monitors_git_track_branch: master

## Mistral service
mistral_git_repo: https://opendev.org/openstack/mistral
mistral_git_install_branch: b3f609d165aeea5aefc4ae4f4ca153846c6ed3c5 # HEAD as of 20.12.2020
mistral_git_track_branch: master

## Murano service
murano_git_repo: https://opendev.org/openstack/murano
murano_git_install_branch: e078063cffeab325d98025c43b7a955c53dfc78c # HEAD as of 20.12.2020
murano_git_track_branch: master

murano_dashboard_git_repo: https://opendev.org/openstack/murano-dashboard
murano_dashboard_git_install_branch: afb552342bbe73a9942e265f402b0d1392573f05 # HEAD as of 20.12.2020
murano_dashboard_git_track_branch: master

## Trove service
trove_git_repo: https://opendev.org/openstack/trove
trove_git_install_branch: 3301e2e42c8fb2e26d9db60adf001194f83ef369 # HEAD as of 20.12.2020
trove_git_track_branch: master

## Horizon Trove dashboard plugin
trove_dashboard_git_repo: https://opendev.org/openstack/trove-dashboard
trove_dashboard_git_install_branch: d0e1f82d90f1ff0ad30096faf4780e93f18f6891 # HEAD as of 20.12.2020
trove_dashboard_git_track_branch: master


## Octavia service
octavia_git_repo: https://opendev.org/openstack/octavia
octavia_git_install_branch: 1a86e454e7be22b36039a4a4bac6a886f523e9d3 # HEAD as of 20.12.2020
octavia_git_track_branch: master


## Panko service
panko_git_repo: https://opendev.org/openstack/panko
panko_git_install_branch: ac92c378b89b6dcb98193ee902b71588f50841d6 # HEAD as of 20.12.2020
panko_git_track_branch: master


## Placement service
placement_git_repo: https://opendev.org/openstack/placement
placement_git_install_branch: a0acd219378db6b156d4c14dfaf0cf947ab14e60 # HEAD as of 20.12.2020
placement_git_track_branch: master


## Tacker service
tacker_git_repo: https://opendev.org/openstack/tacker
tacker_git_install_branch: 4558f9ad37354d7f24e046f22891ed5eb43927e0 # HEAD as of 20.12.2020
tacker_git_track_branch: master


## Horizon Octavia dashboard plugin
octavia_dashboard_git_repo: https://opendev.org/openstack/octavia-dashboard
octavia_dashboard_git_install_branch: bd5f48ca185f05d203989d9bf1fc85e61f570f39 # HEAD as of 20.12.2020
octavia_dashboard_git_track_branch: master


## Blazar service
blazar_git_repo: https://opendev.org/openstack/blazar
blazar_git_install_branch: cb7c142a890e84a2b3171395832d9839b2d66a63 # HEAD as of 20.12.2020
blazar_git_track_branch: master

## Blazar Nova Service
blazar_nova_git_repo: https://opendev.org/openstack/blazar-nova
blazar_nova_git_install_branch: d399fe717b9185da06d9f3dd42117294aaf3f2cc # HEAD as of 20.12.2020
blazar_nova_git_track_branch: master

## Zun service
zun_git_repo: https://opendev.org/openstack/zun
zun_git_install_branch: 12fa7efcfef617a7112c2c017f744767c56d212a # HEAD as of 20.12.2020
zun_git_track_branch: master

## Zun kuryr service
zun_kuryr_git_repo: https://opendev.org/openstack/kuryr-libnetwork
zun_kuryr_git_install_branch: c34f977cfda2d52af86249c6234bc86469a2af5f # HEAD as of 20.12.2020
zun_kuryr_git_track_branch: master

## Zun kuryr library
zun_kuryr_lib_git_repo: https://opendev.org/openstack/kuryr
zun_kuryr_lib_git_install_branch: f9737498168abe81b442649a296e85198d96e29a # HEAD as of 20.12.2020
zun_kuryr_lib_git_track_branch: master
