---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


## NOTICE on items in this file:
##   * If you use anything in the *._git_install_branch field that is not a TAG
##     make sure to leave an in-line comment as to "why".

## For the sake of anyone else editing this file:
##   * If you add services to this file please do so in alphabetical order.
##   * Every entry should be name spaced with the name of the client followed by an "_"
##   * All items with this file should be separated by `name_` note that the name of the
##     package should be one long name with no additional `_` separating it.


### Before this is shipped all of these services should have a tag set as the branch,
### or have a comment / reason attached to them as to why a tag can not work.


## Global Requirements
requirements_git_repo: https://git.openstack.org/openstack/requirements
requirements_git_install_branch: b02483f93227843bfd55e495b76eed4a6390bb96 # HEAD of "stable/ocata" as of 31.05.2017
requirements_git_dest: "/opt/requirements_{{ requirements_git_install_branch | replace('/', '_') }}"


## Aodh service
aodh_git_repo: https://git.openstack.org/openstack/aodh
aodh_git_install_branch: 5c6b46ecc85743798c04b2d5fd094a0e9ef661a7 # HEAD of "stable/ocata" as of 31.05.2017
aodh_git_dest: "/opt/aodh_{{ aodh_git_install_branch | replace('/', '_') }}"
aodh_git_project_group: aodh_all


## Barbican service
barbican_git_repo: https://git.openstack.org/openstack/barbican
barbican_git_install_branch: b04aa152843d9cda3b11e8736e740c71fd798d0f # HEAD of "stable/ocata" as of 31.05.2017
barbican_git_dest: "/opt/barbican_{{ barbican_git_install_branch | replace('/', '_') }}"
barbican_git_project_group: barbican_all


## Ceilometer service
ceilometer_git_repo: https://git.openstack.org/openstack/ceilometer
ceilometer_git_install_branch: 1cc40682982e73c914c3f00bdf7a1ef7d03b2f31 # HEAD of "stable/ocata" as of 31.05.2017
ceilometer_git_dest: "/opt/ceilometer_{{ceilometer_git_install_branch | replace('/', '_') }}"
ceilometer_git_project_group: ceilometer_all


## Cinder service
cinder_git_repo: https://git.openstack.org/openstack/cinder
cinder_git_install_branch: bccd77a6002c04c9b7629a6eadd897ad4c33135d # HEAD of "stable/ocata" as of 31.05.2017
cinder_git_dest: "/opt/cinder_{{ cinder_git_install_branch | replace('/', '_') }}"
cinder_git_project_group: cinder_all


## Designate service
designate_git_repo: https://git.openstack.org/openstack/designate
designate_git_install_branch: 9c8bad11d9588cbf4a73a276eb5457f3e64c6a40 # HEAD of "stable/ocata" as of 31.05.2017
designate_git_dest: "/opt/designate_{{ designate_git_install_branch | replace('/', '_') }}"
designate_git_project_group: designate_all


## Horizon Designate dashboard plugin
designate_dashboard_git_repo: https://git.openstack.org/openstack/designate-dashboard
designate_dashboard_git_install_branch: fb8108354937ef6d3a1bb389481af79681f7c5b3 # HEAD of "stable/ocata" as of 31.05.2017
designate_dashboard_git_dest: "/opt/designate_dashboard_{{ designate_dashboard_git_install_branch | replace('/', '_') }}"
designate_dashboard_git_project_group: horizon_all


## Dragonflow service
dragonflow_git_repo: https://git.openstack.org/openstack/dragonflow
dragonflow_git_install_branch: b72ffa06721faf95f42c9702f60a9acc3a7d8b61 # HEAD of "stable/ocata" as of 31.05.2017
dragonflow_git_dest: "/opt/dragonflow_{{ dragonflow_git_install_branch | replace('/', '_') }}"
dragonflow_git_project_group: neutron_all


## Glance service
glance_git_repo: https://git.openstack.org/openstack/glance
glance_git_install_branch: 57c4d7d78f37e840660719b944ebabe91cbf231b # HEAD of "stable/ocata" as of 31.05.2017
glance_git_dest: "/opt/glance_{{ glance_git_install_branch | replace('/', '_') }}"
glance_git_project_group: glance_all


## Heat service
heat_git_repo: https://git.openstack.org/openstack/heat
heat_git_install_branch: d06690d72d39af3f6cf98468946ea41074220389 # HEAD of "stable/ocata" as of 31.05.2017
heat_git_dest: "/opt/heat_{{ heat_git_install_branch | replace('/', '_') }}"
heat_git_project_group: heat_all


## Horizon service
horizon_git_repo: https://git.openstack.org/openstack/horizon
horizon_git_install_branch: 3bc399f3ae34b5eb3b18544c55c65ff8a6dc7a71 # HEAD of "stable/ocata" as of 31.05.2017
horizon_git_dest: "/opt/horizon_{{ horizon_git_install_branch | replace('/', '_') }}"
horizon_git_project_group: horizon_all

## Horizon Ironic dashboard plugin
ironic_dashboard_git_repo: https://git.openstack.org/openstack/ironic-ui
ironic_dashboard_git_install_branch: 565fc3f27881467a2b0a13c72d32acd8f24a4f7a # HEAD of "stable/ocata" as of 31.05.2017
ironic_dashboard_git_dest: "/opt/ironic_dashboard_{{ ironic_dashboard_git_install_branch | replace('/', '_') }}"
ironic_dashboard_git_project_group: horizon_all

## Horizon Magnum dashboard plugin
magnum_dashboard_git_repo: https://git.openstack.org/openstack/magnum-ui
magnum_dashboard_git_install_branch: 369d3e0bf9bb562c28bb975736694b598109310a # HEAD of "stable/ocata" as of 31.05.2017
magnum_dashboard_git_dest: "/opt/magnum_dashboard_{{ magnum_dashboard_git_install_branch | replace('/', '_') }}"
magnum_dashboard_git_project_group: horizon_all

## Horizon LBaaS dashboard plugin
neutron_lbaas_dashboard_git_repo: https://git.openstack.org/openstack/neutron-lbaas-dashboard
neutron_lbaas_dashboard_git_install_branch: 834ea9dd7aeaefed397d6d510b7527ce0fa5bd33 # HEAD of "stable/ocata" as of 31.05.2017
neutron_lbaas_dashboard_git_dest: "/opt/neutron_lbaas_dashboard_{{ neutron_lbaas_dashboard_git_install_branch | replace('/', '_') }}"
neutron_lbaas_dashboard_git_project_group: horizon_all

## Horizon Sahara dashboard plugin
sahara_dashboard_git_repo: https://git.openstack.org/openstack/sahara-dashboard
sahara_dashboard_git_install_branch: 919ab93f46a2d0bf757610c09e1da3484fcdc8c0 # HEAD of "stable/ocata" as of 31.05.2017
sahara_dashboard_git_dest: "/opt/sahara_dashboard_{{ sahara_dashboard_git_install_branch | replace('/', '_') }}"
sahara_dashboard_git_project_group: horizon_all


## Keystone service
keystone_git_repo: https://git.openstack.org/openstack/keystone
keystone_git_install_branch: 736149c0cd91e66121229ed9aea8ddc90ea2eb26 # HEAD of "stable/ocata" as of 31.05.2017
keystone_git_dest: "/opt/keystone_{{ keystone_git_install_branch | replace('/', '_') }}"
keystone_git_project_group: keystone_all


## Neutron service
neutron_git_repo: https://git.openstack.org/openstack/neutron
neutron_git_install_branch: 151310cdc3efaba921a314f24df1667a71bdb348 # HEAD of "stable/ocata" as of 31.05.2017
neutron_git_dest: "/opt/neutron_{{ neutron_git_install_branch | replace('/', '_') }}"
neutron_git_project_group: neutron_all

neutron_lbaas_git_repo: https://git.openstack.org/openstack/neutron-lbaas
neutron_lbaas_git_install_branch: 47ffd1343f194f805ec203a5dc6e5844f1d038ea # HEAD of "stable/ocata" as of 31.05.2017
neutron_lbaas_git_dest: "/opt/neutron_lbaas_{{ neutron_lbaas_git_install_branch | replace('/', '_') }}"
neutron_lbaas_git_project_group: neutron_all

neutron_vpnaas_git_repo: https://git.openstack.org/openstack/neutron-vpnaas
neutron_vpnaas_git_install_branch: 6fece0ee069c5dd036b4712cfd74855844aa7f91 # HEAD of "stable/ocata" as of 31.05.2017
neutron_vpnaas_git_dest: "/opt/neutron_vpnaas_{{ neutron_vpnaas_git_install_branch | replace('/', '_') }}"
neutron_vpnaas_git_project_group: neutron_all

neutron_fwaas_git_repo: https://git.openstack.org/openstack/neutron-fwaas
neutron_fwaas_git_install_branch: e32e82de454f4f7788caade52e973662b7c85a33 # HEAD of "stable/ocata" as of 31.05.2017
neutron_fwaas_git_dest: "/opt/neutron_fwaas_{{ neutron_fwaas_git_install_branch | replace('/', '_') }}"
neutron_fwaas_git_project_group: neutron_all

neutron_dynamic_routing_git_repo: https://git.openstack.org/openstack/neutron-dynamic-routing
neutron_dynamic_routing_git_install_branch: 4b6afd41961743353400f78ddcbc4a5d34665468 # HEAD of "stable/ocata" as of 31.05.2017
neutron_dynamic_routing_git_dest: "/opt/neutron_dynamic_routing_{{ neutron_dynamic_routing_git_install_branch | replace('/', '_') }}"
neutron_dynamic_routing_git_project_group: neutron_all


## Nova service
nova_git_repo: https://git.openstack.org/openstack/nova
nova_git_install_branch: 81838f1ae910383bf0992684e6b0ef30a6d943ba # HEAD of "stable/ocata" as of 31.05.2017
nova_git_dest: "/opt/nova_{{ nova_git_install_branch | replace('/', '_') }}"
nova_git_project_group: nova_all


## PowerVM Virt Driver
nova_powervm_git_repo: https://git.openstack.org/openstack/nova-powervm
nova_powervm_git_install_branch: 7913a0807bfc7eab88bca5af05f654e316841289 # HEAD of "stable/ocata" as of 31.05.2017
nova_powervm_git_dest: "/opt/nova_powervm_{{ nova_powervm_git_install_branch | replace('/', '_') }}"
nova_powervm_git_project_group: nova_compute


## LXD Virt Driver
nova_lxd_git_repo: https://git.openstack.org/openstack/nova-lxd
nova_lxd_git_install_branch: d7b8e7013be4208c699ecde4224f03bc31d56cf8 # HEAD of "stable/ocata" as of 31.05.2017
nova_lxd_git_dest: "/opt/nova_lxd_{{ nova_lxd_git_install_branch | replace('/', '_') }}"
nova_lxd_git_project_group: nova_compute


## Sahara service
sahara_git_repo: https://git.openstack.org/openstack/sahara
sahara_git_install_branch: d38cb7693b13ed0add5ab2383a02d7b8b495fcc5 # HEAD of "stable/ocata" as of 31.05.2017
sahara_git_dest: "/opt/sahara_{{ sahara_git_install_branch | replace('/', '_') }}"
sahara_git_project_group: sahara_all


## Swift service
swift_git_repo: https://git.openstack.org/openstack/swift
swift_git_install_branch: 72ed8f23a78f11e1ca1688ba086590bb7062a8c7 # HEAD of "stable/ocata" as of 31.05.2017
swift_git_dest: "/opt/swift_{{ swift_git_install_branch | replace('/', '_') }}"
swift_git_project_group: swift_all


## Ironic service
ironic_git_repo: https://git.openstack.org/openstack/ironic
ironic_git_install_branch: bb3da02fbdd9bf8b2aa9707260a716f0469b1748 # HEAD of "stable/ocata" as of 31.05.2017
ironic_git_dest: "/opt/ironic_{{ ironic_git_install_branch | replace('/', '_') }}"
ironic_git_project_group: ironic_all

## Magnum service
magnum_git_repo: https://git.openstack.org/openstack/magnum
magnum_git_install_branch: dacadc2afd4b5675833987ca507ac16dae55996e # HEAD of "stable/ocata" as of 31.05.2017
magnum_git_dest: "/opt/magnum_{{ magnum_git_install_branch | replace('/', '_') }}"
magnum_git_project_group: magnum_all

## Trove service
trove_git_repo: https://git.openstack.org/openstack/trove
trove_git_install_branch: be4d63612f6cca2b9d8a3e3903e9e5d02314323a # HEAD of "stable/ocata" as of 31.05.2017
trove_git_dest: "/opt/trove_{{ trove_git_install_branch | replace('/', '_') }}"
trove_git_project_group: trove_all

## Horizon Trove dashboard plugin
trove_dashboard_git_repo: https://git.openstack.org/openstack/trove-dashboard
trove_dashboard_git_install_branch: e88344200a0b3e03f644a98723ff5fa1b670df7a # HEAD of "stable/ocata" as of 31.05.2017
trove_dashboard_git_dest: "/opt/trove_dashboard_{{ trove_dashboard_git_install_branch | replace('/', '_') }}"
trove_dashboard_git_project_group: horizon_all
