---
# Copyright 2018, Jean-Philippe Evrard <jean-philippe@evrard.me>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

### HEAD as of 23.06.2022 ###

tempest_git_repo: https://opendev.org/openstack/tempest
tempest_git_install_branch: 7559bb649e11377c8cba4e7a6129025a7d3d5d06
tempest_git_track_branch: master

tempest_plugin_barbican_git_repo: https://opendev.org/openstack/barbican-tempest-plugin
tempest_plugin_barbican_git_install_branch: 11c8cfae0ce85b874ab055e685accba85f460fda
tempest_plugin_barbican_git_track_branch: master

tempest_plugin_cinder_git_repo: https://opendev.org/openstack/cinder-tempest-plugin
tempest_plugin_cinder_git_install_branch: 141dace60e5e4d14bf39b65872a4c9db63ba8df4
tempest_plugin_cinder_git_track_branch: master

tempest_plugin_cloudkitty_git_repo: https://opendev.org/openstack/cloudkitty-tempest-plugin
tempest_plugin_cloudkitty_git_install_branch: 97cd523c437246033ed38ffe6ec7f545abe20d7f
tempest_plugin_cloudkitty_git_track_branch: master

tempest_plugin_designate_git_repo: https://opendev.org/openstack/designate-tempest-plugin
tempest_plugin_designate_git_install_branch: 6d5e0a1406070667f97718e98dfe21dbc95b3d98
tempest_plugin_designate_git_track_branch: master

tempest_plugin_heat_git_repo: https://opendev.org/openstack/heat-tempest-plugin
tempest_plugin_heat_git_install_branch: ba43685c131d6387779ed35f5bf61fc86667a728
tempest_plugin_heat_git_track_branch: master

tempest_plugin_ironic_git_repo: https://opendev.org/openstack/ironic-tempest-plugin
tempest_plugin_ironic_git_install_branch: 3af6253bc96ba1897feb0a88e60bddd0097d05ff
tempest_plugin_ironic_git_track_branch: master

tempest_plugin_keystone_git_repo: https://opendev.org/openstack/keystone-tempest-plugin
tempest_plugin_keystone_git_install_branch: 4eff632695fe79a5d78f400dca3ceab663c83788
tempest_plugin_keystone_git_track_branch: master

tempest_plugin_magnum_git_repo: https://opendev.org/openstack/magnum-tempest-plugin
tempest_plugin_magnum_git_install_branch: 70d8e4551409c712f4a1e523566951da72e1871c
tempest_plugin_magnum_git_track_branch: master

tempest_plugin_manila_git_repo: https://opendev.org/openstack/manila-tempest-plugin
tempest_plugin_manila_git_install_branch: b31d6efb21cfec92fed899a1eec1cb5de30c737b
tempest_plugin_manila_git_track_branch: master

tempest_plugin_murano_git_repo: https://opendev.org/openstack/murano-tempest-plugin
tempest_plugin_murano_git_install_branch: 97d430bbe105b204960cddd9d587d11cf1f9b2ca
tempest_plugin_murano_git_track_branch: master

tempest_plugin_neutron_git_repo: https://opendev.org/openstack/neutron-tempest-plugin
tempest_plugin_neutron_git_install_branch: 318ec127c548d4f3cba1ceb9edb11c5d250b1786
tempest_plugin_neutron_git_track_branch: master

tempest_plugin_novajoin_git_repo: https://opendev.org/x/novajoin-tempest-plugin
tempest_plugin_novajoin_git_install_branch: b2e548518a8893562ed111fe66f5937603f5ec5d
tempest_plugin_novajoin_git_track_branch: master

tempest_plugin_octavia_git_repo: https://opendev.org/openstack/octavia-tempest-plugin
tempest_plugin_octavia_git_install_branch: 1aeccba999a15e2e71feb520c233dd19299e6905
tempest_plugin_octavia_git_track_branch: master

tempest_plugin_senlin_git_repo: https://opendev.org/openstack/senlin-tempest-plugin
tempest_plugin_senlin_git_install_branch: 7a8121fc5f51f17f9f56a7d73739ed4378ba264f
tempest_plugin_senlin_git_track_branch: master

tempest_plugin_sahara_git_repo: https://opendev.org/openstack/sahara-tests
tempest_plugin_sahara_git_install_branch: 98063d3fd93ce77cb3ecbbd33868bbe5dd3a6865
tempest_plugin_sahara_git_track_branch: master

tempest_plugin_telemetry_git_repo: https://opendev.org/openstack/telemetry-tempest-plugin
tempest_plugin_telemetry_git_install_branch: e5ef4e7c6eeeada174452da9be5f56fa1dcc22a9
tempest_plugin_telemetry_git_track_branch: master

tempest_plugin_trove_git_repo: https://opendev.org/openstack/trove-tempest-plugin
tempest_plugin_trove_git_install_branch: 5de39645ed4c5f12526863d1546769dce74fcb08
tempest_plugin_trove_git_track_branch: master

tempest_plugin_zaqar_git_repo: https://opendev.org/openstack/zaqar-tempest-plugin
tempest_plugin_zaqar_git_install_branch: 3813c99e501a1f67a9cbde751cf71747a61f6786
tempest_plugin_zaqar_git_track_branch: master

tempest_plugin_zun_git_repo: https://opendev.org/openstack/zun-tempest-plugin
tempest_plugin_zun_git_install_branch: c6b830885c15ed40e9e5436c88c72d32e754beae
tempest_plugin_zun_git_track_branch: master

rally_openstack_git_repo: https://opendev.org/openstack/rally-openstack
rally_openstack_git_install_branch: 3984f97c1c9fd0695bab123da81323e83abac3a3
rally_openstack_git_track_branch: master

