---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


## NOTICE on items in this file:
##   * If you use anything in the *._git_install_branch field that is not a TAG
##     make sure to leave an in-line comment as to "why".

## For the sake of anyone else editing this file:
##   * If you add services to this file please do so in alphabetical order.
##   * Every entry should be name spaced with the name of the client followed by an "_"
##   * All items with this file should be separated by `name_` note that the name of the
##     package should be one long name with no additional `_` separating it.


### Before this is shipped all of these services should have a tag set as the branch,
### or have a comment / reason attached to them as to why a tag can not work.

## Cinder service
cinder_git_repo: https://github.com/openstack/cinder
cinder_git_install_branch: 6c055943e70675585ef45301318c47ccc1139ce9 # HEAD of "stable/kilo" as of 07.07.2015
cinder_git_dest: "/opt/cinder_{{ cinder_git_install_branch | replace('/', '_') }}"


## Glance service
glance_git_repo: https://github.com/openstack/glance
glance_git_install_branch: d1f54b71b863c2505ce31898f769a71624016e67 # HEAD of "stable/kilo" as of 07.07.2015
glance_git_dest: "/opt/glance_{{ glance_git_install_branch | replace('/', '_') }}"


## Heat service
heat_git_repo: https://github.com/openstack/heat
heat_git_install_branch: 6880594b7951e2fd00f8f705cefcc3c7e0925460 # HEAD of "stable/kilo" as of 07.07.2015
heat_git_dest: "/opt/heat_{{ heat_git_install_branch | replace('/', '_') }}"
# The version of PBR >= 0.11.0 breaks this plugin (contrib package) so the package has been removed
# from the build process until the PBR issues are resolve upstream which is related to all of the
# services transitioning to Liberty. Note that the package will still be available as its presently
# part of the upstream index as found here: http://rpc-repo.rackspace.com/pools/heat_contrib_extraroute/
# BUG: https://bugs.launchpad.net/openstack-ansible/+bug/1450733
# TODO(cloudnull) Re-enable this plugin once the build issues are resolved upstream.
# heat_repo_plugins:
#   - { path: "contrib", package: "extraroute" }


## Horizon service
horizon_git_repo: https://github.com/openstack/horizon
horizon_git_install_branch: 2cc2495c68e341cdc95617bdb4b64a7597d80c28 # HEAD of "stable/kilo" as of 07.07.2015
horizon_git_dest: "/opt/horizon_{{ horizon_git_install_branch | replace('/', '_') }}"


## Keystone service
keystone_git_repo: https://github.com/openstack/keystone
keystone_git_install_branch: 8125a8913d233f3da0eaacd09aa8e0b794ea98cb # HEAD of "stable/kilo" as of 07.07.2015
keystone_git_dest: "/opt/keystone_{{ keystone_git_install_branch | replace('/', '_') }}"


## Neutron service
neutron_git_repo: https://github.com/openstack/neutron
neutron_git_install_branch: 8e82dc7eaa15e14bd95dde884f4d99919e6bb19c # HEAD of "stable/kilo" as of 07.07.2015
neutron_git_dest: "/opt/neutron_{{ neutron_git_install_branch | replace('/', '_') }}"

neutron_lbaas_git_repo: https://github.com/openstack/neutron-lbaas
neutron_lbaas_git_install_branch: 4ab10135f2571727689ad74000a419c00977bef8 # HEAD of "stable/kilo" as of 07.07.2015
neutron_lbaas_git_dest: "/opt/neutron_lbaas_{{ neutron_lbaas_git_install_branch | replace('/', '_') }}"

neutron_vpnaas_git_repo: https://github.com/openstack/neutron-vpnaas
neutron_vpnaas_git_install_branch: c61c0437307b9d7076d8ef0fb98bcdb890278979 # HEAD of "stable/kilo" as of 07.07.2015
neutron_vpnaas_git_dest: "/opt/neutron_vpnaas_{{ neutron_vpnaas_git_install_branch | replace('/', '_') }}"

neutron_fwaas_git_repo: https://github.com/openstack/neutron-fwaas
neutron_fwaas_git_install_branch: aeca0b89c0091723cf0aeb7fc4749bb3c3ef39e7 # HEAD of "stable/kilo" as of 07.07.2015
neutron_fwaas_git_dest: "/opt/neutron_fwaas_{{ neutron_fwaas_git_install_branch | replace('/', '_') }}"


## Nova service
nova_git_repo: https://github.com/openstack/nova
nova_git_install_branch: b8c4f1bce356838dd3dac3b59734cf47f72373e5 # HEAD of "stable/kilo" as of 07.07.2015
nova_git_dest: "/opt/nova_{{ nova_git_install_branch | replace('/', '_') }}"


## Swift service
swift_git_repo: https://github.com/openstack/swift
swift_git_install_branch: fe4cdb597f70e40c667b001b446546d75a7a5ab0 # HEAD of "stable/kilo" as of 07.07.2015
swift_git_dest: "/opt/swift_{{ swift_git_install_branch | replace('/', '_') }}"


## Tempest service
tempest_git_repo: https://github.com/openstack/tempest
tempest_git_install_branch: 9927d643c7340cc55a351cc8ed159d7dd3ba0c54 # HEAD of "master" as of 08.06.2015
tempest_git_install_fragments: "yaprtignorerequirements=true"
tempest_git_dest: "/opt/tempest_{{ tempest_git_install_branch | replace('/', '_') }}"
