---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


## NOTICE on items in this file:
##   * If you use anything in the *._git_install_branch field that is not a TAG
##     make sure to leave an in-line comment as to "why".

## For the sake of anyone else editing this file:
##   * If you add services to this file please do so in alphabetical order.
##   * Every entry should be name spaced with the name of the client followed by an "_"
##   * All items with this file should be separated by `name_` note that the name of the
##     package should be one long name with no additional `_` separating it.


### Before this is shipped all of these services should have a tag set as the branch,
### or have a comment / reason attached to them as to why a tag can not work.


## Global Requirements
requirements_git_repo: https://git.openstack.org/openstack/requirements
requirements_git_install_branch: 27bd6f6c29125487e864d00339f67e6e0358a836 # HEAD as of 09.03.2019
requirements_git_track_branch: master


## Aodh service
aodh_git_repo: https://git.openstack.org/openstack/aodh
aodh_git_install_branch: 1b552dd82565157c123925adecd12fc279cbbee0 # HEAD as of 09.03.2019
aodh_git_project_group: aodh_all
aodh_git_track_branch: master


## Barbican service
barbican_git_repo: https://git.openstack.org/openstack/barbican
barbican_git_install_branch: 4c0ddda941289fba8e5ec4341b5d02d155d46162 # HEAD as of 09.03.2019
barbican_git_project_group: barbican_all
barbican_git_track_branch: master


## Ceilometer service
ceilometer_git_repo: https://git.openstack.org/openstack/ceilometer
ceilometer_git_install_branch: 062e02c612d1fdd8c40b9209319b32e04489c163 # HEAD as of 09.03.2019
ceilometer_git_project_group: all
ceilometer_git_track_branch: master


## Cinder service
cinder_git_repo: https://git.openstack.org/openstack/cinder
cinder_git_install_branch: 5d6814de4f64b543683c606f1806ee711e739b5c # HEAD as of 09.03.2019
cinder_git_project_group: cinder_all
cinder_git_track_branch: master


## Designate service
designate_git_repo: https://git.openstack.org/openstack/designate
designate_git_install_branch: 46d167aec910926bb650cca23ac62555e0ccf44d # HEAD as of 09.03.2019
designate_git_project_group: designate_all
designate_git_track_branch: master


## Horizon Designate dashboard plugin
designate_dashboard_git_repo: https://git.openstack.org/openstack/designate-dashboard
designate_dashboard_git_install_branch: 6f00fcb31b8c91795dc7b05c57f6577fbd522b31 # HEAD as of 09.03.2019
designate_dashboard_git_project_group: horizon_all
designate_dashboard_git_track_branch: master


## Glance service
glance_git_repo: https://git.openstack.org/openstack/glance
glance_git_install_branch: 0350fa63715952ea1739e850f027cd1c5d2006ed # HEAD as of 09.03.2019
glance_git_project_group: glance_all
glance_git_track_branch: master


## Heat service
heat_git_repo: https://git.openstack.org/openstack/heat
heat_git_install_branch: 31b19b2139dcc94df5ccf360b60b53d9c909698c # HEAD as of 09.03.2019
heat_git_package_name: openstack-heat
heat_git_project_group: heat_all
heat_git_track_branch: master

## Horizon Heat dashboard plugin
heat_dashboard_git_repo: https://git.openstack.org/openstack/heat-dashboard
heat_dashboard_git_install_branch: e4a8ab4a11b4efcfb25c4c9f36209ecf42db464a # HEAD as of 09.03.2019
heat_dashboard_git_project_group: horizon_all
heat_dashboard_git_track_branch: master

## Horizon service
horizon_git_repo: https://git.openstack.org/openstack/horizon
horizon_git_install_branch: 782cb2f22d4f410f6c8b8b5f6fa88ec7687bda49 # HEAD as of 09.03.2019
horizon_git_project_group: horizon_all
horizon_git_track_branch: master

## Horizon Ironic dashboard plugin
ironic_dashboard_git_repo: https://git.openstack.org/openstack/ironic-ui
ironic_dashboard_git_install_branch: 97bdc1823ca8158cddb003d3718c9475897587da # HEAD as of 09.03.2019
ironic_dashboard_git_project_group: horizon_all
ironic_dashboard_git_track_branch: master

## Horizon Magnum dashboard plugin
magnum_dashboard_git_repo: https://git.openstack.org/openstack/magnum-ui
magnum_dashboard_git_install_branch: 74a312d6edebbb95d5493fd061d82ea010f16204 # HEAD as of 09.03.2019
magnum_dashboard_git_project_group: horizon_all
magnum_dashboard_git_track_branch: master

## Horizon Masakari dashboard plugin
masakari_dashboard_git_repo: https://git.openstack.org/openstack/masakari-dashboard
masakari_dashboard_git_install_branch: d3b34063a19d7ecd598bafbcd0e60dd9a5f13136 # HEAD as of 09.03.2019
masakari_dashboard_git_project_group: horizon_all
masakari_dashboard_git_track_branch: master

## Horizon LBaaS dashboard plugin
neutron_lbaas_dashboard_git_repo: https://git.openstack.org/openstack/neutron-lbaas-dashboard
neutron_lbaas_dashboard_git_install_branch: 0c03857b1cd25eaf5b4cb295fa1c8385974b6c2a # HEAD as of 09.03.2019
neutron_lbaas_dashboard_git_project_group: horizon_all
neutron_lbaas_dashboard_git_track_branch: master

## Horizon FWaaS dashboard plugin
neutron_fwaas_dashboard_git_repo: https://git.openstack.org//openstack/neutron-fwaas-dashboard
neutron_fwaas_dashboard_git_install_branch: ca3d27b57ecf109b23c22d8cd48cca3265b5b6f4 # HEAD as of 09.03.2019
neutron_fwaas_dashboard_git_project_group: horizon_all
neutron_fwaas_dashboard_git_track_branch: master

## Horizon Sahara dashboard plugin
sahara_dashboard_git_repo: https://git.openstack.org/openstack/sahara-dashboard
sahara_dashboard_git_install_branch: 65961853cc06604cea5a80f17631e267ce44202c # HEAD as of 09.03.2019
sahara_dashboard_git_project_group: horizon_all
sahara_dashboard_git_track_branch: master


## Keystone service
keystone_git_repo: https://git.openstack.org/openstack/keystone
keystone_git_install_branch: ed458833809041754f17430f7b8940dde6cf0826 # HEAD as of 09.03.2019
keystone_git_project_group: keystone_all
keystone_git_track_branch: master


## Neutron service
neutron_git_repo: https://git.openstack.org/openstack/neutron
neutron_git_install_branch: 8d3182c45a7de925d267ff5a8b5484dcbe0f39fb # HEAD as of 09.03.2019
neutron_git_project_group: neutron_all
neutron_git_track_branch: master

neutron_lbaas_git_repo: https://git.openstack.org/openstack/neutron-lbaas
neutron_lbaas_git_install_branch: 2552fb1e5dccb483d21f9e329ebec6462eebdb94  # HEAD as of 09.03.2019
neutron_lbaas_git_project_group: neutron_all
neutron_lbaas_git_track_branch: master

neutron_vpnaas_git_repo: https://git.openstack.org/openstack/neutron-vpnaas
neutron_vpnaas_git_install_branch: acf8d1948570a2092629b5ee97d418e9153b3877  # HEAD as of 09.03.2019
neutron_vpnaas_git_project_group: neutron_all
neutron_vpnaas_git_track_branch: master

neutron_fwaas_git_repo: https://git.openstack.org/openstack/neutron-fwaas
neutron_fwaas_git_install_branch: 2860abca27ecd90eaf552490250a46e0f6816846  # HEAD as of 09.03.2019
neutron_fwaas_git_project_group: neutron_all
neutron_fwaas_git_track_branch: master

neutron_dynamic_routing_git_repo: https://git.openstack.org/openstack/neutron-dynamic-routing
neutron_dynamic_routing_git_install_branch: 69e9888b0159ba3c9af09e1eceb48df76e4be839  # HEAD as of 09.03.2019
neutron_dynamic_routing_git_project_group: neutron_all
neutron_dynamic_routing_git_track_branch: master

networking_calico_git_repo: https://git.openstack.org/openstack/networking-calico
networking_calico_git_install_branch: 3c9f3897c7aee6156cddd337975f95d17fb9b4fd  # HEAD as of 09.03.2019
networking_calico_git_project_group: neutron_all
networking_calico_git_track_branch: master

networking_odl_git_repo: https://git.openstack.org/openstack/networking-odl
networking_odl_git_install_branch: 10962b1a48f7ce2d363f3775cf6ff0224942a1fd  # HEAD as of 09.03.2019
networking_odl_git_project_group: neutron_all
networking_odl_git_track_branch: master

networking_ovn_git_repo: https://git.openstack.org/openstack/networking-ovn
networking_ovn_git_install_branch: 9df67005cee8a2341a252073e60979c573e7a4a6  # HEAD as of 09.03.2019
networking_ovn_git_project_group: neutron_all
networking_ovn_git_track_branch: master

# BGPVPN is frozen until further notice due to
# https://github.com/openstack/networking-bgpvpn/commit/e9a0ea199b47f76f69545e04bdb4db44869c388b#diff-b4ef698db8ca845e5845c4618278f29a
networking_bgpvpn_git_repo: https://git.openstack.org/openstack/networking-bgpvpn
networking_bgpvpn_git_install_branch: 3b93ddacd390d92fb144e5660324d4da064ad9a4 # FROZEN HEAD of "master" as of 31.03.2018
networking_bgpvpn_git_project_group: neutron_all
networking_bgpvpn_git_track_branch: None

networking_sfc_git_repo: https://git.openstack.org/openstack/networking-sfc
networking_sfc_git_install_branch: 5ea96a1c85710fb24f860267042fd52e64b59c87  # HEAD as of 09.03.2019
networking_sfc_git_project_group: neutron_all
networking_sfc_git_track_branch: master


## Nova service
nova_git_repo: https://git.openstack.org/openstack/nova
nova_git_install_branch: 30550d3d947e13f4d23b207ff96373971710dd55 # HEAD as of 09.03.2019
nova_git_project_group: nova_all
nova_git_track_branch: master


## PowerVM Virt Driver
nova_powervm_git_repo: https://git.openstack.org/openstack/nova-powervm
nova_powervm_git_install_branch: b3e195041d710135e53e51d17c0b007ea865d850 # HEAD as of 09.03.2019
nova_powervm_git_project_group: nova_all
nova_powervm_git_track_branch: master


## LXD Virt Driver
nova_lxd_git_repo: https://git.openstack.org/openstack/nova-lxd
nova_lxd_git_install_branch: 3c01bfcb7e38b5fe3f274c97a4c5d4b7e9d4299c # HEAD as of 09.03.2019
nova_lxd_git_project_group: nova_all
nova_lxd_git_track_branch: master


## Sahara service
sahara_git_repo: https://git.openstack.org/openstack/sahara
sahara_git_install_branch: b95503f38f8a9b8333c864446dca90e104075059 # HEAD as of 09.03.2019
sahara_git_project_group: sahara_all
sahara_git_track_branch: master


## Swift service
swift_git_repo: https://git.openstack.org/openstack/swift
swift_git_install_branch: 4b180dec81ab907a09a90f8fdc9411a4797be4ef # HEAD as of 09.03.2019
swift_git_project_group: swift_all
swift_git_track_branch: master


## Swift3 middleware
swift_swift3_git_repo: https://git.openstack.org/openstack/swift3
swift_swift3_git_install_branch: 90db5d1510b2a770387961e7bf0fbeae8101ba45 # HEAD as of 09.03.2019
swift_swift3_git_project_group: swift_all
swift_swift3_git_track_branch: master


## Ironic service
ironic_git_repo: https://git.openstack.org/openstack/ironic
ironic_git_install_branch: 02df7f7288202015985a269b97fe4438009c37a4 # HEAD as of 09.03.2019
ironic_git_project_group: ironic_all
ironic_git_track_branch: master


## Magnum service
magnum_git_repo: https://git.openstack.org/openstack/magnum
magnum_git_install_branch: 2595fda3e37372df4061d78b52a85071e28ebfe1 # HEAD as of 09.03.2019
magnum_git_project_group: magnum_all
magnum_git_track_branch: master

## Mistral service
mistral_git_repo: https://git.openstack.org/openstack/mistral
mistral_git_install_branch: 608367f28d10decb0e22a8fe7a58b5c38782a1e9 # HEAD as of 26.02.2019
mistral_git_project_group: mistral_all
mistral_git_track_branch: master

## Trove service
trove_git_repo: https://git.openstack.org/openstack/trove
trove_git_install_branch: 75784f94b1411a325ab3bdff4c71d2e5aa2abc2b # HEAD as of 09.03.2019
trove_git_project_group: trove_all
trove_git_track_branch: master

## Horizon Trove dashboard plugin
trove_dashboard_git_repo: https://git.openstack.org/openstack/trove-dashboard
trove_dashboard_git_install_branch: cc11fc13ee1d1a1688031de9145025afe06ccbce # HEAD as of 09.03.2019
trove_dashboard_git_project_group: horizon_all
trove_dashboard_git_track_branch: master


## Octavia service
octavia_git_repo: https://git.openstack.org/openstack/octavia
octavia_git_install_branch: ff1a4761be18fb0f8dc54c408d9b6487d43fbcbd # HEAD as of 09.03.2019
octavia_git_project_group: octavia_all
octavia_git_track_branch: master


## Tacker service
tacker_git_repo: https://git.openstack.org/openstack/tacker
tacker_git_install_branch: 1d7cd6f6041ad5924bf522b959559bdf38bb7b13 # HEAD as of 09.03.2019
tacker_git_project_group: tacker_all
tacker_git_track_branch: master

## Congress service
congress_git_repo: https://git.openstack.org/openstack/congress
congress_git_install_branch: e84057a6f5e55792803a932e5a6390069aed013e # HEAD as of 09.03.2019
congress_git_project_group: congress_all
congress_git_track_branch: master

## Horizon Octavia dashboard plugin
octavia_dashboard_git_repo: https://git.openstack.org/openstack/octavia-dashboard
octavia_dashboard_git_install_branch: 9422dec8f07a2b9ede2f521c0b7e8f1090b0571a # HEAD as of 09.03.2019
octavia_dashboard_git_project_group: horizon_all
octavia_dashboard_git_track_branch: master


## Blazar service
blazar_git_repo: https://git.openstack.org/openstack/blazar
blazar_git_install_branch: ff86014fa1c1a699d997044d5f4160593475f03a # HEAD as of 09.03.2019
blazar_git_project_group: blazar_all
blazar_git_track_branch: master

## Blazar Nova Service
blazar_nova_git_repo: https://git.openstack.org/openstack/blazar-nova
blazar_nova_git_install_branch: 1fdb0eabdae270cda12c35a829867d52a7250d28 # HEAD as of 09.03.2019
blazar_nova_git_project_group: blazar_all
blazar_nova_git_track_branch: master
