---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


## NOTICE on items in this file:
##   * If you use anything in the *._git_install_branch field that is not a TAG
##     make sure to leave an in-line comment as to "why".

## For the sake of anyone else editing this file:
##   * If you add services to this file please do so in alphabetical order.
##   * Every entry should be name spaced with the name of the client followed by an "_"
##   * All items with this file should be separated by `name_` note that the name of the
##     package should be one long name with no additional `_` separating it.


### Before this is shipped all of these services should have a tag set as the branch,
### or have a comment / reason attached to them as to why a tag can not work.


## Global Requirements
requirements_git_repo: https://opendev.org/openstack/requirements
requirements_git_install_branch: d429bb89c5f00fb8939d016dd9eec21689c32782 # HEAD as of 14.06.2020
requirements_git_track_branch: master


## Aodh service
aodh_git_repo: https://opendev.org/openstack/aodh
aodh_git_install_branch: 932b1e0e6102fada52c9a1a4f7f87d5925d71bca  # HEAD as of 14.06.2020
aodh_git_project_group: aodh_all
aodh_git_track_branch: master


## Barbican service
barbican_git_repo: https://opendev.org/openstack/barbican
barbican_git_install_branch: 87ba19b78bee7b885321f2431ebee32f0eaace91  # HEAD as of 14.06.2020
barbican_git_project_group: barbican_all
barbican_git_track_branch: master


## Ceilometer service
ceilometer_git_repo: https://opendev.org/openstack/ceilometer
ceilometer_git_install_branch: 52f6f13331269a89ba45dff7199bbd66dc3e3db0  # HEAD as of 14.06.2020
ceilometer_git_project_group: all
ceilometer_git_track_branch: master


## Cinder service
cinder_git_repo: https://opendev.org/openstack/cinder
cinder_git_install_branch: d1ef0edd05285ca4ad1e5e31b7a2cf5063b2ec4c  # HEAD as of 14.06.2020
cinder_git_project_group: cinder_all
cinder_git_track_branch: master


## Designate service
designate_git_repo: https://opendev.org/openstack/designate
designate_git_install_branch: 7869cc9df017a58514f3508830c6a71d2d875ad1  # HEAD as of 14.06.2020
designate_git_project_group: designate_all
designate_git_track_branch: master


## Horizon Designate dashboard plugin
designate_dashboard_git_repo: https://opendev.org/openstack/designate-dashboard
designate_dashboard_git_install_branch: 311ae36d6ce74ebce7a54f64d0eb5bada3200dcf  # HEAD as of 14.06.2020
designate_dashboard_git_project_group: horizon_all
designate_dashboard_git_track_branch: master


## Glance service
glance_git_repo: https://opendev.org/openstack/glance
glance_git_install_branch: 781da9354ff0bcd3c22cbe0dc5beb5f204d91769  # HEAD as of 14.06.2020
glance_git_project_group: glance_all
glance_git_track_branch: master


## Heat service
heat_git_repo: https://opendev.org/openstack/heat
heat_git_install_branch: d0e44ded0a07cfe6b3413693d79c7f1f67b27701  # HEAD as of 14.06.2020
heat_git_package_name: openstack-heat
heat_git_project_group: heat_all
heat_git_track_branch: master

## Horizon Heat dashboard plugin
heat_dashboard_git_repo: https://opendev.org/openstack/heat-dashboard
heat_dashboard_git_install_branch: e1e9fc853b72c2770ba041c0ac1151b4c9484f36  # HEAD as of 14.06.2020
heat_dashboard_git_project_group: horizon_all
heat_dashboard_git_track_branch: master

## Horizon service
horizon_git_repo: https://opendev.org/openstack/horizon
horizon_git_install_branch: dd62fd386e0899ff84cdf9418c63f98caf66cf33  # HEAD as of 14.06.2020
horizon_git_project_group: horizon_all
horizon_git_track_branch: master

## Horizon Ironic dashboard plugin
ironic_dashboard_git_repo: https://opendev.org/openstack/ironic-ui
ironic_dashboard_git_install_branch: 50134dc769a666b29ba55e377d7b1bfc4af94489  # HEAD as of 14.06.2020
ironic_dashboard_git_project_group: horizon_all
ironic_dashboard_git_track_branch: master

## Horizon Magnum dashboard plugin
magnum_dashboard_git_repo: https://opendev.org/openstack/magnum-ui
magnum_dashboard_git_install_branch: 8b3bf823f6f40d80a86b2f23cee0182f9ff262c5  # HEAD as of 14.06.2020
magnum_dashboard_git_project_group: horizon_all
magnum_dashboard_git_track_branch: master

## Horizon Masakari dashboard plugin
masakari_dashboard_git_repo: https://opendev.org/openstack/masakari-dashboard
masakari_dashboard_git_install_branch: 31fe6d75445410efb0336b2ad71a4ac29c3eba8a  # HEAD as of 14.06.2020
masakari_dashboard_git_project_group: horizon_all
masakari_dashboard_git_track_branch: master

## Horizon FWaaS dashboard plugin
neutron_fwaas_dashboard_git_repo: https://opendev.org/openstack/neutron-fwaas-dashboard
neutron_fwaas_dashboard_git_install_branch: 6451d3dbffd821a5e0e073006951c208e074aaa4  # HEAD as of 14.06.2020
neutron_fwaas_dashboard_git_project_group: horizon_all
neutron_fwaas_dashboard_git_track_branch: master

## Horizon Sahara dashboard plugin
sahara_dashboard_git_repo: https://opendev.org/openstack/sahara-dashboard
sahara_dashboard_git_install_branch: 08d4d8e6534bf110c6e66702b58a78b41f6e6db5 # HEAD as of 14.06.2020
sahara_dashboard_git_project_group: horizon_all
sahara_dashboard_git_track_branch: master


## Keystone service
keystone_git_repo: https://opendev.org/openstack/keystone
keystone_git_install_branch: c27c9d258db6f6c5d5865bd2beae3b9680effa5d  # HEAD as of 14.06.2020
keystone_git_project_group: keystone_all
keystone_git_track_branch: master


## Manila service
manila_git_repo: https://opendev.org/openstack/manila
manila_git_install_branch: 6651f675e255e43bdf6393af59873b821ebacf52  # HEAD as of 14.06.2020
manila_git_project_group: manila_all
manila_git_track_branch: master


## Neutron service
neutron_git_repo: https://opendev.org/openstack/neutron
neutron_git_install_branch: 7d8f400791707e5db7839dcdf3ef4dbbd1dd39bc  # HEAD as of 14.06.2020
neutron_git_project_group: neutron_all
neutron_git_track_branch: master

neutron_vpnaas_git_repo: https://opendev.org/openstack/neutron-vpnaas
neutron_vpnaas_git_install_branch: d18958bf72f4210da7718b86737259f495fdd0ab  # HEAD as of 14.06.2020
neutron_vpnaas_git_project_group: neutron_all
neutron_vpnaas_git_track_branch: master

neutron_fwaas_git_repo: https://opendev.org/openstack/neutron-fwaas
neutron_fwaas_git_install_branch: 94c0d54ded5006174ca9623a21ff8b3e995caa03  # HEAD as of 14.06.2020
neutron_fwaas_git_project_group: neutron_all
neutron_fwaas_git_track_branch: master

neutron_dynamic_routing_git_repo: https://opendev.org/openstack/neutron-dynamic-routing
neutron_dynamic_routing_git_install_branch: a728d2271d955364e4a14b6d0a3c6af7bc8a40be  # HEAD as of 14.06.2020
neutron_dynamic_routing_git_project_group: neutron_all
neutron_dynamic_routing_git_track_branch: master

# Networking calico follows master
networking_calico_git_repo: https://github.com/projectcalico/networking-calico
networking_calico_git_install_branch: v3.14.0  # HEAD as of 19.05.2020
networking_calico_git_project_group: neutron_all
networking_calico_git_track_branch: None

networking_odl_git_repo: https://opendev.org/openstack/networking-odl
networking_odl_git_install_branch: 6253d8baa44c3293ee070f59c184dd7322d59947  # HEAD as of 14.06.2020
networking_odl_git_project_group: neutron_all
networking_odl_git_track_branch: master

networking_bgpvpn_git_repo: https://opendev.org/openstack/networking-bgpvpn
networking_bgpvpn_git_install_branch: 82af96f02357c637717739fcc20fc64ec6ebf522  # HEAD as of 14.06.2020
networking_bgpvpn_git_project_group: neutron_all
networking_bgpvpn_git_track_branch: master

networking_sfc_git_repo: https://opendev.org/openstack/networking-sfc
networking_sfc_git_install_branch: 211e515630d2695c3a48a7ba6212a22f312bb3bc  # HEAD as of 14.06.2020
networking_sfc_git_project_group: neutron_all
networking_sfc_git_track_branch: master


## Nova service
nova_git_repo: https://opendev.org/openstack/nova
nova_git_install_branch: a9e0b0573da65074db686ceb0c5cc000ec7110f1  # HEAD as of 14.06.2020
nova_git_project_group: nova_all
nova_git_track_branch: master


## Sahara service
sahara_git_repo: https://opendev.org/openstack/sahara
sahara_git_install_branch: 81bae85a9a5457a2c74a528d9501f998013d0197 # HEAD as of 14.06.2020
sahara_git_project_group: sahara_all
sahara_git_track_branch: master


## Swift service
swift_git_repo: https://opendev.org/openstack/swift
swift_git_install_branch: 0bed59e3faae94b96f98bbbc61b09abe54453267 # HEAD as of 14.06.2020
swift_git_project_group: swift_all
swift_git_track_branch: master


## Ironic service
ironic_git_repo: https://opendev.org/openstack/ironic
ironic_git_install_branch: 15f0dc93df6f03303f3ab3813d48fbb7da8ac0a2  # HEAD as of 14.06.2020
ironic_git_project_group: ironic_all
ironic_git_track_branch: master


## Magnum service
magnum_git_repo: https://opendev.org/openstack/magnum
magnum_git_install_branch: caf687494432cf8a93a17302aa7cd7e253b8622b  # HEAD as of 14.06.2020
magnum_git_project_group: magnum_all
magnum_git_track_branch: master

## Masakari service
masakari_git_repo: https://opendev.org/openstack/masakari
masakari_git_install_branch: f590fa1ba1976bc3e9c828a46083ff827583ebde  # HEAD as of 14.06.2020
masakari_git_project_group: masakari_api
masakari_git_track_branch: master

## Masakari monitors services
masakari_monitors_git_repo: https://opendev.org/openstack/masakari-monitors
masakari_monitors_git_install_branch: be1173e853cb4548cdc33d5d5c5ef98c0cbbc28a  # HEAD as of 14.06.2020
masakari_monitors_git_project_group: masakari_monitor
masakari_monitors_git_track_branch: master

## Mistral service
mistral_git_repo: https://opendev.org/openstack/mistral
mistral_git_install_branch: d0d75be7cbeca4b4445b0799f196feb5ddeb6b1b  # HEAD as of 14.06.2020
mistral_git_project_group: mistral_all
mistral_git_track_branch: master

## Murano service
murano_git_repo: https://opendev.org/openstack/murano
murano_git_install_branch: aac7c6b80e56c2561da4b2f2e9d4b0c358e83ad4  # HEAD as of 14.06.2020
murano_git_project_group: murano_all
murano_git_track_branch: master

## Trove service
trove_git_repo: https://opendev.org/openstack/trove
trove_git_install_branch: 428e3644f8770a608f6e4dfc617f45f6e17cb685 # HEAD as of 14.06.2020
trove_git_project_group: trove_all
trove_git_track_branch: master

## Horizon Trove dashboard plugin
trove_dashboard_git_repo: https://opendev.org/openstack/trove-dashboard
trove_dashboard_git_install_branch: cccbd65bc23a0819e73e5a88d0028d99ff908286 # HEAD as of 14.06.2020
trove_dashboard_git_project_group: horizon_all
trove_dashboard_git_track_branch: master


## Octavia service
octavia_git_repo: https://opendev.org/openstack/octavia
octavia_git_install_branch: 6418ae00c9267f363a17f69d5fb92adaa9c08a8e  # HEAD as of 14.06.2020
octavia_git_project_group: octavia_all
octavia_git_track_branch: master


## Panko service
panko_git_repo: https://opendev.org/openstack/panko
panko_git_install_branch: d2453d77b6055da9cea71dba6353b0d55df69771  # HEAD as of 14.06.2020
panko_git_project_group: panko_all
panko_git_track_branch: master


## Placement service
placement_git_repo: https://opendev.org/openstack/placement
placement_git_install_branch: 2009e61335a43645e5d191546dbdc94709b221cd  # HEAD as of 14.06.2020
placement_git_project_group: placement_all
placement_git_track_branch: master


## Tacker service
tacker_git_repo: https://opendev.org/openstack/tacker
tacker_git_install_branch: 4237fe52046286b339fe7853d69d181f17824dba # HEAD as of 14.06.2020
tacker_git_project_group: tacker_all
tacker_git_track_branch: master


## Congress service
congress_git_repo: https://opendev.org/openstack/congress
congress_git_install_branch: bba805af02f516b95650531afc02d1c60b1cd010  # HEAD as of 14.06.2020
congress_git_package_name: openstack-congress
congress_git_project_group: congress_all
congress_git_track_branch: master

## Horizon Octavia dashboard plugin
octavia_dashboard_git_repo: https://opendev.org/openstack/octavia-dashboard
octavia_dashboard_git_install_branch: 6db692e5fa8eadbb137d85443a76b2a3863550da  # HEAD as of 14.06.2020
octavia_dashboard_git_project_group: horizon_all
octavia_dashboard_git_track_branch: master


## Blazar service
blazar_git_repo: https://opendev.org/openstack/blazar
blazar_git_install_branch: 0c3ac1911dcbcb1291001883af0d3ff42654c77a  # HEAD as of 14.06.2020
blazar_git_project_group: blazar_all
blazar_git_track_branch: master

## Blazar Nova Service
blazar_nova_git_repo: https://opendev.org/openstack/blazar-nova
blazar_nova_git_install_branch: 0473d573049faa6d95fcbbb02b836f9924a746d7  # HEAD as of 14.06.2020
blazar_nova_git_project_group: blazar_all
blazar_nova_git_track_branch: master

## Zun service
zun_git_repo: https://opendev.org/openstack/zun
zun_git_install_branch: b77686412bac24cb5ca61de1b3f3a2d0b1b4cf34 # HEAD as of 14.06.2020
zun_git_project_group: zun_all
zun_git_track_branch: master

## Zun kyrir service
zun_kuryr_git_repo: https://opendev.org/openstack/kuryr-libnetwork
zun_kuryr_git_install_branch: 3fc01f57fdddfefc540f11bf5347ea46e3e55095 # HEAD as of 14.06.2020
zun_kuryr_git_project_group: zun_all
zun_kuryr_git_track_branch: master
