---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


## NOTICE on items in this file:
##   * If you use anything in the *._git_install_branch field that is not a TAG
##     make sure to leave an in-line comment as to "why".

## For the sake of anyone else editing this file:
##   * If you add services to this file please do so in alphabetical order.
##   * Every entry should be name spaced with the name of the client followed by an "_"
##   * All items with this file should be separated by `name_` note that the name of the
##     package should be one long name with no additional `_` separating it.


### Before this is shipped all of these services should have a tag set as the branch,
### or have a comment / reason attached to them as to why a tag can not work.


## Global Requirements
requirements_git_repo: https://opendev.org/openstack/requirements
requirements_git_install_branch: d3959ceadc425e3b78649edb7e2e42c4f3931611 # HEAD as of 29.12.2019
requirements_git_track_branch: master


## Aodh service
aodh_git_repo: https://opendev.org/openstack/aodh
aodh_git_install_branch: b54455f165a7fe61ddda695c8560fec88ce47fea  # HEAD as of 29.12.2019
aodh_git_project_group: aodh_all
aodh_git_track_branch: master


## Barbican service
barbican_git_repo: https://opendev.org/openstack/barbican
barbican_git_install_branch: d633693bb0848fe73c0be5d7a24bb2883d441d86  # HEAD as of 29.12.2019
barbican_git_project_group: barbican_all
barbican_git_track_branch: master


## Ceilometer service
ceilometer_git_repo: https://opendev.org/openstack/ceilometer
ceilometer_git_install_branch: 0c0948f0a7ae292b90c8878a41e107f5de4e8000  # HEAD as of 29.12.2019
ceilometer_git_project_group: all
ceilometer_git_track_branch: master


## Cinder service
cinder_git_repo: https://opendev.org/openstack/cinder
cinder_git_install_branch: 83267c72ae6f66eb3d368296676cc1cdd9837e88  # HEAD as of 29.12.2019
cinder_git_project_group: cinder_all
cinder_git_track_branch: master


## Designate service
designate_git_repo: https://opendev.org/openstack/designate
designate_git_install_branch: 0050549441a1889a40b85accc4733d3dca8f067f  # HEAD as of 29.12.2019
designate_git_project_group: designate_all
designate_git_track_branch: master


## Horizon Designate dashboard plugin
designate_dashboard_git_repo: https://opendev.org/openstack/designate-dashboard
designate_dashboard_git_install_branch: b194e71909846b1c9acce4995ce8fd05356c3b4d  # HEAD as of 29.12.2019
designate_dashboard_git_project_group: horizon_all
designate_dashboard_git_track_branch: master


## Glance service
glance_git_repo: https://opendev.org/openstack/glance
glance_git_install_branch: 0eacf2da183b641447e1fae703bca65facde91b5  # HEAD as of 29.12.2019
glance_git_project_group: glance_all
glance_git_track_branch: master


## Heat service
heat_git_repo: https://opendev.org/openstack/heat
heat_git_install_branch: 28ce9f3ad42e1a4713dea845bcc4bdc5a6d08fb9  # HEAD as of 29.12.2019
heat_git_package_name: openstack-heat
heat_git_project_group: heat_all
heat_git_track_branch: master

## Horizon Heat dashboard plugin
heat_dashboard_git_repo: https://opendev.org/openstack/heat-dashboard
heat_dashboard_git_install_branch: f7af4f4117313219368d8041f5f2634452469f77  # HEAD as of 29.12.2019
heat_dashboard_git_project_group: horizon_all
heat_dashboard_git_track_branch: master

## Horizon service
horizon_git_repo: https://opendev.org/openstack/horizon
horizon_git_install_branch: ee36da77f5d639ed985421d1a615dc497bb0ec7d  # HEAD as of 29.12.2019
horizon_git_project_group: horizon_all
horizon_git_track_branch: master

## Horizon Ironic dashboard plugin
ironic_dashboard_git_repo: https://opendev.org/openstack/ironic-ui
ironic_dashboard_git_install_branch: 70a293d31ac4fb7f465b59e7a3c539c5629a205f  # HEAD as of 29.12.2019
ironic_dashboard_git_project_group: horizon_all
ironic_dashboard_git_track_branch: master

## Horizon Magnum dashboard plugin
magnum_dashboard_git_repo: https://opendev.org/openstack/magnum-ui
magnum_dashboard_git_install_branch: f6b5a2dc5ec5926225e512ba20b2c0fcf5fbd23d  # HEAD as of 29.12.2019
magnum_dashboard_git_project_group: horizon_all
magnum_dashboard_git_track_branch: master

## Horizon Masakari dashboard plugin
masakari_dashboard_git_repo: https://opendev.org/openstack/masakari-dashboard
masakari_dashboard_git_install_branch: a232649ab33279053b4a33f6023d013f20dcc5df  # HEAD as of 29.12.2019
masakari_dashboard_git_project_group: horizon_all
masakari_dashboard_git_track_branch: master

## Horizon FWaaS dashboard plugin
neutron_fwaas_dashboard_git_repo: https://opendev.org/openstack/neutron-fwaas-dashboard
neutron_fwaas_dashboard_git_install_branch: 4eb4547c2be3ede216ee8858e678e9cc068e16b1  # HEAD as of 29.12.2019
neutron_fwaas_dashboard_git_project_group: horizon_all
neutron_fwaas_dashboard_git_track_branch: master

## Horizon Sahara dashboard plugin
sahara_dashboard_git_repo: https://opendev.org/openstack/sahara-dashboard
sahara_dashboard_git_install_branch: 59f93f160cc75e9c23a53545e17c739efabf739e # HEAD as of 29.12.2019
sahara_dashboard_git_project_group: horizon_all
sahara_dashboard_git_track_branch: master


## Keystone service
keystone_git_repo: https://opendev.org/openstack/keystone
keystone_git_install_branch: a950f9c376534154ba15b2a7a9f962d316448b7a  # HEAD as of 29.12.2019
keystone_git_project_group: keystone_all
keystone_git_track_branch: master


## Manila service
manila_git_repo: https://opendev.org/openstack/manila
manila_git_install_branch: 4d68c25f2fc4982fb8cbcf24d63f046dd488252e  # HEAD as of 29.12.2019
manila_git_project_group: manila_all
manila_git_track_branch: master


## Neutron service
neutron_git_repo: https://opendev.org/openstack/neutron
neutron_git_install_branch: 68f89c79c803a3c9420e2a8df7a56499e88091ad  # HEAD as of 29.12.2019
neutron_git_project_group: neutron_all
neutron_git_track_branch: master

neutron_vpnaas_git_repo: https://opendev.org/openstack/neutron-vpnaas
neutron_vpnaas_git_install_branch: 7d851c64013e601a6f0d49180bdd5589f4d66c34  # HEAD as of 29.12.2019
neutron_vpnaas_git_project_group: neutron_all
neutron_vpnaas_git_track_branch: master

neutron_fwaas_git_repo: https://opendev.org/openstack/neutron-fwaas
neutron_fwaas_git_install_branch: 330e233a40b7d10436c8a8f74528a601747c98ec  # HEAD as of 29.12.2019
neutron_fwaas_git_project_group: neutron_all
neutron_fwaas_git_track_branch: master

neutron_dynamic_routing_git_repo: https://opendev.org/openstack/neutron-dynamic-routing
neutron_dynamic_routing_git_install_branch: 777fb1638e8b3d15ca261dfe449b443381819509  # HEAD as of 29.12.2019
neutron_dynamic_routing_git_project_group: neutron_all
neutron_dynamic_routing_git_track_branch: master

# Networking calico follows master
networking_calico_git_repo: https://opendev.org/openstack/networking-calico
networking_calico_git_install_branch: 594cf28fb0359c1abf6da1022574be5ddd710a7b  # HEAD as of 29.12.2019
networking_calico_git_project_group: neutron_all
networking_calico_git_track_branch: master

networking_odl_git_repo: https://opendev.org/openstack/networking-odl
networking_odl_git_install_branch: e765aa81808eec272cd2bec17c79fe9473d25a62  # HEAD as of 29.12.2019
networking_odl_git_project_group: neutron_all
networking_odl_git_track_branch: master

networking_ovn_git_repo: https://opendev.org/openstack/networking-ovn
networking_ovn_git_install_branch: 16735e32303810c5327822fe016a1d6413597657  # HEAD as of 29.12.2019
networking_ovn_git_project_group: neutron_all
networking_ovn_git_track_branch: master

# BGPVPN is frozen until further notice due to
# https://github.com/openstack/networking-bgpvpn/commit/e9a0ea199b47f76f69545e04bdb4db44869c388b#diff-b4ef698db8ca845e5845c4618278f29a
networking_bgpvpn_git_repo: https://opendev.org/openstack/networking-bgpvpn
networking_bgpvpn_git_install_branch: 3b93ddacd390d92fb144e5660324d4da064ad9a4 # FROZEN HEAD of "master" as of 31.03.2018
networking_bgpvpn_git_project_group: neutron_all
networking_bgpvpn_git_track_branch: None

networking_sfc_git_repo: https://opendev.org/openstack/networking-sfc
networking_sfc_git_install_branch: 84175687fb5c23fdf76322b18392c783ca8d6d73  # HEAD as of 29.12.2019
networking_sfc_git_project_group: neutron_all
networking_sfc_git_track_branch: master


## Nova service
nova_git_repo: https://opendev.org/openstack/nova
nova_git_install_branch: 65aae518f81c2754e30429a3547c5cf62a3cf598  # HEAD as of 29.12.2019
nova_git_project_group: nova_all
nova_git_track_branch: master


## Sahara service
sahara_git_repo: https://opendev.org/openstack/sahara
sahara_git_install_branch: bb2f1f586b6558367d0810e60c27e36195b48609 # HEAD as of 29.12.2019
sahara_git_project_group: sahara_all
sahara_git_track_branch: master


## Swift service
swift_git_repo: https://opendev.org/openstack/swift
swift_git_install_branch: 7862ec7b8a7c56fffc32e0bfac3665f8b4f198dc # HEAD as of 29.12.2019
swift_git_project_group: swift_all
swift_git_track_branch: master


## Ironic service
ironic_git_repo: https://opendev.org/openstack/ironic
ironic_git_install_branch: c39e84d4f5bf80ecc822f96e9a88d4e6f6b12023  # HEAD as of 29.12.2019
ironic_git_project_group: ironic_all
ironic_git_track_branch: master


## Magnum service
magnum_git_repo: https://opendev.org/openstack/magnum
magnum_git_install_branch: c2c701f78c9cbddd6e0e34082815c86be8b87aed  # HEAD as of 29.12.2019
magnum_git_project_group: magnum_all
magnum_git_track_branch: master

## Masakari service
masakari_git_repo: https://opendev.org/openstack/masakari
masakari_git_install_branch: 596b3d142eeea935fb2293de5631cd9dd4c191c6  # HEAD as of 29.12.2019
masakari_git_project_group: masakari_api
masakari_git_track_branch: master

## Masakari monitors services
masakari_monitors_git_repo: https://opendev.org/openstack/masakari-monitors
masakari_monitors_git_install_branch: b717be163e96dfd7363885a937f05197be3530b1  # HEAD as of 29.12.2019
masakari_monitors_git_project_group: masakari_monitor
masakari_monitors_git_track_branch: master

## Mistral service
mistral_git_repo: https://opendev.org/openstack/mistral
mistral_git_install_branch: 6e9a70db25ddbce2ce7ec4d6fd057cec5d988417  # HEAD as of 29.12.2019
mistral_git_project_group: mistral_all
mistral_git_track_branch: master

## Murano service
murano_git_repo: https://opendev.org/openstack/murano
murano_git_install_branch: b33d398950993cbf2e73e767eade281d67cd8546  # HEAD as of 29.12.2019
murano_git_project_group: murano_all
murano_git_track_branch: master

## Trove service
trove_git_repo: https://opendev.org/openstack/trove
trove_git_install_branch: 35f989a8701bd675f5ec3bafe161897fc23dfd90 # HEAD as of 29.12.2019
trove_git_project_group: trove_all
trove_git_track_branch: master

## Horizon Trove dashboard plugin
trove_dashboard_git_repo: https://opendev.org/openstack/trove-dashboard
trove_dashboard_git_install_branch: 50c31953a816197e1aecf4037525f6c4e7c84261 # HEAD as of 29.12.2019
trove_dashboard_git_project_group: horizon_all
trove_dashboard_git_track_branch: master


## Octavia service
octavia_git_repo: https://opendev.org/openstack/octavia
octavia_git_install_branch: 8f032d884e0f89ac69d5b6e5f5b77d19ee6eb1d7  # HEAD as of 29.12.2019
octavia_git_project_group: octavia_all
octavia_git_track_branch: master


## Panko service
panko_git_repo: https://opendev.org/openstack/panko
panko_git_install_branch: f7f87fc9694ccaff5e8dc149f956679676210d09  # HEAD as of 29.12.2019
panko_git_project_group: panko_all
panko_git_track_branch: master


## Placement service
placement_git_repo: https://opendev.org/openstack/placement
placement_git_install_branch: 3eab6acb65456c6c162af36f7cfeed31553dc6d2  # HEAD as of 29.12.2019
placement_git_project_group: placement_all
placement_git_track_branch: master


## Tacker service
tacker_git_repo: https://opendev.org/openstack/tacker
tacker_git_install_branch: c3263b83da705e089f98d0fce44feb7f137c5105 # HEAD as of 29.12.2019
tacker_git_project_group: tacker_all
tacker_git_track_branch: master


## Congress service
congress_git_repo: https://opendev.org/openstack/congress
congress_git_install_branch: 7aa9e87eaff8f8946d453ee6f9ed4ef5776c8196  # HEAD as of 29.12.2019
congress_git_package_name: openstack-congress
congress_git_project_group: congress_all
congress_git_track_branch: master

## Horizon Octavia dashboard plugin
octavia_dashboard_git_repo: https://opendev.org/openstack/octavia-dashboard
octavia_dashboard_git_install_branch: f4f7be3cdc9518c94d6e2dd204b032070ff6b1e6  # HEAD as of 29.12.2019
octavia_dashboard_git_project_group: horizon_all
octavia_dashboard_git_track_branch: master


## Blazar service
blazar_git_repo: https://opendev.org/openstack/blazar
blazar_git_install_branch: 9cef00c2ad795d7d6c334451ae7a3fa70f39eaa9  # HEAD as of 29.12.2019
blazar_git_project_group: blazar_all
blazar_git_track_branch: master

## Blazar Nova Service
blazar_nova_git_repo: https://opendev.org/openstack/blazar-nova
blazar_nova_git_install_branch: 4856c7209f5e227828073b2da1fd07c44137b373  # HEAD as of 29.12.2019
blazar_nova_git_project_group: blazar_all
blazar_nova_git_track_branch: master
