---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


## NOTICE on items in this file:
##   * If you use anything in the *._git_install_branch field that is not a TAG
##     make sure to leave an in-line comment as to "why".

## For the sake of anyone else editing this file:
##   * If you add services to this file please do so in alphabetical order.
##   * Every entry should be name spaced with the name of the client followed by an "_"
##   * All items with this file should be separated by `name_` note that the name of the
##     package should be one long name with no additional `_` separating it.


### Before this is shipped all of these services should have a tag set as the branch,
### or have a comment / reason attached to them as to why a tag can not work.


## Global Requirements
requirements_git_repo: https://opendev.org/openstack/requirements
requirements_git_install_branch: abbd4b407d8fd3ce39659de7d193887395204cae # HEAD as of 20.07.2021
requirements_git_track_branch: master

## Adjutant service
adjutant_git_repo: https://opendev.org/openstack/adjutant
adjutant_git_install_branch: d9045e4b105a3b88067c7f30915ca92fa697f150 # HEAD as of 20.07.2021
adjutant_git_track_branch: master

## Adjutant dashboard plugin
adjutant_dashboard_git_repo: https://opendev.org/openstack/adjutant-ui
adjutant_dashboard_git_install_branch: 104c474479e9a89d22b96777378ff59983c03393 # HEAD as of 20.07.2021
adjutant_dashboard_git_track_branch: master

## Aodh service
aodh_git_repo: https://opendev.org/openstack/aodh
aodh_git_install_branch: 10383f4d5b899d2644968090e4572c47fe314695 # HEAD as of 20.07.2021
aodh_git_track_branch: master


## Barbican service
barbican_git_repo: https://opendev.org/openstack/barbican
barbican_git_install_branch: 123c73a550bfc7979e0f056314f6e633f941a47a # HEAD as of 20.07.2021
barbican_git_track_branch: master


## Barbican dashboard plugin
barbican_dashboard_git_repo: https://opendev.org/openstack/barbican-ui
barbican_dashboard_git_install_branch: 3a78a743426376250f43508d4281e86c75067271 # HEAD as of 20.07.2021
barbican_dashboard_git_track_branch: master


## Ceilometer service
ceilometer_git_repo: https://opendev.org/openstack/ceilometer
ceilometer_git_install_branch: fe13beaa76f0a02699b46a9e10cc94af61b2f08b # HEAD as of 20.07.2021
ceilometer_git_track_branch: master


## Cinder service
cinder_git_repo: https://opendev.org/openstack/cinder
cinder_git_install_branch: 81f2aaeea91bce6455f9b09cc8795855200e75e1 # HEAD as of 20.07.2021
cinder_git_track_branch: master


## Cloudkitty service
cloudkitty_git_repo: https://opendev.org/openstack/cloudkitty
cloudkitty_git_install_branch: ffccfc222ce066e17c90d47ffc1bbfac32b34584 # HEAD as of 20.07.2021
cloudkitty_git_track_branch: master


## Cloudkitty dashboard plugin
cloudkitty_dashboard_git_repo: https://opendev.org/openstack/cloudkitty-dashboard
cloudkitty_dashboard_git_install_branch: 2a0ec4732542a98a82e71f948a2f2d377f00f1c2 # HEAD as of 20.07.2021
cloudkitty_dashboard_git_track_branch: master


## Designate service
designate_git_repo: https://opendev.org/openstack/designate
designate_git_install_branch: 6fc04e72ec1fd039290173197dc4921df2f3d1c0 # HEAD as of 20.07.2021
designate_git_track_branch: master


## Horizon Designate dashboard plugin
designate_dashboard_git_repo: https://opendev.org/openstack/designate-dashboard
designate_dashboard_git_install_branch: b948e43365bec0d96bcda0f31f25f74b5a9b0971 # HEAD as of 20.07.2021
designate_dashboard_git_track_branch: master


## Glance service
glance_git_repo: https://opendev.org/openstack/glance
glance_git_install_branch: 62334aa4645546011b97664c5329e5539a444676 # HEAD as of 20.07.2021
glance_git_track_branch: master


## Heat service
heat_git_repo: https://opendev.org/openstack/heat
heat_git_install_branch: c72b55bee9d27235615c188cc2e027bd71bcd830 # HEAD as of 20.07.2021
heat_git_track_branch: master

## Horizon Heat dashboard plugin
heat_dashboard_git_repo: https://opendev.org/openstack/heat-dashboard
heat_dashboard_git_install_branch: 1fbbf77a0a01149ce39e6b68c1a9845ae89dc17d # HEAD as of 20.07.2021
heat_dashboard_git_track_branch: master

## Horizon service
horizon_git_repo: https://opendev.org/openstack/horizon
horizon_git_install_branch: b58ac2894b9b901d6ed433fb049502d988222ceb # HEAD as of 20.07.2021
horizon_git_track_branch: master

## Horizon Ironic dashboard plugin
ironic_dashboard_git_repo: https://opendev.org/openstack/ironic-ui
ironic_dashboard_git_install_branch: 9488051e4fbe396c94456df6698b5eb7a1e6bb73 # HEAD as of 20.07.2021
ironic_dashboard_git_track_branch: master

## Horizon Magnum dashboard plugin
magnum_dashboard_git_repo: https://opendev.org/openstack/magnum-ui
magnum_dashboard_git_install_branch: defed81ab78bc6098a3ec7652a6eb6e649232b06 # HEAD as of 20.07.2021
magnum_dashboard_git_track_branch: master

## Horizon Masakari dashboard plugin
masakari_dashboard_git_repo: https://opendev.org/openstack/masakari-dashboard
masakari_dashboard_git_install_branch: a01dacca8a49b1cdb71191389e786ce5392b08cd # HEAD as of 20.07.2021
masakari_dashboard_git_track_branch: master


## Horizon Sahara dashboard plugin
sahara_dashboard_git_repo: https://opendev.org/openstack/sahara-dashboard
sahara_dashboard_git_install_branch: 4604f95cb22c8322a3bef9e59969d659f22e1a0a # HEAD as of 20.07.2021
sahara_dashboard_git_track_branch: master


## Keystone service
keystone_git_repo: https://opendev.org/openstack/keystone
keystone_git_install_branch: d1c7759f487612d6069ac076ad314e572a71ed24 # HEAD as of 20.07.2021
keystone_git_track_branch: master


## Manila service
manila_git_repo: https://opendev.org/openstack/manila
manila_git_install_branch: 1a395050395a7af3f2b2f11f3578a90a1d14e312 # HEAD as of 20.07.2021
manila_git_track_branch: master


## Neutron service
neutron_git_repo: https://opendev.org/openstack/neutron
neutron_git_install_branch: fcb2c7e2c8a5355de1031b02387740f7f9841911 # HEAD as of 20.07.2021
neutron_git_track_branch: master

neutron_vpnaas_git_repo: https://opendev.org/openstack/neutron-vpnaas
neutron_vpnaas_git_install_branch: 52eba441d171575726dc97c8b5c98681e65ac327 # HEAD as of 20.07.2021
neutron_vpnaas_git_track_branch: master


neutron_dynamic_routing_git_repo: https://opendev.org/openstack/neutron-dynamic-routing
neutron_dynamic_routing_git_install_branch: 7245c228c2a083a7700d20224cb82a6c216cdd63 # HEAD as of 20.07.2021
neutron_dynamic_routing_git_track_branch: master

# Networking calico follows master
networking_calico_git_repo: https://github.com/projectcalico/networking-calico
networking_calico_git_install_branch: 5a930a2a1cd882dde6c064e8cd240fbf4ff233d6 # HEAD as of 20.07.2021
networking_calico_git_track_branch: release-v3.19

networking_odl_git_repo: https://opendev.org/openstack/networking-odl
networking_odl_git_install_branch: a413efcbf389f2e9c71538365cad522ada219806 # HEAD as of 20.07.2021
networking_odl_git_track_branch: master

networking_bgpvpn_git_repo: https://opendev.org/openstack/networking-bgpvpn
networking_bgpvpn_git_install_branch: 8b3d07cd9ec83936d2f546923414d0c629d23c13 # HEAD as of 20.07.2021
networking_bgpvpn_git_track_branch: master

networking_sfc_git_repo: https://opendev.org/openstack/networking-sfc
networking_sfc_git_install_branch: e01048cc521c2c16f36cea23eef8331c6bae0904 # HEAD as of 20.07.2021
networking_sfc_git_track_branch: master

networking_generic_switch_git_repo: https://opendev.org/openstack/networking-generic-switch
networking_generic_switch_git_install_branch: 1828169f15f0c3b29a82d488937728dfdc61fbbe # HEAD as of 20.07.2021
networking_generic_switch_git_track_branch: master

networking_nsx_git_repo: https://opendev.org/x/vmware-nsx
networking_nsx_git_install_branch: f3d16822a55a0d027066f8e9e703668b70ca0f1f # HEAD as of 20.07.2021
networking_nsx_git_track_branch: master

networking_nsxlib_git_repo: https://opendev.org/x/vmware-nsxlib
networking_nsxlib_git_install_branch: d717cee827acb194d5a138fc50e36a64fcfedc9d # HEAD as of 20.07.2021
networking_nsxlib_git_track_branch: master

## Nova service
nova_git_repo: https://opendev.org/openstack/nova
nova_git_install_branch: 3545356ae3a719442833cb8c3c911408d4bd3c15 # HEAD as of 20.07.2021
nova_git_track_branch: master


## Sahara service
sahara_git_repo: https://opendev.org/openstack/sahara
sahara_git_install_branch: 622af6949b2f9da0fcd3f8d75ab89b79b50f42d4 # HEAD as of 20.07.2021
sahara_git_track_branch: master


## Senlin service
senlin_git_repo: https://opendev.org/openstack/senlin
senlin_git_install_branch: 3e02c0c8d83b33582e18a6a82df6535515086397 # HEAD as of 20.07.2021
senlin_git_track_branch: master


## Swift service
swift_git_repo: https://opendev.org/openstack/swift
swift_git_install_branch: d739c3eba5b12ddf79ac597cc4ce80201306e72b # HEAD as of 20.07.2021
swift_git_track_branch: master


## Ironic service
ironic_git_repo: https://opendev.org/openstack/ironic
ironic_git_install_branch: 103e34f5a8e3f22b329b6a38a05edff5539bb063 # HEAD as of 20.07.2021
ironic_git_track_branch: master


## Ironic inspector service
ironic_inspector_git_repo: https://opendev.org/openstack/ironic-inspector
ironic_inspector_git_install_branch: 611a543ecddda22ed5f19af96bf6b2f690cdbf51 # HEAD as of 20.07.2021
ironic_inspector_git_track_branch: master


## Magnum service
magnum_git_repo: https://opendev.org/openstack/magnum
magnum_git_install_branch: d8cc88284b3a45921eb5f182821e6fd558ddab94 # HEAD as of 20.07.2021
magnum_git_track_branch: master

## Masakari service
masakari_git_repo: https://opendev.org/openstack/masakari
masakari_git_install_branch: f2e830f9278a2bf1b3ac9b042bd25393f8793916 # HEAD as of 20.07.2021
masakari_git_track_branch: master

## Masakari monitors services
masakari_monitors_git_repo: https://opendev.org/openstack/masakari-monitors
masakari_monitors_git_install_branch: 6a496e78713fb8db56ccc1a6ad6ab007b88d102e # HEAD as of 20.07.2021
masakari_monitors_git_track_branch: master

## Mistral service
mistral_git_repo: https://opendev.org/openstack/mistral
mistral_git_install_branch: 22e822dde29dd68c5868f615629b84b53841c4e6 # HEAD as of 20.07.2021
mistral_git_track_branch: master

## Murano service
murano_git_repo: https://opendev.org/openstack/murano
murano_git_install_branch: 67baf3175ddbeedb3d1ebe13a5cee1d2628bab27 # HEAD as of 20.07.2021
murano_git_track_branch: master

murano_dashboard_git_repo: https://opendev.org/openstack/murano-dashboard
murano_dashboard_git_install_branch: 6175248cef1954e30645537dd4b442c3deb2676e # HEAD as of 20.07.2021
murano_dashboard_git_track_branch: master

## Trove service
trove_git_repo: https://opendev.org/openstack/trove
trove_git_install_branch: 69f08ab470a0d1d1d4676b41ad29a9c19ce28648 # HEAD as of 20.07.2021
trove_git_track_branch: master

## Horizon Trove dashboard plugin
trove_dashboard_git_repo: https://opendev.org/openstack/trove-dashboard
trove_dashboard_git_install_branch: 05d15b33cbc062d0d2013ae347a07c87f53af6e0 # HEAD as of 20.07.2021
trove_dashboard_git_track_branch: master


## Octavia service
octavia_git_repo: https://opendev.org/openstack/octavia
octavia_git_install_branch: 7e264e1f21ee396d046e0df0c1a4f4218039e4aa # HEAD as of 20.07.2021
octavia_git_track_branch: master


## Placement service
placement_git_repo: https://opendev.org/openstack/placement
placement_git_install_branch: 4fa74c24e7d58f192ca9fb165243f0b1fc56491e # HEAD as of 20.07.2021
placement_git_track_branch: master


## Tacker service
tacker_git_repo: https://opendev.org/openstack/tacker
tacker_git_install_branch: a98cd4eaa9f2c1669f0a1d1c748d6d0028edd1f4 # HEAD as of 20.07.2021
tacker_git_track_branch: master


## Horizon Octavia dashboard plugin
octavia_dashboard_git_repo: https://opendev.org/openstack/octavia-dashboard
octavia_dashboard_git_install_branch: 7e390312eaf3cbbf89d46b05dd20b5296d61616d # HEAD as of 20.07.2021
octavia_dashboard_git_track_branch: master


## Blazar service
blazar_git_repo: https://opendev.org/openstack/blazar
blazar_git_install_branch: 63d94170b59937995247ff8443a3303e5288d304 # HEAD as of 20.07.2021
blazar_git_track_branch: master

## Blazar Nova Service
blazar_nova_git_repo: https://opendev.org/openstack/blazar-nova
blazar_nova_git_install_branch: 5f7bd6eea5f737f2bfbfea7d114f8e4ee99c04d2 # HEAD as of 20.07.2021
blazar_nova_git_track_branch: master

## Zun service
zun_git_repo: https://opendev.org/openstack/zun
zun_git_install_branch: abd1e5c9f34c3b3c141600f0386e77ab41f7e89a # HEAD as of 20.07.2021
zun_git_track_branch: master

## Zun kuryr service
zun_kuryr_git_repo: https://opendev.org/openstack/kuryr-libnetwork
zun_kuryr_git_install_branch: dbb7a4dff64326d547243ce092d5064a13bfabb0 # HEAD as of 20.07.2021
zun_kuryr_git_track_branch: master

## Zun kuryr library
zun_kuryr_lib_git_repo: https://opendev.org/openstack/kuryr
zun_kuryr_lib_git_install_branch: 764de32607059a9a1a0bd37c46609815a1abe1ba # HEAD as of 20.07.2021
zun_kuryr_lib_git_track_branch: master
