---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


## NOTICE on items in this file:
##   * If you use anything in the *._git_install_branch field that is not a TAG
##     make sure to leave an in-line comment as to "why".

## For the sake of anyone else editing this file:
##   * If you add services to this file please do so in alphabetical order.
##   * Every entry should be name spaced with the name of the client followed by an "_"
##   * All items with this file should be separated by `name_` note that the name of the
##     package should be one long name with no additional `_` separating it.


### Before this is shipped all of these services should have a tag set as the branch,
### or have a comment / reason attached to them as to why a tag can not work.


## Global Requirements
requirements_git_repo: https://opendev.org/openstack/requirements
requirements_git_install_branch: 36710831f3154ec0844fb2a38317815435da46bc # HEAD as of 13.12.2020
requirements_git_track_branch: stable/victoria

## Adjutant service
adjutant_git_repo: https://opendev.org/openstack/adjutant
adjutant_git_install_branch: 43e0c625e39f826b578e3e5c25519606d9b72808  # HEAD as of 13.12.2020
adjutant_git_project_group: adjutant_all
adjutant_git_track_branch: stable/victoria

## Aodh service
aodh_git_repo: https://opendev.org/openstack/aodh
aodh_git_install_branch: 028561741e125f1b343ae5bf1021df1012e92005  # HEAD as of 13.12.2020
aodh_git_project_group: aodh_all
aodh_git_track_branch: stable/victoria


## Barbican service
barbican_git_repo: https://opendev.org/openstack/barbican
barbican_git_install_branch: bbf024012e25b89622b58c7e8fc558d7e701e2d0  # HEAD as of 13.12.2020
barbican_git_project_group: barbican_all
barbican_git_track_branch: stable/victoria


## Ceilometer service
ceilometer_git_repo: https://opendev.org/openstack/ceilometer
ceilometer_git_install_branch: e555e938a6c13c7867e66f6c710c5bf8b9e246de  # HEAD as of 13.12.2020
ceilometer_git_project_group: all
ceilometer_git_track_branch: stable/victoria


## Cinder service
cinder_git_repo: https://opendev.org/openstack/cinder
cinder_git_install_branch: cdc586631586dc9782794a90f129ce3f34118193  # HEAD as of 13.12.2020
cinder_git_project_group: cinder_all
cinder_git_track_branch: stable/victoria


## Designate service
designate_git_repo: https://opendev.org/openstack/designate
designate_git_install_branch: 16fd046c71d8c418bb144e9f70dde681420261ad  # HEAD as of 13.12.2020
designate_git_project_group: designate_all
designate_git_track_branch: stable/victoria


## Horizon Designate dashboard plugin
designate_dashboard_git_repo: https://opendev.org/openstack/designate-dashboard
designate_dashboard_git_install_branch: 7b1adbd7be137ff3e67fc051b4b1ffe8745f46c1  # HEAD as of 13.12.2020
designate_dashboard_git_project_group: horizon_all
designate_dashboard_git_track_branch: stable/victoria


## Glance service
glance_git_repo: https://opendev.org/openstack/glance
glance_git_install_branch: 794c0fa19883c245ced7a886f9f5d11bd50228c4  # HEAD as of 13.12.2020
glance_git_project_group: glance_all
glance_git_track_branch: stable/victoria


## Heat service
heat_git_repo: https://opendev.org/openstack/heat
heat_git_install_branch: 7e03502a6e3477dcada86f51adeff8d22d2e5951  # HEAD as of 13.12.2020
heat_git_package_name: openstack-heat
heat_git_project_group: heat_all
heat_git_track_branch: stable/victoria

## Horizon Heat dashboard plugin
heat_dashboard_git_repo: https://opendev.org/openstack/heat-dashboard
heat_dashboard_git_install_branch: e601aab1a3f238429d8b28d3034fcf45fbd83a8b  # HEAD as of 13.12.2020
heat_dashboard_git_project_group: horizon_all
heat_dashboard_git_track_branch: stable/victoria

## Horizon service
horizon_git_repo: https://opendev.org/openstack/horizon
horizon_git_install_branch: afebcf42c3e4ba33c553d5f35c4536b2e38d6abd  # HEAD as of 13.12.2020
horizon_git_project_group: horizon_all
horizon_git_track_branch: stable/victoria

## Horizon Ironic dashboard plugin
ironic_dashboard_git_repo: https://opendev.org/openstack/ironic-ui
ironic_dashboard_git_install_branch: 268629d80ebbdb00668a6902625911b45fb0ab5a  # HEAD as of 13.12.2020
ironic_dashboard_git_project_group: horizon_all
ironic_dashboard_git_track_branch: stable/victoria

## Horizon Magnum dashboard plugin
magnum_dashboard_git_repo: https://opendev.org/openstack/magnum-ui
magnum_dashboard_git_install_branch: 7f4fd7bb12f3cbb76aa9939900b2fd4ae49134c6  # HEAD as of 13.12.2020
magnum_dashboard_git_project_group: horizon_all
magnum_dashboard_git_track_branch: stable/victoria

## Horizon Masakari dashboard plugin
masakari_dashboard_git_repo: https://opendev.org/openstack/masakari-dashboard
masakari_dashboard_git_install_branch: 267f96e483c825cfac508aa31a0c41765a11af76  # HEAD as of 13.12.2020
masakari_dashboard_git_project_group: horizon_all
masakari_dashboard_git_track_branch: stable/victoria


## Horizon Sahara dashboard plugin
sahara_dashboard_git_repo: https://opendev.org/openstack/sahara-dashboard
sahara_dashboard_git_install_branch: bd37574be4fb279b5088b8d8e9389e3de85d9ae2 # HEAD as of 13.12.2020
sahara_dashboard_git_project_group: horizon_all
sahara_dashboard_git_track_branch: stable/victoria


## Keystone service
keystone_git_repo: https://opendev.org/openstack/keystone
keystone_git_install_branch: a26a40d441e7f211fd68e0c1b9c779d965c19dea  # HEAD as of 13.12.2020
keystone_git_project_group: keystone_all
keystone_git_track_branch: stable/victoria


## Manila service
manila_git_repo: https://opendev.org/openstack/manila
manila_git_install_branch: 6250197a14e92aca7f8698873ba2dfe9a649f464  # HEAD as of 13.12.2020
manila_git_project_group: manila_all
manila_git_track_branch: stable/victoria


## Neutron service
neutron_git_repo: https://opendev.org/openstack/neutron
neutron_git_install_branch: 311071f567cc33d9868ba317536da18b7071d14e  # HEAD as of 13.12.2020
neutron_git_project_group: neutron_all
neutron_git_track_branch: stable/victoria

neutron_vpnaas_git_repo: https://opendev.org/openstack/neutron-vpnaas
neutron_vpnaas_git_install_branch: 51232ec14fb94468c4820dfa886e35bbafdc08e8  # HEAD as of 13.12.2020
neutron_vpnaas_git_project_group: neutron_all
neutron_vpnaas_git_track_branch: stable/victoria


neutron_dynamic_routing_git_repo: https://opendev.org/openstack/neutron-dynamic-routing
neutron_dynamic_routing_git_install_branch: a99d5db87de283b027df533b0189828d69385656  # HEAD as of 13.12.2020
neutron_dynamic_routing_git_project_group: neutron_all
neutron_dynamic_routing_git_track_branch: stable/victoria

# Networking calico follows master
networking_calico_git_repo: https://github.com/projectcalico/networking-calico
networking_calico_git_install_branch: 1a588c56645333ab044cf98661498d4e601d1590  # HEAD as of 13.12.2020
networking_calico_git_project_group: neutron_all
networking_calico_git_track_branch: release-v3.16

networking_odl_git_repo: https://opendev.org/openstack/networking-odl
networking_odl_git_install_branch: 09948fa1523e051d371cb3c915f8b0a3bb553ecf  # HEAD as of 13.12.2020
networking_odl_git_project_group: neutron_all
networking_odl_git_track_branch: stable/victoria

networking_bgpvpn_git_repo: https://opendev.org/openstack/networking-bgpvpn
networking_bgpvpn_git_install_branch: b849ea5c74e3729df25e868a266d8076ad85f4d7  # HEAD as of 13.12.2020
networking_bgpvpn_git_project_group: neutron_all
networking_bgpvpn_git_track_branch: stable/victoria

networking_sfc_git_repo: https://opendev.org/openstack/networking-sfc
networking_sfc_git_install_branch: 49b7c208416dbadcdd198a9414500c52357e8d0a  # HEAD as of 13.12.2020
networking_sfc_git_project_group: neutron_all
networking_sfc_git_track_branch: stable/victoria

networking_generic_switch_git_repo: https://opendev.org/openstack/networking-generic-switch
networking_generic_switch_git_install_branch: f7e74b0520f102eca011c5efc526740185b4e6bd  # HEAD as of 13.12.2020
networking_generic_switch_git_project_group: neutron_all
networking_generic_switch_git_track_branch: stable/victoria

networking_nsx_git_repo: https://opendev.org/x/vmware-nsx
networking_nsx_git_install_branch: e3c7c19dc64f05b10173889a0815521d2ea0a3db  # HEAD as of 13.12.2020
networking_nsx_git_project_group: neutron_all
networking_nsx_git_track_branch: stable/victoria

networking_nsxlib_git_repo: https://opendev.org/x/vmware-nsxlib
networking_nsxlib_git_install_branch: e8e804d866f2139e0822ebc51cb98b309479601d  # HEAD as of 13.12.2020
networking_nsxlib_git_project_group: neutron_all
networking_nsxlib_git_track_branch: stable/victoria

## Nova service
nova_git_repo: https://opendev.org/openstack/nova
nova_git_install_branch: e3da2ca7be0cb06fe05717ea78718d9323c7ca40  # HEAD as of 13.12.2020
nova_git_project_group: nova_all
nova_git_track_branch: stable/victoria


## Sahara service
sahara_git_repo: https://opendev.org/openstack/sahara
sahara_git_install_branch: 8cba2f25362cb45a518fa5c44627d68809b095b0 # HEAD as of 13.12.2020
sahara_git_project_group: sahara_all
sahara_git_track_branch: stable/victoria


## Senlin service
senlin_git_repo: https://opendev.org/openstack/senlin
senlin_git_install_branch: a2d9092c8bb0bb1635e3ebbece343e8eded5fec1 # HEAD as of 13.12.2020
senlin_git_project_group: senlin_all
senlin_git_track_branch: stable/victoria


## Swift service
swift_git_repo: https://opendev.org/openstack/swift
swift_git_install_branch: 508c444697e9d0d721adc0bcc0b863b43ab3768d # HEAD as of 13.12.2020
swift_git_project_group: swift_all
swift_git_track_branch: stable/victoria


## Ironic service
ironic_git_repo: https://opendev.org/openstack/ironic
ironic_git_install_branch: 0f438e7d8de9b689ebb2f239c5003afbf69dade2  # HEAD as of 13.12.2020
ironic_git_project_group: ironic_all
ironic_git_track_branch: stable/victoria


## Ironic inspector service
ironic_inspector_git_repo: https://opendev.org/openstack/ironic-inspector
ironic_inspector_git_install_branch: 70fccecb2da254d4e5e98b4b30f504e1b19c8408  # HEAD as of 13.12.2020
ironic_inspector_git_project_group: ironic_inspector
ironic_inspector_git_track_branch: stable/victoria


## Magnum service
magnum_git_repo: https://opendev.org/openstack/magnum
magnum_git_install_branch: a3b43bca7143c1894b71afb2eb2c549430ddc919  # HEAD as of 13.12.2020
magnum_git_project_group: magnum_all
magnum_git_track_branch: stable/victoria

## Masakari service
masakari_git_repo: https://opendev.org/openstack/masakari
masakari_git_install_branch: df08edac13caccef5a5939b7d56f65480312a41e  # HEAD as of 13.12.2020
masakari_git_project_group: masakari_api
masakari_git_track_branch: stable/victoria

## Masakari monitors services
masakari_monitors_git_repo: https://opendev.org/openstack/masakari-monitors
masakari_monitors_git_install_branch: ec7d0f297ced633671c0c4617dd91a8f04d13230  # HEAD as of 13.12.2020
masakari_monitors_git_project_group: masakari_monitor
masakari_monitors_git_track_branch: stable/victoria

## Mistral service
mistral_git_repo: https://opendev.org/openstack/mistral
mistral_git_install_branch: 6e9c47cf03bfa21c4457325a8244969460c39d14  # HEAD as of 13.12.2020
mistral_git_project_group: mistral_all
mistral_git_track_branch: stable/victoria

## Murano service
murano_git_repo: https://opendev.org/openstack/murano
murano_git_install_branch: b8f0708149dac18b72e30ed47860f3f3993d54c5  # HEAD as of 13.12.2020
murano_git_project_group: murano_all
murano_git_track_branch: stable/victoria

murano_dashboard_git_repo: https://opendev.org/openstack/murano-dashboard
murano_dashboard_git_install_branch: 122fbb8548a4c1507462a9c7b27f7521b05ded3a  # HEAD as of 13.12.2020
murano_dashboard_git_project_group: murano_all
murano_dashboard_git_track_branch: stable/victoria

## Trove service
trove_git_repo: https://opendev.org/openstack/trove
trove_git_install_branch: 73978a9b978788817ee98ef6970a35f9121a2dc9 # HEAD as of 13.12.2020
trove_git_project_group: trove_all
trove_git_track_branch: stable/victoria

## Horizon Trove dashboard plugin
trove_dashboard_git_repo: https://opendev.org/openstack/trove-dashboard
trove_dashboard_git_install_branch: d99d3944eb6c4df90e413aae8ed2927110df8515 # HEAD as of 13.12.2020
trove_dashboard_git_project_group: horizon_all
trove_dashboard_git_track_branch: stable/victoria


## Octavia service
octavia_git_repo: https://opendev.org/openstack/octavia
octavia_git_install_branch: 9471d05976495b7f35115bc1f7727df781e1cbeb  # HEAD as of 13.12.2020
octavia_git_project_group: octavia_all
octavia_git_track_branch: stable/victoria


## Panko service
panko_git_repo: https://opendev.org/openstack/panko
panko_git_install_branch: 4d0c0d66da6833e5283d71fe5bdee9594e4b651c  # HEAD as of 13.12.2020
panko_git_project_group: panko_all
panko_git_track_branch: stable/victoria


## Placement service
placement_git_repo: https://opendev.org/openstack/placement
placement_git_install_branch: 471e4cc8b78d4382820bbb5245e15d648e7cc136  # HEAD as of 13.12.2020
placement_git_project_group: placement_all
placement_git_track_branch: stable/victoria


## Tacker service
tacker_git_repo: https://opendev.org/openstack/tacker
tacker_git_install_branch: e4a7d9b7cd0b4ca110230eca64fe5fa0ba68d3ed # HEAD as of 13.12.2020
tacker_git_project_group: tacker_all
tacker_git_track_branch: stable/victoria


## Horizon Octavia dashboard plugin
octavia_dashboard_git_repo: https://opendev.org/openstack/octavia-dashboard
octavia_dashboard_git_install_branch: 1b8a97d6c4f8f1799d8eae38e24d7c7b79bee3c7  # HEAD as of 13.12.2020
octavia_dashboard_git_project_group: horizon_all
octavia_dashboard_git_track_branch: stable/victoria


## Blazar service
blazar_git_repo: https://opendev.org/openstack/blazar
blazar_git_install_branch: 002024d5fb4da56aad66fc5ca795f2d4892269c6  # HEAD as of 13.12.2020
blazar_git_project_group: blazar_all
blazar_git_track_branch: stable/victoria

## Blazar Nova Service
blazar_nova_git_repo: https://opendev.org/openstack/blazar-nova
blazar_nova_git_install_branch: e363f22fa9bc5a8d683518ba75c216a26acfc5fd  # HEAD as of 13.12.2020
blazar_nova_git_project_group: blazar_all
blazar_nova_git_track_branch: stable/victoria

## Zun service
zun_git_repo: https://opendev.org/openstack/zun
zun_git_install_branch: 4014ba9ea326fc15f370c2dda5cecf046275e429 # HEAD as of 13.12.2020
zun_git_project_group: zun_all
zun_git_track_branch: stable/victoria

## Zun kuryr service
zun_kuryr_git_repo: https://opendev.org/openstack/kuryr-libnetwork
zun_kuryr_git_install_branch: 402b764c2f6a1290125d03b5280a5c6b7666b44c # HEAD as of 13.12.2020
zun_kuryr_git_project_group: zun_all
zun_kuryr_git_track_branch: stable/victoria

## Zun kuryr library
zun_kuryr_lib_git_repo: https://opendev.org/openstack/kuryr
zun_kuryr_lib_git_install_branch: 0af52266184e77e7dff4852200044007a0548415 # HEAD as of 13.12.2020
zun_kuryr_lib_git_project_group: zun_all
zun_kuryr_lib_git_track_branch: stable/victoria
