---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


## NOTICE on items in this file:
##   * If you use anything in the *._git_install_branch field that is not a TAG
##     make sure to leave an in-line comment as to "why".

## For the sake of anyone else editing this file:
##   * If you add services to this file please do so in alphabetical order.
##   * Every entry should be name spaced with the name of the client followed by an "_"
##   * All items with this file should be separated by `name_` note that the name of the
##     package should be one long name with no additional `_` separating it.


### Before this is shipped all of these services should have a tag set as the branch,
### or have a comment / reason attached to them as to why a tag can not work.


## Global Requirements
requirements_git_repo: https://opendev.org/openstack/requirements
requirements_git_install_branch: 72a83df4edd56fb45d8d66c71e4df56442cc4940 # HEAD as of 30.06.2019
requirements_git_track_branch: stable/stein


## Aodh service
aodh_git_repo: https://opendev.org/openstack/aodh
aodh_git_install_branch: 1b1b8e20c7e4872e2872182757e561125859c9f0  # HEAD as of 30.06.2019
aodh_git_project_group: aodh_all
aodh_git_track_branch: stable/stein


## Barbican service
barbican_git_repo: https://opendev.org/openstack/barbican
barbican_git_install_branch: 35f698da4e1785565ef28a06e37e15135090a245  # HEAD as of 30.06.2019
barbican_git_project_group: barbican_all
barbican_git_track_branch: stable/stein


## Ceilometer service
ceilometer_git_repo: https://opendev.org/openstack/ceilometer
ceilometer_git_install_branch: 22b8e2fba2b7116dc732ff98b06ee6b7cfce77ae  # HEAD as of 30.06.2019
ceilometer_git_project_group: all
ceilometer_git_track_branch: stable/stein


## Cinder service
cinder_git_repo: https://opendev.org/openstack/cinder
cinder_git_install_branch: 0996f0ac76188c324831f19089bdd87b9c364cb6  # HEAD as of 30.06.2019
cinder_git_project_group: cinder_all
cinder_git_track_branch: stable/stein


## Designate service
designate_git_repo: https://opendev.org/openstack/designate
designate_git_install_branch: 4a564e1804ebe085d4f992423da9ed0ba6c33cbe  # HEAD as of 30.06.2019
designate_git_project_group: designate_all
designate_git_track_branch: stable/stein


## Horizon Designate dashboard plugin
designate_dashboard_git_repo: https://opendev.org/openstack/designate-dashboard
designate_dashboard_git_install_branch: b8dc251792ffdc84d06091242880166d48e6c873  # HEAD as of 30.06.2019
designate_dashboard_git_project_group: horizon_all
designate_dashboard_git_track_branch: stable/stein


## Glance service
glance_git_repo: https://opendev.org/openstack/glance
glance_git_install_branch: f77232182c56cb4d4dcafadfbf086ce4aa09fa1e  # HEAD as of 30.06.2019
glance_git_project_group: glance_all
glance_git_track_branch: stable/stein


## Heat service
heat_git_repo: https://opendev.org/openstack/heat
heat_git_install_branch: e5b6c90b4c69b83baf0d80a6cad0a2bf39c944a5  # HEAD as of 30.06.2019
heat_git_package_name: openstack-heat
heat_git_project_group: heat_all
heat_git_track_branch: stable/stein

## Horizon Heat dashboard plugin
heat_dashboard_git_repo: https://opendev.org/openstack/heat-dashboard
heat_dashboard_git_install_branch: c8d8cab3557f76f5363822f1bb2cbe1ec32858d3  # HEAD as of 30.06.2019
heat_dashboard_git_project_group: horizon_all
heat_dashboard_git_track_branch: stable/stein

## Horizon service
horizon_git_repo: https://opendev.org/openstack/horizon
horizon_git_install_branch: c3ac75edcb0808bb25977bee3c3a5691c325a708  # HEAD as of 30.06.2019
horizon_git_project_group: horizon_all
horizon_git_track_branch: stable/stein

## Horizon Ironic dashboard plugin
ironic_dashboard_git_repo: https://opendev.org/openstack/ironic-ui
ironic_dashboard_git_install_branch: 859560fe8722edbd61a79d3137814295fad43b61  # HEAD as of 30.06.2019
ironic_dashboard_git_project_group: horizon_all
ironic_dashboard_git_track_branch: stable/stein

## Horizon Magnum dashboard plugin
magnum_dashboard_git_repo: https://opendev.org/openstack/magnum-ui
magnum_dashboard_git_install_branch: 2e494fb673fc79dbbc94ff67644eaf8f42efce6c  # HEAD as of 30.06.2019
magnum_dashboard_git_project_group: horizon_all
magnum_dashboard_git_track_branch: stable/stein

## Horizon Masakari dashboard plugin
masakari_dashboard_git_repo: https://opendev.org/openstack/masakari-dashboard
masakari_dashboard_git_install_branch: 2ddff1358068b384e51cd0a32e313da963096740  # HEAD as of 30.06.2019
masakari_dashboard_git_project_group: horizon_all
masakari_dashboard_git_track_branch: stable/stein

## Horizon LBaaS dashboard plugin
neutron_lbaas_dashboard_git_repo: https://opendev.org/openstack/neutron-lbaas-dashboard
neutron_lbaas_dashboard_git_install_branch: 87d0c15b10f9087de5f80d5565f41c884f91db59  # HEAD as of 30.06.2019
neutron_lbaas_dashboard_git_project_group: horizon_all
neutron_lbaas_dashboard_git_track_branch: stable/stein

## Horizon FWaaS dashboard plugin
neutron_fwaas_dashboard_git_repo: https://opendev.org/openstack/neutron-fwaas-dashboard
neutron_fwaas_dashboard_git_install_branch: 1fcd4e865d21c32881fbfe569f315807720fff23  # HEAD as of 30.06.2019
neutron_fwaas_dashboard_git_project_group: horizon_all
neutron_fwaas_dashboard_git_track_branch: stable/stein

## Horizon Sahara dashboard plugin
sahara_dashboard_git_repo: https://opendev.org/openstack/sahara-dashboard
sahara_dashboard_git_install_branch: d73912d3853d05995b55635fb51d34c20dce3979 # HEAD as of 30.06.2019
sahara_dashboard_git_project_group: horizon_all
sahara_dashboard_git_track_branch: stable/stein


## Keystone service
keystone_git_repo: https://opendev.org/openstack/keystone
keystone_git_install_branch: 1828d0612cf2c51427773077dc25bd8b659eb549  # HEAD as of 30.06.2019
keystone_git_project_group: keystone_all
keystone_git_track_branch: stable/stein


## Manila service
manila_git_repo: https://opendev.org/openstack/manila
manila_git_install_branch: f1ae3df86a3c8792689fc1e494dd93dcb34ea55c  # HEAD as of 30.06.2019
manila_git_project_group: manila_all
manila_git_track_branch: stable/stein


## Neutron service
neutron_git_repo: https://opendev.org/openstack/neutron
neutron_git_install_branch: e735aa376fba766f0f23c6ce62535bb0dd3dc312  # HEAD as of 30.06.2019
neutron_git_project_group: neutron_all
neutron_git_track_branch: stable/stein

neutron_lbaas_git_repo: https://opendev.org/openstack/neutron-lbaas
neutron_lbaas_git_install_branch: 30bdd86690596e32e6daf960f6bcd97683b508bb  # HEAD as of 30.06.2019
neutron_lbaas_git_project_group: neutron_all
neutron_lbaas_git_track_branch: stable/stein

neutron_vpnaas_git_repo: https://opendev.org/openstack/neutron-vpnaas
neutron_vpnaas_git_install_branch: 31ba50b20ca4b2be9ac51dc0e213f0504cf74699  # HEAD as of 30.06.2019
neutron_vpnaas_git_project_group: neutron_all
neutron_vpnaas_git_track_branch: stable/stein

neutron_fwaas_git_repo: https://opendev.org/openstack/neutron-fwaas
neutron_fwaas_git_install_branch: c49c1d697798337335524594ecc15a9adb4e3561  # HEAD as of 30.06.2019
neutron_fwaas_git_project_group: neutron_all
neutron_fwaas_git_track_branch: stable/stein

neutron_dynamic_routing_git_repo: https://opendev.org/openstack/neutron-dynamic-routing
neutron_dynamic_routing_git_install_branch: f313f0e9c030849d62e6bc4c9511efe9623ab06f  # HEAD as of 30.06.2019
neutron_dynamic_routing_git_project_group: neutron_all
neutron_dynamic_routing_git_track_branch: stable/stein

# Networking calico follows master
networking_calico_git_repo: https://opendev.org/openstack/networking-calico
networking_calico_git_install_branch: 87e780110d3ba0f0b57154ad74f9254aa950acda  # HEAD as of 30.06.2019
networking_calico_git_project_group: neutron_all
networking_calico_git_track_branch: master

networking_odl_git_repo: https://opendev.org/openstack/networking-odl
networking_odl_git_install_branch: d9e171187780bcb9fc7452fb78e63158fef3e8e4  # HEAD as of 30.06.2019
networking_odl_git_project_group: neutron_all
networking_odl_git_track_branch: stable/stein

networking_ovn_git_repo: https://opendev.org/openstack/networking-ovn
networking_ovn_git_install_branch: c243b5b68a4b3a1314f134cb8fc71129f5d3bc6f  # HEAD as of 30.06.2019
networking_ovn_git_project_group: neutron_all
networking_ovn_git_track_branch: stable/stein

# BGPVPN is frozen until further notice due to
# https://github.com/openstack/networking-bgpvpn/commit/e9a0ea199b47f76f69545e04bdb4db44869c388b#diff-b4ef698db8ca845e5845c4618278f29a
networking_bgpvpn_git_repo: https://opendev.org/openstack/networking-bgpvpn
networking_bgpvpn_git_install_branch: 3b93ddacd390d92fb144e5660324d4da064ad9a4 # FROZEN HEAD of "stable/stein" as of 31.03.2018
networking_bgpvpn_git_project_group: neutron_all
networking_bgpvpn_git_track_branch: None

networking_sfc_git_repo: https://opendev.org/openstack/networking-sfc
networking_sfc_git_install_branch: 8bee6b4896d7a5428b3e4053c7f3d0786412603f  # HEAD as of 30.06.2019
networking_sfc_git_project_group: neutron_all
networking_sfc_git_track_branch: stable/stein


## Nova service
nova_git_repo: https://opendev.org/openstack/nova
nova_git_install_branch: 89413ff042ae119bfe35378fbf0bb56bf0d07fe3  # HEAD as of 30.06.2019
nova_git_project_group: nova_all
nova_git_track_branch: stable/stein


## PowerVM Virt Driver
nova_powervm_git_repo: https://opendev.org/openstack/nova-powervm
nova_powervm_git_install_branch: 6806d3d6f673fbe75f7df7fc40fe9fc04088e34f  # HEAD as of 30.06.2019
nova_powervm_git_project_group: nova_all
nova_powervm_git_track_branch: stable/stein


## LXD Virt Driver
nova_lxd_git_repo: https://opendev.org/x/nova-lxd
nova_lxd_git_install_branch: 14819c16f3705a119235149d8883eac20fdff9fe  # HEAD as of 30.06.2019
nova_lxd_git_project_group: nova_all
nova_lxd_git_track_branch: stable/stein


## Sahara service
sahara_git_repo: https://opendev.org/openstack/sahara
sahara_git_install_branch: 994ff8cb4c89a3e57f3091e086862a3abe2175ec # HEAD as of 30.06.2019
sahara_git_project_group: sahara_all
sahara_git_track_branch: stable/stein


## Swift service
swift_git_repo: https://opendev.org/openstack/swift
swift_git_install_branch: 5ba975cf6962872635ef625fd7d88838f326b6ea # HEAD as of 30.06.2019
swift_git_project_group: swift_all
swift_git_track_branch: stable/stein


## Ironic service
ironic_git_repo: https://opendev.org/openstack/ironic
ironic_git_install_branch: c3cbdb5f32d367c33a2a995a7f68fdf41c55ef38  # HEAD as of 30.06.2019
ironic_git_project_group: ironic_all
ironic_git_track_branch: stable/stein


## Magnum service
magnum_git_repo: https://opendev.org/openstack/magnum
magnum_git_install_branch: 10e37bc1f4cb2ed2890d3aa2ee59eda3c12d5a6c  # HEAD as of 30.06.2019
magnum_git_project_group: magnum_all
magnum_git_track_branch: stable/stein

## Masakari service
masakari_git_repo: https://opendev.org/openstack/masakari
masakari_git_install_branch: df08881742a18c5100f59d06889120b277b98911  # HEAD as of 30.06.2019
masakari_git_project_group: masakari_api
masakari_git_track_branch: stable/stein

## Masakari monitors services
masakari_monitors_git_repo: https://opendev.org/openstack/masakari-monitors
masakari_monitors_git_install_branch: 77132bbdbda459177e815f6412924d70cbc5d87f  # HEAD as of 30.06.2019
masakari_monitors_git_project_group: masakari_monitor
masakari_monitors_git_track_branch: stable/stein

## Mistral service
mistral_git_repo: https://opendev.org/openstack/mistral
mistral_git_install_branch: 6ff82c316e9b2464eedd5a8df215101918ebff9b  # HEAD as of 30.06.2019
mistral_git_project_group: mistral_all
mistral_git_track_branch: stable/stein

## Trove service
trove_git_repo: https://opendev.org/openstack/trove
trove_git_install_branch: 26d1e5ad59eda795e5d1485730bd8a71d620e55c # HEAD as of 30.06.2019
trove_git_project_group: trove_all
trove_git_track_branch: stable/stein

## Horizon Trove dashboard plugin
trove_dashboard_git_repo: https://opendev.org/openstack/trove-dashboard
trove_dashboard_git_install_branch: ebb414093c2ccd0ef1a650f5110cac5d29934462 # HEAD as of 30.06.2019
trove_dashboard_git_project_group: horizon_all
trove_dashboard_git_track_branch: stable/stein


## Octavia service
octavia_git_repo: https://opendev.org/openstack/octavia
octavia_git_install_branch: d53010dc423867bc965069206b007a62fbb02475  # HEAD as of 30.06.2019
octavia_git_project_group: octavia_all
octavia_git_track_branch: stable/stein


## Panko service
panko_git_repo: https://opendev.org/openstack/panko
panko_git_install_branch: cc4fbd4704f89e570e36b7a5f652fadf68f3eb6f  # HEAD as of 30.06.2019
panko_git_project_group: panko_all
panko_git_track_branch: stable/stein


## Tacker service
tacker_git_repo: https://opendev.org/openstack/tacker
tacker_git_install_branch: aee46c86bbe87cbb8b6ebb3bd9b765aafd13df53 # HEAD as of 30.06.2019
tacker_git_project_group: tacker_all
tacker_git_track_branch: stable/stein


## Congress service
congress_git_repo: https://opendev.org/openstack/congress
congress_git_install_branch: b565c87d0224abb76d3710a4238df433f75ffbf3  # HEAD as of 30.06.2019
congress_git_package_name: openstack-congress
congress_git_project_group: congress_all
congress_git_track_branch: stable/stein

## Horizon Octavia dashboard plugin
octavia_dashboard_git_repo: https://opendev.org/openstack/octavia-dashboard
octavia_dashboard_git_install_branch: 13c01348f5275c7afe4130dc0a3b072d89cae4af  # HEAD as of 30.06.2019
octavia_dashboard_git_project_group: horizon_all
octavia_dashboard_git_track_branch: stable/stein


## Blazar service
blazar_git_repo: https://opendev.org/openstack/blazar
blazar_git_install_branch: 536ea887b96424d6a81e33b9fea576cdb2173d1d  # HEAD as of 30.06.2019
blazar_git_project_group: blazar_all
blazar_git_track_branch: stable/stein

## Blazar Nova Service
blazar_nova_git_repo: https://opendev.org/openstack/blazar-nova
blazar_nova_git_install_branch: 334965654ba3ce5a62a25ede5250c2e2c05c064d  # HEAD as of 30.06.2019
blazar_nova_git_project_group: blazar_all
blazar_nova_git_track_branch: stable/stein
