---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


## NOTICE on items in this file:
##   * If you use anything in the *._git_install_branch field that is not a TAG
##     make sure to leave an in-line comment as to "why".

## For the sake of anyone else editing this file:
##   * If you add services to this file please do so in alphabetical order.
##   * Every entry should be name spaced with the name of the client followed by an "_"
##   * All items with this file should be separated by `name_` note that the name of the
##     package should be one long name with no additional `_` separating it.


### Before this is shipped all of these services should have a tag set as the branch,
### or have a comment / reason attached to them as to why a tag can not work.


## Global Requirements
requirements_git_repo: https://git.openstack.org/openstack/requirements
requirements_git_install_branch: ocata-eol
requirements_git_dest: "/opt/requirements_{{ requirements_git_install_branch | replace('/', '_') }}"
requirements_git_track_branch: stable/ocata


## Aodh service
aodh_git_repo: https://git.openstack.org/openstack/aodh
aodh_git_install_branch: ocata-eol
aodh_git_dest: "/opt/aodh_{{ aodh_git_install_branch | replace('/', '_') }}"
aodh_git_project_group: aodh_all
aodh_git_track_branch: stable/ocata


## Barbican service
barbican_git_repo: https://git.openstack.org/openstack/barbican
barbican_git_install_branch: ocata-eol
barbican_git_dest: "/opt/barbican_{{ barbican_git_install_branch | replace('/', '_') }}"
barbican_git_project_group: barbican_all
barbican_git_track_branch: stable/ocata


## Ceilometer service
ceilometer_git_repo: https://git.openstack.org/openstack/ceilometer
ceilometer_git_install_branch: ocata-eol
ceilometer_git_dest: "/opt/ceilometer_{{ceilometer_git_install_branch | replace('/', '_') }}"
ceilometer_git_project_group: ceilometer_all
ceilometer_git_track_branch: stable/ocata


## Cinder service
cinder_git_repo: https://git.openstack.org/openstack/cinder
cinder_git_install_branch: ocata-eol
cinder_git_dest: "/opt/cinder_{{ cinder_git_install_branch | replace('/', '_') }}"
cinder_git_project_group: cinder_all
cinder_git_track_branch: stable/ocata


## Designate service
designate_git_repo: https://git.openstack.org/openstack/designate
designate_git_install_branch: ocata-eol # HEAD of "stable/ocata" as of 04.10.2018
designate_git_dest: "/opt/designate_{{ designate_git_install_branch | replace('/', '_') }}"
designate_git_project_group: designate_all
designate_git_track_branch: stable/ocata


## Horizon Designate dashboard plugin
designate_dashboard_git_repo: https://git.openstack.org/openstack/designate-dashboard
designate_dashboard_git_install_branch: ocata-eol # HEAD of "stable/ocata" as of 04.10.2018
designate_dashboard_git_dest: "/opt/designate_dashboard_{{ designate_dashboard_git_install_branch | replace('/', '_') }}"
designate_dashboard_git_project_group: horizon_all
designate_dashboard_git_track_branch: stable/ocata


## Dragonflow service
dragonflow_git_repo: https://git.openstack.org/openstack/dragonflow
dragonflow_git_install_branch: ocata-eol # HEAD of "stable/ocata" as of 04.10.2018
dragonflow_git_dest: "/opt/dragonflow_{{ dragonflow_git_install_branch | replace('/', '_') }}"
dragonflow_git_project_group: neutron_all
dragonflow_git_track_branch: stable/ocata


## Glance service
glance_git_repo: https://git.openstack.org/openstack/glance
glance_git_install_branch: ocata-eol # HEAD of "stable/ocata" as of 04.10.2018
glance_git_dest: "/opt/glance_{{ glance_git_install_branch | replace('/', '_') }}"
glance_git_project_group: glance_all
glance_git_track_branch: stable/ocata


## Heat service
heat_git_repo: https://git.openstack.org/openstack/heat
heat_git_install_branch: ocata-eol # HEAD of "stable/ocata" as of 04.10.2018
heat_git_dest: "/opt/heat_{{ heat_git_install_branch | replace('/', '_') }}"
heat_git_project_group: heat_all
heat_git_track_branch: stable/ocata


## Horizon service
horizon_git_repo: https://git.openstack.org/openstack/horizon
horizon_git_install_branch: ocata-eol # HEAD of "stable/ocata" as of 04.10.2018
horizon_git_dest: "/opt/horizon_{{ horizon_git_install_branch | replace('/', '_') }}"
horizon_git_project_group: horizon_all
horizon_git_track_branch: stable/ocata

## Horizon Ironic dashboard plugin
ironic_dashboard_git_repo: https://git.openstack.org/openstack/ironic-ui
ironic_dashboard_git_install_branch: ocata-eol # HEAD of "stable/ocata" as of 04.10.2018
ironic_dashboard_git_dest: "/opt/ironic_dashboard_{{ ironic_dashboard_git_install_branch | replace('/', '_') }}"
ironic_dashboard_git_project_group: horizon_all
ironic_dashboard_git_track_branch: stable/ocata

## Horizon Magnum dashboard plugin
magnum_dashboard_git_repo: https://git.openstack.org/openstack/magnum-ui
magnum_dashboard_git_install_branch: ocata-eol # HEAD of "stable/ocata" as of 04.10.2018
magnum_dashboard_git_dest: "/opt/magnum_dashboard_{{ magnum_dashboard_git_install_branch | replace('/', '_') }}"
magnum_dashboard_git_project_group: horizon_all
magnum_dashboard_git_track_branch: stable/ocata

## Horizon LBaaS dashboard plugin
neutron_lbaas_dashboard_git_repo: https://git.openstack.org/openstack/neutron-lbaas-dashboard
neutron_lbaas_dashboard_git_install_branch: ocata-eol # HEAD of "stable/ocata" as of 04.10.2018
neutron_lbaas_dashboard_git_dest: "/opt/neutron_lbaas_dashboard_{{ neutron_lbaas_dashboard_git_install_branch | replace('/', '_') }}"
neutron_lbaas_dashboard_git_project_group: horizon_all
neutron_lbaas_dashboard_git_track_branch: stable/ocata

## Horizon Sahara dashboard plugin
sahara_dashboard_git_repo: https://git.openstack.org/openstack/sahara-dashboard
sahara_dashboard_git_install_branch: ocata-eol # HEAD of "stable/ocata" as of 04.10.2018
sahara_dashboard_git_dest: "/opt/sahara_dashboard_{{ sahara_dashboard_git_install_branch | replace('/', '_') }}"
sahara_dashboard_git_project_group: horizon_all
sahara_dashboard_git_track_branch: stable/ocata

## Keystone service
keystone_git_repo: https://git.openstack.org/openstack/keystone
keystone_git_install_branch: ocata-eol # HEAD of "stable/ocata" as of 04.10.2018
keystone_git_dest: "/opt/keystone_{{ keystone_git_install_branch | replace('/', '_') }}"
keystone_git_project_group: keystone_all
keystone_git_track_branch: stable/ocata


## Neutron service
neutron_git_repo: https://git.openstack.org/openstack/neutron
neutron_git_install_branch: ocata-eol # HEAD of "stable/ocata" as of 04.10.2018
neutron_git_dest: "/opt/neutron_{{ neutron_git_install_branch | replace('/', '_') }}"
neutron_git_project_group: neutron_all
neutron_git_track_branch: stable/ocata

neutron_lbaas_git_repo: https://git.openstack.org/openstack/neutron-lbaas
neutron_lbaas_git_install_branch: ocata-eol # HEAD of "stable/ocata" as of 04.10.2018
neutron_lbaas_git_dest: "/opt/neutron_lbaas_{{ neutron_lbaas_git_install_branch | replace('/', '_') }}"
neutron_lbaas_git_project_group: neutron_all
neutron_lbaas_git_track_branch: stable/ocata

neutron_vpnaas_git_repo: https://git.openstack.org/openstack/neutron-vpnaas
neutron_vpnaas_git_install_branch: ocata-eol # HEAD of "stable/ocata" as of 04.10.2018
neutron_vpnaas_git_dest: "/opt/neutron_vpnaas_{{ neutron_vpnaas_git_install_branch | replace('/', '_') }}"
neutron_vpnaas_git_project_group: neutron_all
neutron_vpnaas_git_track_branch: stable/ocata

neutron_fwaas_git_repo: https://git.openstack.org/openstack/neutron-fwaas
neutron_fwaas_git_install_branch: ocata-eol # HEAD of "stable/ocata" as of 04.10.2018
neutron_fwaas_git_dest: "/opt/neutron_fwaas_{{ neutron_fwaas_git_install_branch | replace('/', '_') }}"
neutron_fwaas_git_project_group: neutron_all
neutron_fwaas_git_track_branch: stable/ocata

neutron_dynamic_routing_git_repo: https://git.openstack.org/openstack/neutron-dynamic-routing
neutron_dynamic_routing_git_install_branch: ocata-eol # HEAD of "stable/ocata" as of 04.10.2018
neutron_dynamic_routing_git_dest: "/opt/neutron_dynamic_routing_{{ neutron_dynamic_routing_git_install_branch | replace('/', '_') }}"
neutron_dynamic_routing_git_project_group: neutron_all
neutron_dynamic_routing_git_track_branch: stable/ocata

networking_calico_git_repo: https://git.openstack.org/openstack/networking-calico
networking_calico_git_install_branch: ocata-eol # HEAD of "master" as of 04.10.2018
networking_calico_git_project_group: neutron_all
networking_calico_git_track_branch: master

## Nova service
nova_git_repo: https://git.openstack.org/openstack/nova
nova_git_install_branch: ocata-eol # HEAD of "stable/ocata" as of 04.10.2018
nova_git_dest: "/opt/nova_{{ nova_git_install_branch | replace('/', '_') }}"
nova_git_project_group: nova_all
nova_git_track_branch: stable/ocata


## PowerVM Virt Driver
nova_powervm_git_repo: https://git.openstack.org/openstack/nova-powervm
nova_powervm_git_install_branch: ocata-eol # HEAD of "stable/ocata" as of 04.10.2018
nova_powervm_git_dest: "/opt/nova_powervm_{{ nova_powervm_git_install_branch | replace('/', '_') }}"
nova_powervm_git_project_group: nova_all
nova_powervm_git_track_branch: stable/ocata


## LXD Virt Driver
nova_lxd_git_repo: https://git.openstack.org/openstack/nova-lxd
nova_lxd_git_install_branch: ocata-eol # HEAD of "stable/ocata" as of 04.10.2018
nova_lxd_git_dest: "/opt/nova_lxd_{{ nova_lxd_git_install_branch | replace('/', '_') }}"
nova_lxd_git_project_group: nova_all
nova_lxd_git_track_branch: stable/ocata


## Sahara service
sahara_git_repo: https://git.openstack.org/openstack/sahara
sahara_git_install_branch: ocata-eol # HEAD of "stable/ocata" as of 04.10.2018
sahara_git_dest: "/opt/sahara_{{ sahara_git_install_branch | replace('/', '_') }}"
sahara_git_project_group: sahara_all
sahara_git_track_branch: stable/ocata


## Swift service
swift_git_repo: https://git.openstack.org/openstack/swift
swift_git_install_branch: ocata-eol # HEAD of "stable/ocata" as of 04.10.2018
swift_git_dest: "/opt/swift_{{ swift_git_install_branch | replace('/', '_') }}"
swift_git_project_group: swift_all
swift_git_track_branch: stable/ocata


## Swift3 middleware
swift_swift3_git_repo: https://git.openstack.org/openstack/swift3
swift_swift3_git_install_branch: ocata-eol # FROZEN HEAD of "master" as of 22.08.2018
swift_swift3_git_project_group: swift_all
swift_swift3_git_track_branch: None


## Ironic service
ironic_git_repo: https://git.openstack.org/openstack/ironic
ironic_git_install_branch: ocata-eol # HEAD of "stable/ocata" as of 04.10.2018
ironic_git_dest: "/opt/ironic_{{ ironic_git_install_branch | replace('/', '_') }}"
ironic_git_project_group: ironic_all
ironic_git_track_branch: stable/ocata

## Magnum service
magnum_git_repo: https://git.openstack.org/openstack/magnum
magnum_git_install_branch: ocata-eol # HEAD of "stable/ocata" as of 04.10.2018
magnum_git_dest: "/opt/magnum_{{ magnum_git_install_branch | replace('/', '_') }}"
magnum_git_project_group: magnum_all
magnum_git_track_branch: stable/ocata

## Trove service
trove_git_repo: https://git.openstack.org/openstack/trove
trove_git_install_branch: ocata-eol # HEAD of "stable/ocata" as of 04.10.2018
trove_git_dest: "/opt/trove_{{ trove_git_install_branch | replace('/', '_') }}"
trove_git_project_group: trove_all
trove_git_track_branch: stable/ocata

## Horizon Trove dashboard plugin
trove_dashboard_git_repo: https://git.openstack.org/openstack/trove-dashboard
trove_dashboard_git_install_branch: ocata-eol # HEAD of "stable/ocata" as of 04.10.2018
trove_dashboard_git_dest: "/opt/trove_dashboard_{{ trove_dashboard_git_install_branch | replace('/', '_') }}"
trove_dashboard_git_project_group: horizon_all
trove_dashboard_git_track_branch: stable/ocata
