---
# Copyright 2018, Jean-Philippe Evrard <jean-philippe@evrard.me>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

### HEAD as of 21.02.2022 ###

tempest_git_repo: https://opendev.org/openstack/tempest
tempest_git_install_branch: ca03d2b504eabb19aff56ea6673eeb9a7d7b22fe
tempest_git_track_branch: master

tempest_plugin_barbican_git_repo: https://opendev.org/openstack/barbican-tempest-plugin
tempest_plugin_barbican_git_install_branch: 9fe096e1422c7c884b94166763b4857b5abcea30
tempest_plugin_barbican_git_track_branch: master

tempest_plugin_cinder_git_repo: https://opendev.org/openstack/cinder-tempest-plugin
tempest_plugin_cinder_git_install_branch: a3b2272871db9ceacf99324f980f12af716f7b69
tempest_plugin_cinder_git_track_branch: master

tempest_plugin_cloudkitty_git_repo: https://opendev.org/openstack/cloudkitty-tempest-plugin
tempest_plugin_cloudkitty_git_install_branch: 03d07b84ef4dffa685718ec4124d283e47ffc5e1
tempest_plugin_cloudkitty_git_track_branch: master

tempest_plugin_designate_git_repo: https://opendev.org/openstack/designate-tempest-plugin
tempest_plugin_designate_git_install_branch: 45b3d39d422dd1062abfe849f15a4aeb37b3d462
tempest_plugin_designate_git_track_branch: master

tempest_plugin_heat_git_repo: https://opendev.org/openstack/heat-tempest-plugin
tempest_plugin_heat_git_install_branch: ba43685c131d6387779ed35f5bf61fc86667a728
tempest_plugin_heat_git_track_branch: master

tempest_plugin_ironic_git_repo: https://opendev.org/openstack/ironic-tempest-plugin
tempest_plugin_ironic_git_install_branch: fd43dcc3b607603978c51ca605dc70e1b784d782
tempest_plugin_ironic_git_track_branch: master

tempest_plugin_keystone_git_repo: https://opendev.org/openstack/keystone-tempest-plugin
tempest_plugin_keystone_git_install_branch: 4eff632695fe79a5d78f400dca3ceab663c83788
tempest_plugin_keystone_git_track_branch: master

tempest_plugin_magnum_git_repo: https://opendev.org/openstack/magnum-tempest-plugin
tempest_plugin_magnum_git_install_branch: 9b9eacfa515db07874b6489a9ce1785965d684fb
tempest_plugin_magnum_git_track_branch: master

tempest_plugin_manila_git_repo: https://opendev.org/openstack/manila-tempest-plugin
tempest_plugin_manila_git_install_branch: 73e0b6fdc450b7539bf6a97349f5774177ffb24a
tempest_plugin_manila_git_track_branch: master

tempest_plugin_murano_git_repo: https://opendev.org/openstack/murano-tempest-plugin
tempest_plugin_murano_git_install_branch: e3ff4504b590a7b170cd0dd5406909afeafd3f55
tempest_plugin_murano_git_track_branch: master

tempest_plugin_neutron_git_repo: https://opendev.org/openstack/neutron-tempest-plugin
tempest_plugin_neutron_git_install_branch: d2ecabb4fc1f35aa6374260f8b89cea0c467534b
tempest_plugin_neutron_git_track_branch: master

tempest_plugin_novajoin_git_repo: https://opendev.org/x/novajoin-tempest-plugin
tempest_plugin_novajoin_git_install_branch: b2e548518a8893562ed111fe66f5937603f5ec5d
tempest_plugin_novajoin_git_track_branch: master

tempest_plugin_octavia_git_repo: https://opendev.org/openstack/octavia-tempest-plugin
tempest_plugin_octavia_git_install_branch: a3a95b132eac0b37fe85835d89b195ac08436501
tempest_plugin_octavia_git_track_branch: master

tempest_plugin_senlin_git_repo: https://opendev.org/openstack/senlin-tempest-plugin
tempest_plugin_senlin_git_install_branch: 7a8121fc5f51f17f9f56a7d73739ed4378ba264f
tempest_plugin_senlin_git_track_branch: master

tempest_plugin_sahara_git_repo: https://opendev.org/openstack/sahara-tests
tempest_plugin_sahara_git_install_branch: 98063d3fd93ce77cb3ecbbd33868bbe5dd3a6865
tempest_plugin_sahara_git_track_branch: master

tempest_plugin_telemetry_git_repo: https://opendev.org/openstack/telemetry-tempest-plugin
tempest_plugin_telemetry_git_install_branch: 6cd5f0274d73bb7a1024f99f609fd74907674f65
tempest_plugin_telemetry_git_track_branch: master

tempest_plugin_trove_git_repo: https://opendev.org/openstack/trove-tempest-plugin
tempest_plugin_trove_git_install_branch: 5de39645ed4c5f12526863d1546769dce74fcb08
tempest_plugin_trove_git_track_branch: master

tempest_plugin_zaqar_git_repo: https://opendev.org/openstack/zaqar-tempest-plugin
tempest_plugin_zaqar_git_install_branch: 3813c99e501a1f67a9cbde751cf71747a61f6786
tempest_plugin_zaqar_git_track_branch: master

tempest_plugin_zun_git_repo: https://opendev.org/openstack/zun-tempest-plugin
tempest_plugin_zun_git_install_branch: 6d2529583bc32bcb84e447d5524af1c900cc2845
tempest_plugin_zun_git_track_branch: master
