---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


## NOTICE on items in this file:
##   * If you use anything in the *._git_install_branch field that is not a TAG
##     make sure to leave an in-line comment as to "why".

## For the sake of anyone else editing this file:
##   * If you add services to this file please do so in alphabetical order.
##   * Every entry should be name spaced with the name of the client followed by an "_"
##   * All items with this file should be separated by `name_` note that the name of the
##     package should be one long name with no additional `_` separating it.


### Before this is shipped all of these services should have a tag set as the branch,
### or have a comment / reason attached to them as to why a tag can not work.


## Global Requirements
requirements_git_repo: https://git.openstack.org/openstack/requirements
requirements_git_install_branch: 3562f380493bcea4b98d8da11a1718250b2bda6b # HEAD of "stable/rocky" as of 23.12.2018
requirements_git_track_branch: stable/rocky


## Aodh service
aodh_git_repo: https://git.openstack.org/openstack/aodh
aodh_git_install_branch: ae5e710cd5ade867ebd0e6666bad95f82d130210 # HEAD of "stable/rocky" as of 23.12.2018
aodh_git_project_group: aodh_all
aodh_git_track_branch: stable/rocky


## Barbican service
barbican_git_repo: https://git.openstack.org/openstack/barbican
barbican_git_install_branch: 0a1a9917e791d0c6fc8534a052700af5f5cbe9d0 # HEAD of "stable/rocky" as of 23.12.2018
barbican_git_project_group: barbican_all
barbican_git_track_branch: stable/rocky


## Ceilometer service
ceilometer_git_repo: https://git.openstack.org/openstack/ceilometer
ceilometer_git_install_branch: 9c9110278a9521dc821b80e6c4c23bc6d01b6cf9 # HEAD of "stable/rocky" as of 23.12.2018
ceilometer_git_project_group: all
ceilometer_git_track_branch: stable/rocky


## Cinder service
cinder_git_repo: https://git.openstack.org/openstack/cinder
cinder_git_install_branch: 83d2df3a67020f20eed7004946211af9b4835dde # HEAD of "stable/rocky" as of 23.12.2018
cinder_git_project_group: cinder_all
cinder_git_track_branch: stable/rocky


## Designate service
designate_git_repo: https://git.openstack.org/openstack/designate
designate_git_install_branch: af1bb8a36a704bb1a226fe5154f828e152ef23e1 # HEAD of "stable/rocky" as of 23.12.2018
designate_git_project_group: designate_all
designate_git_track_branch: stable/rocky


## Horizon Designate dashboard plugin
designate_dashboard_git_repo: https://git.openstack.org/openstack/designate-dashboard
designate_dashboard_git_install_branch: faa67c87ad3cd5563da722f13b3adaee5bfe350f # HEAD of "stable/rocky" as of 23.12.2018
designate_dashboard_git_project_group: horizon_all
designate_dashboard_git_track_branch: stable/rocky


## Dragonflow service
# please update the branch (sha and update the comment) when stable/rocky is branched on this repo.
dragonflow_git_repo: https://git.openstack.org/openstack/dragonflow
dragonflow_git_install_branch: 945b1e368c651ffa3655f42df724d9f13a7b6b96 # FROZEN HEAD of "master" as of 17.08.2018
dragonflow_git_project_group: neutron_all
dragonflow_git_track_branch: None


## Glance service
glance_git_repo: https://git.openstack.org/openstack/glance
glance_git_install_branch: d2bb38d58bac9c22c2a8f27739720db43f3af290 # HEAD of "stable/rocky" as of 23.12.2018
glance_git_project_group: glance_all
glance_git_track_branch: stable/rocky


## Heat service
heat_git_repo: https://git.openstack.org/openstack/heat
heat_git_install_branch: f91ca4a22d87f4010134163283934e673a8e5f7e # HEAD of "stable/rocky" as of 23.12.2018
heat_git_project_group: heat_all
heat_git_track_branch: stable/rocky

## Horizon Heat dashboard plugin
# please update the branch (sha and update the comment) when stable/rocky is branched on this repo.
heat_dashboard_git_repo: https://git.openstack.org/openstack/heat-dashboard
heat_dashboard_git_install_branch: bc7f5068bbb6f7974eaffa2d865a859ff0fd0069 # FROZEN HEAD of "master" as of 17.08.2018
heat_dashboard_git_project_group: horizon_all
heat_dashboard_git_track_branch: None

## Horizon service
horizon_git_repo: https://git.openstack.org/openstack/horizon
horizon_git_install_branch: 85fef71c0dfff3b7f816add638ad2d916a2ffe38 # HEAD of "stable/rocky" as of 23.12.2018
horizon_git_project_group: horizon_all
horizon_git_track_branch: stable/rocky

## Horizon Ironic dashboard plugin
ironic_dashboard_git_repo: https://git.openstack.org/openstack/ironic-ui
ironic_dashboard_git_install_branch: c700f3a613f3d78875caf7588e7bdf42a5db83cb # HEAD of "stable/rocky" as of 23.12.2018
ironic_dashboard_git_project_group: horizon_all
ironic_dashboard_git_track_branch: stable/rocky

## Horizon Magnum dashboard plugin
magnum_dashboard_git_repo: https://git.openstack.org/openstack/magnum-ui
magnum_dashboard_git_install_branch: 2e9cb253eaee45a57f07369e432369dbff8fc173 # HEAD of "stable/rocky" as of 23.12.2018
magnum_dashboard_git_project_group: horizon_all
magnum_dashboard_git_track_branch: stable/rocky

## Horizon LBaaS dashboard plugin
neutron_lbaas_dashboard_git_repo: https://git.openstack.org/openstack/neutron-lbaas-dashboard
neutron_lbaas_dashboard_git_install_branch: 84fd20a474e8165ddbf5cf4bd14b7eb7da63ed41 # HEAD of "stable/rocky" as of 23.12.2018
neutron_lbaas_dashboard_git_project_group: horizon_all
neutron_lbaas_dashboard_git_track_branch: stable/rocky

## Horizon FWaaS dashboard plugin
neutron_fwaas_dashboard_git_repo: https://git.openstack.org//openstack/neutron-fwaas-dashboard
neutron_fwaas_dashboard_git_install_branch: 4adf5599211ef90696da94b2fee3aac730f3b7bc # HEAD of "stable/rocky" as of 23.12.2018
neutron_fwaas_dashboard_git_project_group: horizon_all
neutron_fwaas_dashboard_git_track_branch: stable/rocky

## Horizon Sahara dashboard plugin
sahara_dashboard_git_repo: https://git.openstack.org/openstack/sahara-dashboard
sahara_dashboard_git_install_branch: 6e3f7538ce7779612d8e82b069597c06c2225a77 # HEAD of "stable/rocky" as of 23.12.2018
sahara_dashboard_git_project_group: horizon_all
sahara_dashboard_git_track_branch: stable/rocky


## Keystone service
keystone_git_repo: https://git.openstack.org/openstack/keystone
keystone_git_install_branch: b8500aecb938594e95f8e4734826ae146c9bc379 # HEAD of "stable/rocky" as of 23.12.2018
keystone_git_project_group: keystone_all
keystone_git_track_branch: stable/rocky


## Neutron service
neutron_git_repo: https://git.openstack.org/openstack/neutron
neutron_git_install_branch: 7382f39313fc0a69dd973cb13117a2f0597d3f3e # HEAD of "stable/rocky" as of 23.12.2018
neutron_git_project_group: neutron_all
neutron_git_track_branch: stable/rocky

neutron_lbaas_git_repo: https://git.openstack.org/openstack/neutron-lbaas
neutron_lbaas_git_install_branch: 1353bad713fd97418a9984016da49df8cfa8825b # HEAD of "stable/rocky" as of 23.12.2018
neutron_lbaas_git_project_group: neutron_all
neutron_lbaas_git_track_branch: stable/rocky

neutron_vpnaas_git_repo: https://git.openstack.org/openstack/neutron-vpnaas
neutron_vpnaas_git_install_branch: 0876f4dfe7e2f57305110e035efa753bfb711a3f # HEAD of "stable/rocky" as of 23.12.2018
neutron_vpnaas_git_project_group: neutron_all
neutron_vpnaas_git_track_branch: stable/rocky

neutron_fwaas_git_repo: https://git.openstack.org/openstack/neutron-fwaas
neutron_fwaas_git_install_branch: 5ece265b65247ee81a9335d5a685fa9f0a68b0fc # HEAD of "stable/rocky" as of 23.12.2018
neutron_fwaas_git_project_group: neutron_all
neutron_fwaas_git_track_branch: stable/rocky

neutron_dynamic_routing_git_repo: https://git.openstack.org/openstack/neutron-dynamic-routing
neutron_dynamic_routing_git_install_branch: ae3a01ca1fd6270fc27b3c6bae11afc0f17563d5 # HEAD of "stable/rocky" as of 23.12.2018
neutron_dynamic_routing_git_project_group: neutron_all
neutron_dynamic_routing_git_track_branch: stable/rocky

# Networking Calico is following master
networking_calico_git_repo: https://git.openstack.org/openstack/networking-calico
networking_calico_git_install_branch: 47a453b276edd35d34869cf3036c0c1706c258b5 # HEAD of "master" as of 23.12.2018
networking_calico_git_project_group: neutron_all
networking_calico_git_track_branch: stable/rocky

networking_odl_git_repo: https://git.openstack.org/openstack/networking-odl
networking_odl_git_install_branch: 1cef1f0939a405eea4cb87e712794e8fa26b5166 # HEAD of "stable/rocky" as of 23.12.2018
networking_odl_git_project_group: neutron_all
networking_odl_git_track_branch: stable/rocky

networking_ovn_git_repo: https://git.openstack.org/openstack/networking-ovn
networking_ovn_git_install_branch: 726820ad3ceb8aa16471c906d48aa3b9efb2683b # HEAD of "stable/rocky" as of 23.12.2018
networking_ovn_git_project_group: neutron_all
networking_ovn_git_track_branch: stable/rocky

# BGPVPN is frozen until further notice due to
# https://github.com/openstack/networking-bgpvpn/commit/e9a0ea199b47f76f69545e04bdb4db44869c388b#diff-b4ef698db8ca845e5845c4618278f29a
networking_bgpvpn_git_repo: https://git.openstack.org/openstack/networking-bgpvpn
networking_bgpvpn_git_install_branch: 3b93ddacd390d92fb144e5660324d4da064ad9a4 # FROZEN HEAD of "stable/rocky" as of 31.03.2018
networking_bgpvpn_git_project_group: neutron_all
networking_bgpvpn_git_track_branch: None

networking_sfc_git_repo: https://git.openstack.org/openstack/networking-sfc
networking_sfc_git_install_branch: f0eddef3d53bbad417038f9d32b196ace2ebd0b2 # HEAD of "stable/rocky" as of 23.12.2018
networking_sfc_git_project_group: neutron_all
networking_sfc_git_track_branch: stable/rocky


## Nova service
nova_git_repo: https://git.openstack.org/openstack/nova
nova_git_install_branch: 734df042a19afa0f3355f231442e9e919ddbd706 # HEAD of "stable/rocky" as of 23.12.2018
nova_git_project_group: nova_all
nova_git_track_branch: stable/rocky


## PowerVM Virt Driver
nova_powervm_git_repo: https://git.openstack.org/openstack/nova-powervm
nova_powervm_git_install_branch: 984b122668161703eee33918d570c61ae9c5b1ca # HEAD of "stable/rocky" as of 23.12.2018
nova_powervm_git_project_group: nova_all
nova_powervm_git_track_branch: stable/rocky


## LXD Virt Driver
# please update the branch (sha and update the comment) when stable/rocky is branched on this repo.
nova_lxd_git_repo: https://git.openstack.org/openstack/nova-lxd
nova_lxd_git_install_branch: bc8d540c95b3209321658000fd74b0e5065a7ee2 # FROZEN HEAD of "master" as of 17.08.2018
nova_lxd_git_project_group: nova_all
nova_lxd_git_track_branch: None


## Sahara service
sahara_git_repo: https://git.openstack.org/openstack/sahara
sahara_git_install_branch: 9ae675fdc83bf51fa3d16880ff978eecee458180 # HEAD of "stable/rocky" as of 23.12.2018
sahara_git_project_group: sahara_all
sahara_git_track_branch: stable/rocky


## Swift service
swift_git_repo: https://git.openstack.org/openstack/swift
swift_git_install_branch: 7fdf66ab70da705774a4ae9c328a3e762bb2f3b4 # HEAD of "stable/rocky" as of 23.12.2018
swift_git_project_group: swift_all
swift_git_track_branch: stable/rocky


## Swift3 middleware
# please remove this when swift role is configured without this middleware (and uses swift code only)
swift_swift3_git_repo: https://git.openstack.org/openstack/swift3
swift_swift3_git_install_branch: 90db5d1510b2a770387961e7bf0fbeae8101ba45 # FROZEN HEAD of "master" as of 17.08.2018
swift_swift3_git_project_group: swift_all
swift_swift3_git_track_branch: None


## Ironic service
ironic_git_repo: https://git.openstack.org/openstack/ironic
ironic_git_install_branch: f55ae7e03d616cd1286d74b7ca3a235e64b1233e # HEAD of "stable/rocky" as of 23.12.2018
ironic_git_project_group: ironic_all
ironic_git_track_branch: stable/rocky


## Magnum service
magnum_git_repo: https://git.openstack.org/openstack/magnum
magnum_git_install_branch: 660299e7b3335323e287bc687054f5616fe271c3 # HEAD of "stable/rocky" as of 23.12.2018
magnum_git_project_group: magnum_all
magnum_git_track_branch: stable/rocky


## Trove service
trove_git_repo: https://git.openstack.org/openstack/trove
trove_git_install_branch: 2953676e81fc22099e72ea7d0f27002a59aa779f # HEAD of "stable/rocky" as of 23.12.2018
trove_git_project_group: trove_all
trove_git_track_branch: stable/rocky

## Horizon Trove dashboard plugin
trove_dashboard_git_repo: https://git.openstack.org/openstack/trove-dashboard
trove_dashboard_git_install_branch: c6482d8f7ebeb980a99cc89593245be381675984 # HEAD of "stable/rocky" as of 23.12.2018
trove_dashboard_git_project_group: horizon_all
trove_dashboard_git_track_branch: stable/rocky


## Octavia service
octavia_git_repo: https://git.openstack.org/openstack/octavia
octavia_git_install_branch: ec4c88e23ebeb786491158682f9a7dd42928f97a # HEAD of "stable/rocky" as of 23.12.2018
octavia_git_project_group: octavia_all
octavia_git_track_branch: stable/rocky


## Tacker service
tacker_git_repo: https://git.openstack.org/openstack/tacker
tacker_git_install_branch: 279b1a2840b9f28377476e0d11ca83ce2e88a0b2 # HEAD of "stable/rocky" as of 23.12.2018
tacker_git_project_group: tacker_all
tacker_git_track_branch: stable/rocky

## Congress service
congress_git_repo: https://git.openstack.org/openstack/congress
congress_git_install_branch: 6862ac9f356a5403e1e37050e12f032f661bae96 # HEAD of "stable/rocky" as of 23.12.2018
congress_git_project_group: congress_all
congress_git_track_branch: stable/rocky

## Horizon Octavia dashboard plugin
octavia_dashboard_git_repo: https://git.openstack.org/openstack/octavia-dashboard
octavia_dashboard_git_install_branch: 80766f9390492c24de38911d7240c5490c7ef562 # HEAD of "stable/rocky" as of 23.12.2018
octavia_dashboard_git_project_group: horizon_all
octavia_dashboard_git_track_branch: stable/rocky
