---
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

## Main
# RPC
oslomsg_rpc_transport: rabbit
oslomsg_rpc_port: "{{ rabbitmq_port }}"
oslomsg_rpc_servers: "{{ rabbitmq_servers }}"
oslomsg_rpc_use_ssl: "{{ rabbitmq_use_ssl }}"
oslomsg_rpc_host_group: "{{ rabbitmq_host_group }}"
oslomsg_rpc_ssl_param: "{{ (oslomsg_rpc_use_ssl | bool) | ternary(1, 0) }}"

# Notify
oslomsg_notify_transport: rabbit
oslomsg_notify_port: "{{ rabbitmq_port }}"
oslomsg_notify_servers: "{{ rabbitmq_servers }}"
oslomsg_notify_use_ssl: "{{ rabbitmq_use_ssl }}"
oslomsg_notify_host_group: "{{ rabbitmq_host_group }}"
oslomsg_notify_ssl_param: "{{ (oslomsg_notify_use_ssl | bool) | ternary(1, 0) }}"

## AODH
aodh_oslomsg_rpc_userid: aodh
aodh_oslomsg_rpc_vhost: /aodh
aodh_oslomsg_rpc_transport: "{{ oslomsg_rpc_transport }}"
aodh_oslomsg_rpc_port: "{{ oslomsg_rpc_port }}"
aodh_oslomsg_rpc_servers: "{{ oslomsg_rpc_servers }}"
aodh_oslomsg_rpc_use_ssl: "{{ oslomsg_rpc_use_ssl }}"
aodh_oslomsg_rpc_host_group: "{{ oslomsg_rpc_host_group }}"
aodh_oslomsg_notify_userid: aodh
aodh_oslomsg_notify_vhost: /aodh
aodh_oslomsg_notify_transport: "{{ oslomsg_notify_transport }}"
aodh_oslomsg_notify_port: "{{ oslomsg_notify_port }}"
aodh_oslomsg_notify_servers: "{{ oslomsg_notify_servers }}"
aodh_oslomsg_notify_use_ssl: "{{ oslomsg_notify_use_ssl }}"
aodh_oslomsg_notify_host_group: "{{ oslomsg_notify_host_group }}"

## Barbican
barbican_oslomsg_rpc_userid: barbican
barbican_oslomsg_rpc_vhost: /barbican
barbican_oslomsg_rpc_transport: "{{ oslomsg_rpc_transport }}"
barbican_oslomsg_rpc_port: "{{ oslomsg_rpc_port }}"
barbican_oslomsg_rpc_servers: "{{ oslomsg_rpc_servers }}"
barbican_oslomsg_rpc_use_ssl: "{{ oslomsg_rpc_use_ssl }}"
barbican_oslomsg_rpc_host_group: "{{ oslomsg_rpc_host_group }}"
barbican_oslomsg_notify_userid: barbican
barbican_oslomsg_notify_vhost: /barbican
barbican_oslomsg_notify_transport: "{{ oslomsg_notify_transport }}"
barbican_oslomsg_notify_port: "{{ oslomsg_notify_port }}"
barbican_oslomsg_notify_servers: "{{ oslomsg_notify_servers }}"
barbican_oslomsg_notify_use_ssl: "{{ oslomsg_notify_use_ssl }}"
barbican_oslomsg_notify_host_group: "{{ oslomsg_notify_host_group }}"
# Shim to remove when wiring is done in barbican role
barbican_rabbitmq_host_group: "{{ oslomsg_rpc_host_group }}"
barbican_rabbitmq_port: "{{ oslomsg_rpc_port }}"
barbican_rabbitmq_servers: "{{ oslomsg_rpc_servers }}"
barbican_rabbitmq_use_ssl: "{{ oslomsg_rpc_use_ssl }}"
barbican_rabbitmq_userid: "{{ barbican_oslomsg_rpc_userid }}"
barbican_rabbitmq_vhost: "{{ barbican_oslomsg_rpc_vhost }}"

## Ceilometer
ceilometer_oslomsg_rpc_userid: ceilometer
ceilometer_oslomsg_rpc_vhost: /ceilometer
ceilometer_oslomsg_rpc_transport: "{{ oslomsg_rpc_transport }}"
ceilometer_oslomsg_rpc_port: "{{ oslomsg_rpc_port }}"
ceilometer_oslomsg_rpc_servers: "{{ oslomsg_rpc_servers }}"
ceilometer_oslomsg_rpc_use_ssl: "{{ oslomsg_rpc_use_ssl }}"
ceilometer_oslomsg_rpc_host_group: "{{ oslomsg_rpc_host_group }}"
ceilometer_oslomsg_notify_userid: ceilometer
ceilometer_oslomsg_notify_vhost: /ceilometer
ceilometer_oslomsg_notify_transport: "{{ oslomsg_notify_transport }}"
ceilometer_oslomsg_notify_port: "{{ oslomsg_notify_port }}"
ceilometer_oslomsg_notify_servers: "{{ oslomsg_notify_servers }}"
ceilometer_oslomsg_notify_use_ssl: "{{ oslomsg_notify_use_ssl }}"
ceilometer_oslomsg_notify_host_group: "{{ oslomsg_notify_host_group }}"
# Shim to remove when wiring is done in ceilometer role
ceilometer_rabbitmq_host_group: "{{ oslomsg_rpc_host_group }}"
ceilometer_rabbitmq_port: "{{ oslomsg_rpc_port }}"
ceilometer_rabbitmq_servers: "{{ oslomsg_rpc_servers }}"
ceilometer_rabbitmq_use_ssl: "{{ oslomsg_rpc_use_ssl }}"
ceilometer_rabbitmq_userid: "{{ ceilometer_oslomsg_rpc_userid }}"
ceilometer_rabbitmq_vhost: "{{ ceilometer_oslomsg_rpc_vhost }}"

## Cinder
cinder_oslomsg_rpc_userid: cinder
cinder_oslomsg_rpc_vhost: /cinder
cinder_oslomsg_rpc_transport: "{{ oslomsg_rpc_transport }}"
cinder_oslomsg_rpc_port: "{{ oslomsg_rpc_port }}"
cinder_oslomsg_rpc_servers: "{{ oslomsg_rpc_servers }}"
cinder_oslomsg_rpc_use_ssl: "{{ oslomsg_rpc_use_ssl }}"
cinder_oslomsg_rpc_host_group: "{{ oslomsg_rpc_host_group }}"
cinder_oslomsg_notify_userid: cinder
cinder_oslomsg_notify_vhost: /cinder
cinder_oslomsg_notify_transport: "{{ oslomsg_notify_transport }}"
cinder_oslomsg_notify_port: "{{ oslomsg_notify_port }}"
cinder_oslomsg_notify_servers: "{{ oslomsg_notify_servers }}"
cinder_oslomsg_notify_use_ssl: "{{ oslomsg_notify_use_ssl }}"
cinder_oslomsg_notify_host_group: "{{ oslomsg_notify_host_group }}"
# Shim to remove when wiring is done in cinder role
cinder_rabbitmq_host_group: "{{ oslomsg_rpc_host_group }}"
cinder_rabbitmq_port: "{{ oslomsg_rpc_port }}"
cinder_rabbitmq_servers: "{{ oslomsg_rpc_servers }}"
cinder_rabbitmq_use_ssl: "{{ oslomsg_rpc_use_ssl }}"
cinder_rabbitmq_userid: "{{ cinder_oslomsg_rpc_userid }}"
cinder_rabbitmq_vhost: "{{ cinder_oslomsg_rpc_vhost }}"

## Designate
designate_oslomsg_rpc_userid: designate
designate_oslomsg_rpc_vhost: /designate
designate_oslomsg_rpc_transport: "{{ oslomsg_rpc_transport }}"
designate_oslomsg_rpc_port: "{{ oslomsg_rpc_port }}"
designate_oslomsg_rpc_servers: "{{ oslomsg_rpc_servers }}"
designate_oslomsg_rpc_use_ssl: "{{ oslomsg_rpc_use_ssl }}"
designate_oslomsg_rpc_host_group: "{{ oslomsg_rpc_host_group }}"
designate_oslomsg_notify_userid: designate
designate_oslomsg_notify_vhost: /designate
designate_oslomsg_notify_transport: "{{ oslomsg_notify_transport }}"
designate_oslomsg_notify_port: "{{ oslomsg_notify_port }}"
designate_oslomsg_notify_servers: "{{ oslomsg_notify_servers }}"
designate_oslomsg_notify_use_ssl: "{{ oslomsg_notify_use_ssl }}"
designate_oslomsg_notify_host_group: "{{ oslomsg_notify_host_group }}"
# Shim to remove when wiring is done in designate role
designate_rabbitmq_host_group: "{{ oslomsg_rpc_host_group }}"
designate_rabbitmq_port: "{{ oslomsg_rpc_port }}"
designate_rabbitmq_servers: "{{ oslomsg_rpc_servers }}"
designate_rabbitmq_use_ssl: "{{ oslomsg_rpc_use_ssl }}"
designate_rabbitmq_userid: "{{ designate_oslomsg_rpc_userid }}"
designate_rabbitmq_vhost: "{{ designate_oslomsg_rpc_vhost }}"

## Heat
heat_oslomsg_rpc_userid: heat
heat_oslomsg_rpc_vhost: /heat
heat_oslomsg_rpc_transport: "{{ oslomsg_rpc_transport }}"
heat_oslomsg_rpc_port: "{{ oslomsg_rpc_port }}"
heat_oslomsg_rpc_servers: "{{ oslomsg_rpc_servers }}"
heat_oslomsg_rpc_use_ssl: "{{ oslomsg_rpc_use_ssl }}"
heat_oslomsg_rpc_host_group: "{{ oslomsg_rpc_host_group }}"
heat_oslomsg_notify_userid: heat
heat_oslomsg_notify_vhost: /heat
heat_oslomsg_notify_transport: "{{ oslomsg_notify_transport }}"
heat_oslomsg_notify_port: "{{ oslomsg_notify_port }}"
heat_oslomsg_notify_servers: "{{ oslomsg_notify_servers }}"
heat_oslomsg_notify_use_ssl: "{{ oslomsg_notify_use_ssl }}"
heat_oslomsg_notify_host_group: "{{ oslomsg_notify_host_group }}"

## Ironic
ironic_oslomsg_rpc_userid: ironic
ironic_oslomsg_rpc_vhost: /ironic
ironic_oslomsg_rpc_transport: "{{ oslomsg_rpc_transport }}"
ironic_oslomsg_rpc_port: "{{ oslomsg_rpc_port }}"
ironic_oslomsg_rpc_servers: "{{ oslomsg_rpc_servers }}"
ironic_oslomsg_rpc_use_ssl: "{{ oslomsg_rpc_use_ssl }}"
ironic_oslomsg_rpc_host_group: "{{ oslomsg_rpc_host_group }}"
ironic_oslomsg_notify_userid: ironic
ironic_oslomsg_notify_vhost: /ironic
ironic_oslomsg_notify_transport: "{{ oslomsg_notify_transport }}"
ironic_oslomsg_notify_port: "{{ oslomsg_notify_port }}"
ironic_oslomsg_notify_servers: "{{ oslomsg_notify_servers }}"
ironic_oslomsg_notify_use_ssl: "{{ oslomsg_notify_use_ssl }}"
ironic_oslomsg_notify_host_group: "{{ oslomsg_notify_host_group }}"

## Keystone
keystone_oslomsg_rpc_userid: keystone
keystone_oslomsg_rpc_vhost: /keystone
keystone_oslomsg_rpc_transport: "{{ oslomsg_rpc_transport }}"
keystone_oslomsg_rpc_port: "{{ oslomsg_rpc_port }}"
keystone_oslomsg_rpc_servers: "{{ oslomsg_rpc_servers }}"
keystone_oslomsg_rpc_use_ssl: "{{ oslomsg_rpc_use_ssl }}"
keystone_oslomsg_rpc_host_group: "{{ oslomsg_rpc_host_group }}"
keystone_oslomsg_notify_userid: keystone
keystone_oslomsg_notify_vhost: /keystone
keystone_oslomsg_notify_transport: "{{ oslomsg_notify_transport }}"
keystone_oslomsg_notify_port: "{{ oslomsg_notify_port }}"
keystone_oslomsg_notify_servers: "{{ oslomsg_notify_servers }}"
keystone_oslomsg_notify_use_ssl: "{{ oslomsg_notify_use_ssl }}"
keystone_oslomsg_notify_host_group: "{{ oslomsg_notify_host_group }}"
# Shim until upgrade is fixed
keystone_rabbitmq_host_group: "{{ oslomsg_rpc_host_group }}"
keystone_rabbitmq_port: "{{ oslomsg_rpc_port }}"
keystone_rabbitmq_servers: "{{ oslomsg_rpc_servers }}"
keystone_rabbitmq_use_ssl: "{{ oslomsg_rpc_use_ssl }}"
keystone_rabbitmq_userid: "{{ keystone_oslomsg_rpc_userid }}"
keystone_rabbitmq_vhost: "{{ keystone_oslomsg_rpc_vhost }}"

## Magnum
magnum_oslomsg_rpc_userid: magnum
magnum_oslomsg_rpc_vhost: /magnum
magnum_oslomsg_rpc_transport: "{{ oslomsg_rpc_transport }}"
magnum_oslomsg_rpc_port: "{{ oslomsg_rpc_port }}"
magnum_oslomsg_rpc_servers: "{{ oslomsg_rpc_servers }}"
magnum_oslomsg_rpc_use_ssl: "{{ oslomsg_rpc_use_ssl }}"
magnum_oslomsg_rpc_host_group: "{{ oslomsg_rpc_host_group }}"
magnum_oslomsg_notify_userid: magnum
magnum_oslomsg_notify_vhost: /magnum
magnum_oslomsg_notify_transport: "{{ oslomsg_notify_transport }}"
magnum_oslomsg_notify_port: "{{ oslomsg_notify_port }}"
magnum_oslomsg_notify_servers: "{{ oslomsg_notify_servers }}"
magnum_oslomsg_notify_use_ssl: "{{ oslomsg_notify_use_ssl }}"
magnum_oslomsg_notify_host_group: "{{ oslomsg_notify_host_group }}"
# Shim until role is fixed
magnum_rabbitmq_host_group: "{{ oslomsg_rpc_host_group }}"
magnum_rabbitmq_port: "{{ oslomsg_rpc_port }}"
magnum_rabbitmq_servers: "{{ oslomsg_rpc_servers }}"
magnum_rabbitmq_use_ssl: "{{ oslomsg_rpc_use_ssl }}"
magnum_rabbitmq_userid: "{{ magnum_oslomsg_rpc_userid }}"
magnum_rabbitmq_vhost: "{{ magnum_oslomsg_rpc_vhost }}"

## Neutron
# RPC
neutron_oslomsg_rpc_userid: neutron
neutron_oslomsg_rpc_vhost: /neutron
neutron_oslomsg_rpc_transport: "{{ oslomsg_rpc_transport }}"
neutron_oslomsg_rpc_port: "{{ oslomsg_rpc_port }}"
neutron_oslomsg_rpc_servers: "{{ oslomsg_rpc_servers }}"
neutron_oslomsg_rpc_use_ssl: "{{ oslomsg_rpc_use_ssl }}"
neutron_oslomsg_rpc_host_group: "{{ oslomsg_rpc_host_group }}"
neutron_oslomsg_notify_userid: neutron
neutron_oslomsg_notify_vhost: /neutron
neutron_oslomsg_notify_transport: "{{ oslomsg_notify_transport }}"
neutron_oslomsg_notify_port: "{{ oslomsg_notify_port }}"
neutron_oslomsg_notify_servers: "{{ oslomsg_notify_servers }}"
neutron_oslomsg_notify_use_ssl: "{{ oslomsg_notify_use_ssl }}"
neutron_oslomsg_notify_host_group: "{{ oslomsg_notify_host_group }}"
# Shim until octavia role and neutron upgrade is fixed
neutron_rabbitmq_host_group: "{{ oslomsg_rpc_host_group }}"
neutron_rabbitmq_port: "{{ oslomsg_rpc_port }}"
neutron_rabbitmq_servers: "{{ oslomsg_rpc_servers }}"
neutron_rabbitmq_use_ssl: "{{ oslomsg_rpc_use_ssl }}"
neutron_rabbitmq_userid: "{{ neutron_oslomsg_rpc_userid }}"
neutron_rabbitmq_vhost: "{{ neutron_oslomsg_rpc_vhost }}"
neutron_rabbitmq_telemetry_userid: "{{ neutron_rabbitmq_userid }}"
neutron_rabbitmq_telemetry_password: "{{ neutron_rabbitmq_password }}"
neutron_rabbitmq_telemetry_vhost: "{{ neutron_rabbitmq_vhost }}"
neutron_rabbitmq_telemetry_port: "{{ neutron_rabbitmq_port }}"
neutron_rabbitmq_telemetry_servers: "{{ neutron_rabbitmq_servers }}"
neutron_rabbitmq_telemetry_use_ssl: "{{ neutron_rabbitmq_use_ssl }}"
neutron_rabbitmq_telemetry_host_group: "{{ neutron_rabbitmq_host_group }}"

## Nova
nova_oslomsg_rpc_userid: nova
nova_oslomsg_rpc_vhost: /nova
nova_oslomsg_rpc_transport: "{{ oslomsg_rpc_transport }}"
nova_oslomsg_rpc_port: "{{ oslomsg_rpc_port }}"
nova_oslomsg_rpc_servers: "{{ oslomsg_rpc_servers }}"
nova_oslomsg_rpc_use_ssl: "{{ oslomsg_rpc_use_ssl }}"
nova_oslomsg_rpc_host_group: "{{ oslomsg_rpc_host_group }}"
nova_oslomsg_notify_userid: nova
nova_oslomsg_notify_vhost: /nova
nova_oslomsg_notify_transport: "{{ oslomsg_notify_transport }}"
nova_oslomsg_notify_port: "{{ oslomsg_notify_port }}"
nova_oslomsg_notify_servers: "{{ oslomsg_notify_servers }}"
nova_oslomsg_notify_use_ssl: "{{ oslomsg_notify_use_ssl }}"
nova_oslomsg_notify_host_group: "{{ oslomsg_notify_host_group }}"
# Shim until nova upgrade and ceilometer role is fixed
nova_rabbitmq_host_group: "{{ oslomsg_rpc_host_group }}"
nova_rabbitmq_port: "{{ oslomsg_rpc_port }}"
nova_rabbitmq_servers: "{{ oslomsg_rpc_servers }}"
nova_rabbitmq_use_ssl: "{{ oslomsg_rpc_use_ssl }}"
nova_rabbitmq_userid: "{{ nova_oslomsg_rpc_userid }}"
nova_rabbitmq_vhost: "{{ nova_oslomsg_rpc_vhost }}"

## Octavia
octavia_oslomsg_rpc_userid: octavia
octavia_oslomsg_rpc_vhost: /octavia
octavia_oslomsg_rpc_transport: "{{ oslomsg_rpc_transport }}"
octavia_oslomsg_rpc_port: "{{ oslomsg_rpc_port }}"
octavia_oslomsg_rpc_servers: "{{ oslomsg_rpc_servers }}"
octavia_oslomsg_rpc_use_ssl: "{{ oslomsg_rpc_use_ssl }}"
octavia_oslomsg_rpc_host_group: "{{ oslomsg_rpc_host_group }}"
octavia_oslomsg_notify_userid: octavia
octavia_oslomsg_notify_vhost: /octavia
octavia_oslomsg_notify_transport: "{{ oslomsg_notify_transport }}"
octavia_oslomsg_notify_port: "{{ oslomsg_notify_port }}"
octavia_oslomsg_notify_servers: "{{ oslomsg_notify_servers }}"
octavia_oslomsg_notify_use_ssl: "{{ oslomsg_notify_use_ssl }}"
octavia_oslomsg_notify_host_group: "{{ oslomsg_notify_host_group }}"
# Shim until octavia role is fixed
octavia_rabbitmq_host_group: "{{ oslomsg_rpc_host_group }}"
octavia_rabbitmq_port: "{{ oslomsg_rpc_port }}"
octavia_rabbitmq_servers: "{{ oslomsg_rpc_servers }}"
octavia_rabbitmq_use_ssl: "{{ oslomsg_rpc_use_ssl }}"
octavia_rabbitmq_userid: "{{ octavia_oslomsg_rpc_userid }}"
octavia_rabbitmq_vhost: "{{ octavia_oslomsg_rpc_vhost }}"

## Sahara
sahara_oslomsg_rpc_userid: sahara
sahara_oslomsg_rpc_vhost: /sahara
sahara_oslomsg_rpc_transport: "{{ oslomsg_rpc_transport }}"
sahara_oslomsg_rpc_port: "{{ oslomsg_rpc_port }}"
sahara_oslomsg_rpc_servers: "{{ oslomsg_rpc_servers }}"
sahara_oslomsg_rpc_use_ssl: "{{ oslomsg_rpc_use_ssl }}"
sahara_oslomsg_rpc_host_group: "{{ oslomsg_rpc_host_group }}"
sahara_oslomsg_notify_userid: sahara
sahara_oslomsg_notify_vhost: /sahara
sahara_oslomsg_notify_transport: "{{ oslomsg_notify_transport }}"
sahara_oslomsg_notify_port: "{{ oslomsg_notify_port }}"
sahara_oslomsg_notify_servers: "{{ oslomsg_notify_servers }}"
sahara_oslomsg_notify_use_ssl: "{{ oslomsg_notify_use_ssl }}"
sahara_oslomsg_notify_host_group: "{{ oslomsg_notify_host_group }}"

## Swift
swift_oslomsg_rpc_userid: swift
swift_oslomsg_rpc_vhost: /swift
swift_oslomsg_rpc_transport: "{{ oslomsg_notify_transport }}"
swift_oslomsg_rpc_port: "{{ oslomsg_notify_port }}"
swift_oslomsg_rpc_servers: "{{ oslomsg_notify_servers }}"
swift_oslomsg_rpc_use_ssl: "{{ oslomsg_notify_use_ssl }}"
swift_oslomsg_rpc_host_group: "{{ oslomsg_notify_host_group }}"
# TODO: (andymccr) ceilometer with swift does not support SSL rabbitmq connections, so we are hard coding the port and use_ssl var
swift_oslomsg_notify_userid: swift
swift_oslomsg_notify_vhost: /swift
swift_oslomsg_notify_transport: "{{ oslomsg_notify_transport }}"
swift_oslomsg_notify_port: 5672
swift_oslomsg_notify_servers: "{{ oslomsg_notify_servers }}"
swift_oslomsg_notify_use_ssl: False
swift_oslomsg_notify_host_group: "{{ oslomsg_notify_host_group }}"
# Swift is not properly wired yet, so compatibility monkey patching:
# For now swift ceilometer does not work with SSL - this is a speculative option in the hope it gets added
swift_rabbitmq_telemetry_userid: "{{ swift_oslomsg_notify_userid }}"
swift_rabbitmq_telemetry_vhost: "{{ swift_oslomsg_notify_vhost }}"
swift_rabbitmq_telemetry_port: "{{ swift_oslomsg_notify_port }}"
swift_rabbitmq_telemetry_servers: "{{ swift_oslomsg_notify_servers }}"
swift_rabbitmq_telemetry_use_ssl: "{{ swift_oslomsg_notify_use_ssl }}"

## Tacker
tacker_oslomsg_rpc_userid: tacker
tacker_oslomsg_rpc_vhost: /tacker
tacker_oslomsg_rpc_transport: "{{ oslomsg_rpc_transport }}"
tacker_oslomsg_rpc_port: "{{ oslomsg_rpc_port }}"
tacker_oslomsg_rpc_servers: "{{ oslomsg_rpc_servers }}"
tacker_oslomsg_rpc_use_ssl: "{{ oslomsg_rpc_use_ssl }}"
tacker_oslomsg_rpc_host_group: "{{ oslomsg_rpc_host_group }}"
tacker_oslomsg_notify_userid: tacker
tacker_oslomsg_notify_vhost: /tacker
tacker_oslomsg_notify_transport: "{{ oslomsg_notify_transport }}"
tacker_oslomsg_notify_port: "{{ oslomsg_notify_port }}"
tacker_oslomsg_notify_servers: "{{ oslomsg_notify_servers }}"
tacker_oslomsg_notify_use_ssl: "{{ oslomsg_notify_use_ssl }}"
tacker_oslomsg_notify_host_group: "{{ oslomsg_notify_host_group }}"
# Shim until tacker role is fixed
tacker_rabbitmq_host_group: "{{ oslomsg_rpc_host_group }}"
tacker_rabbitmq_port: "{{ oslomsg_rpc_port }}"
tacker_rabbitmq_servers: "{{ oslomsg_rpc_servers }}"
tacker_rabbitmq_use_ssl: "{{ oslomsg_rpc_use_ssl }}"
tacker_rabbitmq_userid: "{{ tacker_oslomsg_rpc_userid }}"
tacker_rabbitmq_vhost: "{{ tacker_oslomsg_rpc_vhost }}"

## Trove
trove_oslomsg_rpc_userid: trove
trove_oslomsg_rpc_vhost: /trove
trove_oslomsg_rpc_transport: "{{ oslomsg_rpc_transport }}"
trove_oslomsg_rpc_port: "{{ oslomsg_rpc_port }}"
trove_oslomsg_rpc_servers: "{{ oslomsg_rpc_servers }}"
trove_oslomsg_rpc_use_ssl: "{{ oslomsg_rpc_use_ssl }}"
trove_oslomsg_rpc_host_group: "{{ oslomsg_rpc_host_group }}"
trove_oslomsg_notify_userid: trove
trove_oslomsg_notify_vhost: /trove
trove_oslomsg_notify_transport: "{{ oslomsg_notify_transport }}"
trove_oslomsg_notify_port: "{{ oslomsg_notify_port }}"
trove_oslomsg_notify_servers: "{{ oslomsg_notify_servers }}"
trove_oslomsg_notify_use_ssl: "{{ oslomsg_notify_use_ssl }}"
trove_oslomsg_notify_host_group: "{{ oslomsg_notify_host_group }}"
# Shim until trove role is fixed
trove_rabbitmq_host_group: "{{ oslomsg_rpc_host_group }}"
trove_rabbitmq_port: "{{ oslomsg_rpc_port }}"
trove_rabbitmq_servers: "{{ oslomsg_rpc_servers }}"
trove_rabbitmq_use_ssl: "{{ oslomsg_rpc_use_ssl }}"
trove_rabbitmq_userid: "{{ trove_oslomsg_rpc_userid }}"
trove_rabbitmq_vhost: "{{ trove_oslomsg_rpc_vhost }}"
