---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Drop Glance Config
  template: >
    src={{ item }}
    dest=/etc/glance/{{ item }}
    owner={{ system_user }}
    group={{ system_group }}
  with_items:
      - policy.json
      - schema.json
      - schema-image.json
  notify: Restart os service

- name: Generate Glance Config
  template: >
    src=template_gen
    dest=/etc/glance/{{ item.file }}
    owner={{ system_user }}
    group={{ system_group }}
  with_items:
      - { file: glance-registry-paste.ini, var: "{{ glance_registry_paste_ini }}" }
      - { file: glance-api-paste.ini, var: "{{ glance_api_paste_ini }}" }
      - { file: glance-registry.conf, var: "{{ glance_registry_conf }}" }
      - { file: glance-api.conf, var: "{{ glance_api_conf }}" }
      - { file: glance-cache.conf, var: "{{ glance_cache_conf }}" }
      - { file: glance-scrubber.conf, var: "{{ glance_scrubber_conf }}" }
  notify: Restart os service
