---
# Copyright 2018, SUSE LINUX GmbH.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# (c) 2018, Jean-Philippe Evrard <jean-philippe@evrard.me>
#ansible_python_interpreter: "{{ ansible_playbook_python }}"
glance_images:
  - url: "http://download.cirros-cloud.net/0.3.5/cirros-0.3.5-x86_64-disk.img"
    dest: "/tmp/cirros-0.3.5.img"
    checksum: "sha256:e137062a4dfbb4c225971b67781bc52183d14517170e16a3841d16f962ae7470"
    format: "qcow2"
    name: "cirros-healthcheck"

cinder_volumes:
  - name: healthcheck1
    size: 1

public_net_cidr: "172.29.248.0/22"
private_net_cidr: "192.168.0.0/24"
public_dns_servers:
  - "8.8.8.8"
  - "8.8.4.4"

neutron_networks:
  public:
    name: public
    shared: True
    external: True
    pn_type: flat
    physical_network: flat
    subnets:
      - name: public-subnet
        ip_version: 4
        cidr: "{{ public_net_cidr }}"
        gateway_ip: "{{ public_net_cidr | ipaddr('1') | ipaddr('address') }}"
        enable_dhcp: "yes"
        allocation_pool_start: "{{ public_net_cidr | ipaddr('201') | ipaddr('address') }}"
        allocation_pool_end:   "{{ public_net_cidr | ipaddr('255') | ipaddr('address') }}"
        dns_nameservers: "{{ public_dns_servers }}"
  private:
    name: PRIVATE_NET
    shared: True
    external: True
    pn_type: vxlan
    segmentation_id: 101
    subnets:
      - name: PRIVATE_NET_v4
        ip_version: 4
        cidr: "{{ private_net_cidr }}"
        gateway_ip: "{{ private_net_cidr | ipaddr('1') | ipaddr('address') }}"
        enable_dhcp: "yes"
        allocation_pool_start: "{{ private_net_cidr | ipaddr('201') | ipaddr('address') }}"
        allocation_pool_end:   "{{ private_net_cidr | ipaddr('254') | ipaddr('address') }}"

heat_stack:
  # Please use the following for a nova app:
  # http://git.openstack.org/cgit/openstack/heat-templates/plain/hot/hello_world.yaml
  source_url: http://git.openstack.org/cgit/openstack/heat-templates/plain/hot/keystone/keystone_domain.yaml
  dest_file: /tmp/mystack.yaml
  name: babar
  tag: dumbo
  parameters:
    domain_name: "babar"
    domain_description: "Babar Kingdom"
    domain_enabled: False # you don't want babar to impact the world of non-elephants.

nova_flavors:
  - name: healthcheck1
    ram: 256
    vcpus: 1
    disk: 1
    swap: 0
    ephemeral: 0

nova_vm:
  name: vm1-healthcheck
  image: cirros-healthcheck
  flavor: healthcheck1
  network: "PRIVATE_NET"

swift_object:
  name: fstab
  container: config
  filename: /etc/fstab

security_group:
  name: healthcheck
  rules:
    - protocol: tcp
      port_range_min: 22
      port_range_max: 22
      remote_ip_prefix: 0.0.0.0/0
    - protocol: tcp
      port_range_min: 5000
      port_range_max: 5000
      remote_ip_prefix: 0.0.0.0/0
    - protocol: icmp
      port_range_min: -1
      port_range_max: -1
      remote_ip_prefix: 0.0.0.0/0

ssh_key: "/root/.ssh/id_rsa-healthcheck"
