---
# Copyright 2017, Logan Vig <logan2211@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Configure keystone for radosgw
  hosts: utility_all
  user: root
  vars_files:
    - "defaults/{{ install_method }}_install.yml"
  tasks:
    - name: Ensure RGW service
      keystone:
        command: "ensure_service"
        endpoint: "{{ keystone_service_adminurl }}"
        login_user: "{{ keystone_admin_user_name }}"
        login_password: "{{ keystone_auth_admin_password }}"
        login_project_name: "{{ keystone_admin_tenant_name }}"
        service_name: "{{ radosgw_service_name }}"
        service_type: "{{ radosgw_service_type }}"
        description: "{{ radosgw_service_description }}"
        insecure: "{{ keystone_service_adminuri_insecure }}"
      run_once: true
      register: add_service
      until: add_service is success
      retries: 5
      delay: 2
      no_log: True
      tags:
        - ceph-rgw-setup
        - rgw-service-add

    - name: Ensure RGW user
      keystone:
        command: "ensure_user"
        endpoint: "{{ keystone_service_adminurl }}"
        login_user: "{{ keystone_admin_user_name }}"
        login_password: "{{ keystone_auth_admin_password }}"
        login_project_name: "{{ keystone_admin_tenant_name }}"
        user_name: "{{ radosgw_admin_user }}"
        tenant_name: "{{ radosgw_admin_tenant }}"
        role_name: "{{ radosgw_role_name | default('service') }}"
        password: "{{ radosgw_admin_password }}"
        insecure: "{{ keystone_service_adminuri_insecure }}"
      run_once: true
      register: add_user
      until: add_user is success
      retries: 5
      delay: 10
      no_log: True
      tags:
        - ceph-rgw-setup
        - rgw-service-add

    - name: Ensure RGW user to admin role
      keystone:
        command: "ensure_user_role"
        endpoint: "{{ keystone_service_adminurl }}"
        login_user: "{{ keystone_admin_user_name }}"
        login_password: "{{ keystone_auth_admin_password }}"
        login_project_name: "{{ keystone_admin_tenant_name }}"
        user_name: "{{ radosgw_admin_user }}"
        tenant_name: "{{ radosgw_admin_tenant }}"
        role_name: "{{ radosgw_role_name | default('admin') }}"
        insecure: "{{ keystone_service_adminuri_insecure }}"
      run_once: true
      register: add_admin_role
      until: add_admin_role is success
      retries: 5
      delay: 10
      no_log: True
      tags:
        - ceph-rgw-setup
        - rgw-service-add

    - name: Ensure swiftoperator role
      keystone:
        command: "ensure_role"
        endpoint: "{{ keystone_service_adminurl }}"
        login_user: "{{ keystone_admin_user_name }}"
        login_password: "{{ keystone_auth_admin_password }}"
        login_project_name: "{{ keystone_admin_tenant_name }}"
        role_name: "swiftoperator"
        insecure: "{{ keystone_service_adminuri_insecure }}"
      run_once: true
      register: add_swiftoperator_role
      until: add_swiftoperator_role is success
      retries: 5
      delay: 10
      no_log: True
      tags:
        - ceph-rgw-setup
        - rgw-service-add

    - name: Ensure RGW endpoint
      keystone:
        command: "ensure_endpoint"
        endpoint: "{{ keystone_service_adminurl }}"
        login_user: "{{ keystone_admin_user_name }}"
        login_password: "{{ keystone_auth_admin_password }}"
        login_project_name: "{{ keystone_admin_tenant_name }}"
        region_name: "{{ radosgw_service_region }}"
        service_name: "{{ radosgw_service_name }}"
        service_type: "{{ radosgw_service_type }}"
        insecure: "{{ keystone_service_adminuri_insecure }}"
        endpoint_list:
          - url: "{{ radosgw_service_publicurl }}"
            interface: "public"
          - url: "{{ radosgw_service_adminurl }}"
            interface: "admin"
          - url: "{{ radosgw_service_internalurl }}"
            interface: "internal"
      run_once: true
      register: add_endpoint
      until: add_endpoint is success
      retries: 5
      delay: 10
      no_log: True
      tags:
        - ceph-rgw-setup
        - rgw-service-add
  tags:
    - ceph-rgw
