---
# Copyright 2016, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Installation and setup of barbican
  hosts: barbican_all
  gather_facts: "{{ osa_gather_facts | default(True) }}"
  user: root
  pre_tasks:
    - include: "common-tasks/os-{{ container_tech | default('lxc') }}-container-setup.yml"
    - include: common-tasks/rabbitmq-vhost-user.yml
      static: no
      vars:
        user: "{{ barbican_rabbitmq_userid }}"
        password: "{{ barbican_rabbitmq_password }}"
        vhost: "{{ barbican_rabbitmq_vhost }}"
        _rabbitmq_host_group: "{{ barbican_rabbitmq_host_group }}"
      when:
        - inventory_hostname == groups['barbican_api'][0]
        - groups[barbican_rabbitmq_host_group] | length > 0

    - include: common-tasks/oslomsg-rpc-vhost-user.yml
      static: no
      vars:
        rpc_user: "{{ barbican_oslomsg_rpc_userid }}"
        rpc_password: "{{ barbican_oslomsg_rpc_password }}"
        rpc_vhost: "{{ barbican_oslomsg_rpc_vhost }}"
      when:
        - inventory_hostname == groups['barbican_api'][0]
        - groups[oslomsg_rpc_host_group] | length > 0
    - include: common-tasks/oslomsg-notify-vhost-user.yml
      static: no
      vars:
        notify_user: "{{ barbican_oslomsg_notify_userid }}"
        notify_password: "{{ barbican_oslomsg_notify_password }}"
        notify_vhost: "{{ barbican_oslomsg_notify_vhost }}"
      when:
        - inventory_hostname == groups['barbican_api'][0]
        - groups[oslomsg_notify_host_group] | length > 0

    - include: common-tasks/os-log-dir-setup.yml
      vars:
        log_dirs:
          - src: "/openstack/log/{{ inventory_hostname }}-barbican"
            dest: "/var/log/barbican"
    - include: common-tasks/mysql-db-user.yml
      static: no
      vars:
        user_name: "{{ barbican_galera_user }}"
        password: "{{ barbican_galera_password }}"
        login_host: "{{ barbican_galera_address }}"
        db_name: "{{ barbican_galera_database }}"
      when: inventory_hostname == groups['barbican_all'][0]
    - include: common-tasks/unbound-clients.yml
      static: no
      when:
        - hostvars['localhost']['resolvconf_enabled'] | bool
  roles:
    - role: "os_barbican"

  post_tasks:
    - include_tasks: "common-tasks/rsyslog-client.yml"
      vars:
        rsyslog_client_log_rotate_file: barbican_log_rotate
        rsyslog_client_log_dir: "/var/log/barbican"
        rsyslog_client_config_name: "99-barbican-rsyslog-client.conf"

  environment: "{{ deployment_environment_variables | default({}) }}"
  tags:
    - barbican
