---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Installation and setup of Nova
  hosts: nova_all
  gather_facts: "{{ gather_facts | default(True) }}"
  max_fail_percentage: 20
  user: root
  pre_tasks:
    - include: common-tasks/rabbitmq-servers-sort.yml
      vars:
        sort_group_name: "nova_all"
    - include: common-tasks/os-lxc-container-setup.yml
    - include: common-tasks/rabbitmq-vhost-user.yml
      vars:
        user: "{{ nova_rabbitmq_userid }}"
        password: "{{ nova_rabbitmq_password }}"
        vhost: "{{ nova_rabbitmq_vhost }}"
      when:
        - inventory_hostname == groups['nova_all'][0]
        - groups['rabbitmq_all'] | length > 0
    - include: common-tasks/os-log-dir-setup.yml
      vars:
        log_dirs:
          - src: "/openstack/log/{{ inventory_hostname }}-nova"
            dest: "/var/log/nova"
    - include: common-tasks/mysql-db-user.yml
      vars:
        user_name: "{{ nova_galera_user }}"
        password: "{{ nova_container_mysql_password }}"
        login_host: "{{ nova_galera_address }}"
        db_name: "{{ nova_galera_database }}"
      when: inventory_hostname == groups['nova_all'][0]
    - include: common-tasks/mysql-db-user.yml
      vars:
        user_name: "{{ nova_api_galera_user }}"
        password: "{{ nova_api_container_mysql_password }}"
        login_host: "{{ nova_api_galera_address }}"
        db_name: "{{ nova_api_galera_database }}"
      when: inventory_hostname == groups['nova_all'][0]
    - include: common-tasks/package-cache-proxy.yml

    - name: Add nbd devices to the compute
      shell: |
        for i in /dev/nbd*;do
          lxc-device -n {{ container_name }} add $i $i
        done
      failed_when: false
      register: device_add
      changed_when: >
        'added' in device_add.stdout.lower()
      delegate_to: "{{ physical_host }}"
      when:
        - "inventory_hostname in groups['nova_compute']"
        - "not is_metal | bool"
      tags:
        - nova-kvm
        - nova-kvm-container-devices
    - name: Add net/tun device to the compute
      shell: |
        lxc-device -n {{ container_name }} add /dev/net/tun /dev/net/tun
      delegate_to: "{{ physical_host }}"
      when:
        - "inventory_hostname in groups['nova_compute']"
        - "not is_metal | bool"
      tags:
        - nova-kvm
        - nova-kvm-container-devices
    - name: Check if kvm device exists
      stat:
        path: /dev/kvm
      delegate_to: "{{ physical_host }}"
      register: kvm_device
      when:
        - "inventory_hostname in groups['nova_compute']"
        - "not is_metal | bool"
      tags:
        - nova-kvm
        - nova-kvm-container-devices
    - name: Add kvm device to the compute
      shell: |
        lxc-device -n {{ container_name }} add /dev/kvm /dev/kvm
      delegate_to: "{{ physical_host }}"
      register: device_add
      failed_when: false
      changed_when: >
        'added' in device_add.stdout.lower()
      when:
        - "inventory_hostname in groups['nova_compute']"
        - "not is_metal | bool"
        - kvm_device.stat.ischr is defined and kvm_device.stat.ischr
      tags:
        - nova-kvm
        - nova-kvm-container-devices
    - name: Set nova management bridge (is_metal)
      set_fact:
        management_bridge: "{{ 'ansible_' + hostvars[inventory_hostname]['management_bridge'] | replace('-', '_') }}"
      when:
        - "hostvars[inventory_hostname]['management_bridge'] is defined"
        - "is_metal | bool"
      tags:
        - nova-config
    - name: Set nova management address (is_metal)
      set_fact:
        management_address: "{{ hostvars[inventory_hostname][management_bridge]['ipv4']['address'] }}"
      when:
        - "hostvars[inventory_hostname][management_bridge]['ipv4']['address'] is defined"
        - "is_metal | bool"
      tags:
        - nova-config
    - name: Set nova management address (container)
      set_fact:
        management_address: "{{ hostvars[inventory_hostname]['container_networks']['container_address']['address'] }}"
      when:
        - "management_address is undefined"
        - "hostvars[inventory_hostname]['container_networks']['container_address']['address'] is defined"
        - "not is_metal | bool"
      tags:
        - nova-config
    - name: Set nova management address (unknown management network)
      set_fact:
        management_address: "{{ ansible_ssh_host }}"
      when:
        - "management_address is undefined"
      tags:
        - nova-config
  roles:
    - role: "os_nova"
      nova_novncproxy_git_repo: "{{ openstack_repo_git_url }}/novnc"
      nova_novncproxy_git_install_branch: "{{ novncproxy_git_install_branch }}"
      nova_spicehtml5_git_repo: "{{ openstack_repo_git_url }}/spice-html5"
      nova_spicehtml5_git_install_branch: "{{ spicehtml5_git_install_branch }}"
      nova_management_address: "{{ management_address }}"
      nova_venv_tag: "{{ openstack_release }}"
      nova_venv_download_url: "{{ openstack_repo_url }}/venvs/{{ openstack_release }}/{{ ansible_distribution | lower }}/nova-{{ openstack_release }}.tgz"
      tags:
        - "os-nova"
    - role: "ceph_client"
      nova_venv_bin: "/openstack/venvs/nova-{{ openstack_release }}/bin"
      openstack_service_system_user: "{{ nova_system_user_name }}"
      openstack_service_venv_bin: "{{ nova_venv_bin if nova_venv_enabled|default(True)|bool else None }}"
      tags:
        - "nova-ceph-client"
        - "ceph-client"
    - role: "openstack_openrc"
      tags:
        - "openstack-openrc"
    - role: "rsyslog_client"
      rsyslog_client_log_rotate_file: nova_log_rotate
      rsyslog_client_log_dir: "/var/log/nova"
      rsyslog_client_config_name: "99-nova-rsyslog-client.conf"
      tags:
        - "nova-rsyslog-client"
        - "rsyslog-client"
    - role: "system_crontab_coordination"
      tags:
        - "system-crontab-coordination"
  vars_files:
    - defaults/repo_packages/openstack_other.yml
  vars:
    is_metal: "{{ properties.is_metal|default(false) }}"
    nova_galera_user: nova
    nova_galera_database: nova
    nova_api_galera_user: nova_api
    nova_api_galera_database: nova_api
    nova_galera_address: "{{ galera_address }}"
    nova_api_galera_address: "{{ galera_address }}"
    glance_host: "{{ internal_lb_vip_address }}"
    nova_rabbitmq_userid: nova
    nova_rabbitmq_vhost: /nova
    nova_rabbitmq_servers: "{{ rabbitmq_servers }}"
    nova_rabbitmq_port: "{{ rabbitmq_port }}"
    nova_rabbitmq_use_ssl: "{{ rabbitmq_use_ssl }}"
    pip_lock_to_internal_repo: "{{ (pip_links | length) >= 1 }}"
